os-fpga/FOEDAG

.gitmodules

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [x] Engine

Add tcl as a submodule

---

.github/bin/run-clang-format.sh
CMakeLists.txt
src/Main/main.cpp
src/Tcl/HelloTcl_test.cpp
src/Tcl/TclInterpreter.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Fix dependancy for tcl rebuild

---

CMakeLists.txt
src/Tcl/HelloTcl_test.cpp
src/Tcl/TclInterpreter.cpp
src/Tcl/TclInterpreter.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Enable Google Tests for Tcl

---

INSTALL.md
docs/requirements.txt
docs/source/conf.py
docs/source/index.rst
docs/source/tutorials/getting_started/build_instructions.rst
docs/source/tutorials/getting_started/dependencies.rst
docs/source/tutorials/getting_started/index.rst
docs/source/tutorials/index.rst

> 
> 
Currently, FOEDAG has the following limitations:
- No documentation about build instructions (only in INSTALL.md) and dependency requirements
>
> 
> 
This PR improves in the following aspects: 
> 
> - [ ] Engine
> - [x] Documentation
> - [ ] Continous Integration (CI) …

Update documentation to include build instructions from INSTALL.md

---

.github/workflows/install_ubuntu_dependencies_build.sh
.github/workflows/main.yml
CMakeLists.txt
Makefile
src/Main/CommandLine.cpp
src/Main/CommandLine.h
src/Main/foedag.h
src/Main/main.cpp
src/Main/registerTclCommands.cpp
src/MainWindow/Session.h
src/Tcl/TclInterpreter.cpp
src/Tcl/TclInterpreter.h
tests/TestGui/gui_start_stop.tcl
tests/TestInstall/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Headless Gui testing

---

CMakeLists.txt
Makefile
src/Command/Command.cpp
src/Command/Command.h
src/Command/CommandStack.cpp
src/Command/CommandStack.h
src/Command/Command_test.cpp
src/Main/CommandLine.cpp
src/Main/CommandLine.h
src/Main/GuiMain_test.cpp
src/Main/foedag.h
src/Main/main.cpp
src/Main/registerTclCommands.cpp
src/MainWindow/Session.cpp
src/MainWindow/Session.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/Tcl/HelloTcl_test.cpp
src/Tcl/TclInterpreter.cpp
src/Tcl/TclInterpreter.h
tests/TestGui/gui_start_stop.tcl
tests/TestInstall/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

License banners

---

.github/workflows/main.yml
INSTALL.md
Makefile

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Macos GUI testing

---

.github/workflows/main.yml
Makefile
tests/TestGui/gui_start_stop.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Macos gui test

---

Makefile
src/Main/CommandLine.cpp
src/Main/main.cpp
src/Tcl/TclInterpreter.cpp
tests/TestGui/gui_start_stop.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Gui Test harness

---

src/Main/CommandLine.cpp
src/Main/CommandLine.h
src/Main/foedag.h
src/Main/main.cpp
src/Main/registerTclCommands.cpp
src/MainWindow/Session.cpp
src/Tcl/TclInterpreter.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Allow specialization of the command line

---

Makefile
tests/TestBatch/hello.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

batch test

---

CMakeLists.txt
src/Command/CommandStack.cpp
src/Command/Logger.cpp
src/Command/Logger.h
src/Main/registerTclCommands.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Command logger

---

.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Install QT on msys

---

.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Msys2 support

---

.github/workflows/main.yml
Makefile

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

make lib-only for msys2

---

CMakeLists.txt
src/NewProject/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Top cmake cleanup

---

Makefile
src/Main/Foedag.cpp
src/Main/Foedag.h
src/Main/main.cpp
src/MainWindow/Session.h
src/NewProject/Main/newproject_main.cpp
tests/TestGui/gui_new_project.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Allow replay infra to work with any widget

---

CMakeLists.txt
src/NewProject/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

make cmake of NewProject as standalone as possible

---

src/NewProject/CMakeLists.txt
src/NewProject/ProjectManager/config.cpp
src/NewProject/ProjectManager/project_configuration.cpp

> - [x] To address an existing issue. If so, please provide a link to the issue: #88 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
Warning clean up.
Change to file list.
> 
> - [ ] Engine
> - [ ] Break back-compatibility. If so, …

Warning clean up

---

src/NewProject/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

remove Wno-deprecated-declarations flag

---

cmake/cmake_qt.txt
cmake/cmake_tcl.txt
src/NewProject/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Common cmake parts for subsystems

---

CMakeLists.txt
src/Console/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Add Console sub-project

---

src/Main/CommandLine.cpp
src/Main/registerTclCommands.cpp
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/NewProject/Main/newproject_main.cpp
src/NewProject/ProjectManager/config.cpp
src/NewProject/ProjectManager/config.h
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/NewProject/device_planner_form.cpp
src/NewProject/new_project_dialog.cpp
src/NewProject/new_project_dialog.h
src/NewProject/source_grid.cpp
src/NewProject/summary_form.cpp

> - [x] To address an existing issue. If so, please provide a link to the issue: #77 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
You can use the tcl command to create a project like this:
> create_project --file project.xml
project.xml format example
```
<project type="RTL" name="project_1" path="/root/Desktop">
<device name="x7c100t"/>
<sources>
<source file="/root/counter.v" is_top="true"/>
</sources>
<constraints>
<constraint file="/root/counter.sdc"/>
</constraints>
<testbenches>
<testbench file="/root/counter_t.v"/>
</testbenches> …
```

Add create_project tcl command

---

src/NewProject/ProjectManager/project_configuration.cpp
src/NewProject/ProjectManager/project_configuration.h
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/NewProject/new_project_dialog.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
When you click finish, the default topmodule file and simulation source file will be set.
> 
> - [ ] Engine
> - [ ] Require a change on Quality of …

Set default files

---

.github/workflows/main.yml
CMakeLists.txt
Makefile
src/Compiler/CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/Design.cpp
src/Compiler/Design.h
src/Compiler/Test/compiler_main.cpp
src/Compiler/WorkerThread.cpp
src/Compiler/WorkerThread.h
src/MainWindow/Session.h
tests/TestBatch/test_compiler_batch.tcl
tests/TestBatch/test_compiler_mt.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Compiler wrapper

---

.github/workflows/main.yml
Makefile

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

test/batch on Windows

---

CMakeLists.txt
src/Main/CMakeLists.txt
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/NewProject/new_project_dialog.cpp
src/ProjNavigator/sources_form.cpp
src/ProjNavigator/sources_form.h
src/TextEditor/CMakeLists.txt
src/TextEditor/Test/texteditor_main.cpp
src/TextEditor/editor.cpp
src/TextEditor/editor.h
src/TextEditor/search_dialog.cpp
src/TextEditor/search_dialog.h
src/TextEditor/text_editor.cpp
src/TextEditor/text_editor.h
src/TextEditor/text_editor_form.cpp
src/TextEditor/text_editor_form.h
tests/TestInstall/CMakeLists.txt
third_party/QScintilla-2.13.1/CMakeLists.txt

> - [x] Breaking new feature. If so, please describe details in the description part. #105 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [ ] Break back-compatibility. If so, please list who may be …

add search dialog and integration into mian GUI

---

src/Main/registerTclCommands.cpp
src/NewProject/new_project_dialog.cpp
src/Tcl/TclInterpreter.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

corrected event processing

---

.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Macos support

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/Test/compiler_main.cpp
src/Main/Foedag.cpp
src/Tcl/TclInterpreter.cpp
tests/TestBatch/test_compiler_batch.tcl
tests/TestBatch/test_compiler_mt.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

batch command

---

src/Compiler/Compiler.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

fix error of batch command in console

---

tests/TestBatch/hello.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

fix valgrind test

---

.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

autoconf for Msys2

---

src/Console/FileInfo.cpp
src/Console/FileInfo.h
src/Console/TclConsole.cpp
src/Console/TclConsole.h
src/Console/TclConsoleWidget.cpp
src/Console/TclConsoleWidget.h
third_party/QConsole/include/qconsole.h
third_party/QConsole/src/qconsole.cpp

Add source command autocompletion
improve console.

Add source command auto completion

---

src/Console/CMakeLists.txt
src/Console/SearchWidget.cpp
src/Console/SearchWidget.h
src/Console/TclConsoleBuilder.h
src/Console/TclConsoleWidget.cpp
src/Console/TclConsoleWidget.h
src/Console/Test/console_standalone.cpp
src/MainWindow/main_window.cpp
third_party/QConsole/include/qconsole.h
third_party/QConsole/src/qconsole.cpp

Add search functionality into the console (close #139)

---

src/Console/TclConsoleWidget.cpp
src/Console/TclConsoleWidget.h
third_party/QConsole/include/qconsole.h
third_party/QConsole/src/qconsole.cpp

Add basic support for multiline (close #140)

---

CMakeLists.txt
third_party/tcl_cmake/CMakeLists.txt
third_party/zlib/zlib_make.cmake

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Simplify toplevel cmake

---

CMakeLists.txt
third_party/tcl_cmake/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

cmake style

---

.vscode/launch.json
src/Compiler/Compiler.cpp
src/Main/Foedag.cpp
src/Tcl/TclHistoryScript.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

fix batch cmd error

---

.github/workflows/install_ubuntu_dependencies_build.sh
.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Qt declarative dev

---

src/Console/ConsoleInterface.h
src/Console/TclConsole.cpp
src/Console/TclConsole.h
src/Console/TclConsoleWidget.cpp
src/Console/TclConsoleWidget.h
src/Console/TclWorker.cpp
third_party/QConsole/include/qconsole.h
third_party/QConsole/src/qconsole.cpp

Tcl script cancelation (close os-fpga#147)

---

.github/bin/run-clang-format.sh
src/Console/CMakeLists.txt
src/Console/ConsoleDefines.cpp
src/Console/ConsoleDefines.h
src/Console/ConsoleInterface.cpp
src/Console/ConsoleInterface.h
src/Console/StreamBuffer.cpp
src/Console/StreamBuffer.h
src/Console/TclConsole.cpp
src/Console/TclConsole.h
src/Console/TclConsoleBuilder.cpp
src/Console/TclConsoleWidget.cpp
src/Console/TclConsoleWidget.h
src/Console/TclWorker.cpp
src/Console/TclWorker.h
src/Console/Test/console_main.cpp
src/Console/Test/console_standalone.cpp
src/MainWindow/main_window.cpp

The purpose of this PR is:
* add FOEDAG namespaces where it required
* better handling puts command
* Fixing clang warnings
* localize tcl lib warnings in one file (ConsoleDefines.h/cpp)
* remove dependencies

Console refactoring

---

.github/bin/run-clang-format.sh

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

revert back the clang-format policy

---

src/Console/CMakeLists.txt
src/Console/TclConsoleBuilder.cpp
src/Console/TclConsoleBuilder.h
src/Console/TclConsoleWidget.cpp
src/Console/TclConsoleWidget.h
src/Console/Test/ConsoleTestUtils.h
src/Console/Test/console_main.cpp
tests/TestGui/gui_console_proc.tcl

Add some infrastructure for the console testing.
Add few new tests.

Add real tests for the console (close #133)

---

Makefile
src/Console/Test/ConsoleTestUtils.h
src/Console/Test/console_main.cpp
tests/TestGui/gui_console.tcl
tests/TestGui/gui_console_proc.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Console test

---

.vscode/launch.json
Makefile
src/Console/TclConsoleWidget.h
src/Console/Test/console_main.cpp
src/Tcl/TclInterpreter.cpp
tests/TestGui/gui_console_negative_test.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Negative test and tcl error check

---

src/Console/CMakeLists.txt
src/Console/Test/ConsoleTestUtils.cpp
src/Console/Test/ConsoleTestUtils.h
src/Console/Test/TestingUtils.cpp
src/Console/Test/TestingUtils.h
src/Console/Test/console_main.cpp
src/Console/Test/console_test.cpp

Propose tcl testing platform that is similar to gtest.

suggest tcl testing framework basics

---

src/Console/Test/console_test.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

tcl string format

---

src/Console/CMakeLists.txt
src/Console/Test/ConsoleTestUtils.h
src/Console/Test/TestingUtils.cpp
src/Console/Test/TestingUtils.h
src/Console/Test/console_main.cpp
src/Console/Test/console_test.cpp

Few updates to testing stuff

---

src/Console/TclConsoleWidget.cpp
src/Console/Test/ConsoleTestUtils.cpp
src/Console/Test/ConsoleTestUtils.h
src/Console/Test/console_test.cpp
tests/TestGui/gui_console.tcl
third_party/QConsole/include/qconsole.h
third_party/QConsole/src/qconsole.cpp

Add possibility to cancel when typing multiline command after few line.

Add cancelation of multiline. Add test for that.

---

DEPENDENCIES.md

Added dependencies for ubuntu 20.10 to documentation
Added dependencies for QtQuick Controls 2 to documentation

Dependencies for ubuntu 20.10 and QtQuick controls 2

---

src/Console/TclConsoleBuilder.cpp
src/Console/TclConsoleBuilder.h
src/Console/TclConsoleWidget.cpp
src/Console/TclConsoleWidget.h
src/Console/TclWorker.cpp
src/Console/TclWorker.h
src/Console/Test/ConsoleTestUtils.cpp
src/Console/Test/ConsoleTestUtils.h
src/Console/Test/console_main.cpp
src/Console/Test/console_test.cpp
tests/TestGui/gui_console.tcl

rework a bit tests and simplify code for tcl worker class.

Console simplify code

---

src/Console/TclConsoleWidget.cpp
src/Console/Test/ConsoleTestUtils.cpp
src/Console/Test/ConsoleTestUtils.h
src/Console/Test/console_test.cpp
tests/TestGui/gui_console.tcl
third_party/QConsole/include/qconsole.h
third_party/QConsole/src/qconsole.cpp

Issue 153 multiline improve

---

.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

windows ci

---

src/Compiler/Compiler.cpp
src/Console/CMakeLists.txt
src/Console/DummyParser.cpp
src/Console/DummyParser.h
src/Console/FileInfo.cpp
src/Console/FileInfo.h
src/Console/OutputFormatter.cpp
src/Console/OutputFormatter.h
src/Console/TclConsoleWidget.cpp
src/Console/TclConsoleWidget.h
src/Console/Test/console_standalone.cpp

Close #148 
For test run synth
I put some filenames for the compiler output and the console is able to add file links and emit signal with file path.

Issue 148 hyperlinks

---

third_party/tcl_cmake/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

VS version

---

.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

centos build

---

.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fix centos7 build

---

.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

test centos

---

.github/workflows/install_centos_dependencies_build.sh
.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

centos build in bash

---

.github/workflows/install_centos_dependencies_build.sh
.github/workflows/main.yml
third_party/tcl_cmake/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

artifact QT build

---

.github/workflows/install_centos_dependencies_build.sh
.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Centos QT artifact

---

.github/workflows/install_centos_dependencies_build.sh
.github/workflows/main.yml

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

download artifact

---

.github/workflows/install_centos_dependencies_build.sh
Makefile
src/Tcl/TclInterpreter.cpp

Centos fix

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/TclInterpreterHandler.h
src/Compiler/WorkerThread.cpp
src/Console/ConsoleInterface.h
src/Console/TclConsole.cpp
src/Console/TclConsole.h
src/Console/TclWorker.cpp
src/Console/TclWorker.h
src/Console/Test/console_standalone.cpp
src/Main/CMakeLists.txt
src/Main/CompilerNotifier.cpp
src/Main/CompilerNotifier.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fixed running compiler operations (close #187 #199)

---

src/Main/CMakeLists.txt
src/Main/Foedag.cpp
src/MainWindow/Session.cpp
src/MainWindow/TopLevelInterface.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Start main window at the begin and show all features

---

.github/workflows/install_centos_dependencies_build.sh

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

artifact path

---

src/MainWindow/main_window.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

register compiler commands

---

tests/TestInstall/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

test_install build

---

third_party/tcl_cmake/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

tcl_cmake source location

---

src/MainWindow/main_window.cpp

After opening a project, it looks like this.

gui widgets layout

---

.github/workflows/main.yml
third_party/tcl_cmake/CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Tcl build path on Windows 

---

src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

Don't always show default project name

---

src/NewProject/ProjectManager/project_manager.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

fixed 'QFSFileEngine::open: No file name specified'

---

src/Console/TclConsoleBuilder.cpp
src/Main/registerTclCommands.cpp
tests/TestGui/gui_console.tcl

Here is basic functionality for getting qt widgets into tcl (#236 )

Add basic functionality for getting qt widgets in tcl (issue #236)

---

CMakeLists.txt

Linkage issue on macos in make test_install

Qt::XML dept

---

CMakeLists.txt
Makefile
examples/sample_project/sample_project.ospr

> - [x] To address an existing issue. If so, please provide a link to the issue: #252 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

install Example design

---

src/Compiler/CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/CompilerDefines.cpp
src/Compiler/CompilerDefines.h
src/Compiler/Task.cpp
src/Compiler/Task.h
src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h
src/Compiler/TaskTableView.cpp
src/Compiler/TaskTableView.h
src/MainWindow/main_window.cpp

Code refactoring, remove unused code (close #242)

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Small refactoring

---

src/Compiler/CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/Design.h
src/Compiler/DesignManager.cpp
src/Compiler/DesignManager.h
src/MainWindow/main_window.cpp
src/ProjNavigator/CMakeLists.txt
src/ProjNavigator/Test/projectnavigator_commands.cpp
src/ProjNavigator/sources_form.cpp
src/ProjNavigator/sources_form.h
src/ProjNavigator/tcl_command_integration.cpp
src/ProjNavigator/tcl_command_integration.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Sync Design struct with project (#260)

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h

Fixed error message on the 1rst carriage return (#268)

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h

Revert "Fixed error message on the 1rst carriage return (#268)"

---

src/Compiler/TaskTableView.cpp
src/Main/main.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Make sure compiler resources is initialized

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp

Fixed create_design (close #294)

---

src/Compiler/Compiler.cpp
src/Console/CMakeLists.txt
src/Console/TclErrorParser.cpp
src/Console/TclErrorParser.h
src/Console/TclWorker.cpp
src/Console/Test/console_standalone.cpp
src/MainWindow/main_window.cpp
src/Tcl/HelloTcl_test.cpp
src/Tcl/TclInterpreter.cpp
src/Tcl/TclInterpreter.h

Add tcl stack trace (close #299)

---

src/Compiler/Compiler.cpp
src/Console/TclWorker.cpp

Redirrect stderr from compiler into the tcl console (close #302)

---

src/Compiler/Compiler.cpp
src/Compiler/WorkerThread.cpp
src/Compiler/WorkerThread.h
src/Main/CompilerNotifier.cpp
src/Main/CompilerNotifier.h
tests/Testcases/raygentop/raygentop.tcl

* Avoid using batch mode for compiler steps
* Make GUI alive when compiler steps is in progress

Add thread queue for compiler steps

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/WorkerThread.cpp
src/Compiler/WorkerThread.h
tests/Testcases/raygentop/raygentop.tcl

Close #312 
Remove useless extra command for sync.

Fixed tests/Testcases/trivial/test.tcl (close #312)

---

third_party/QConsole/include/qconsole.h
third_party/QConsole/src/qconsole.cpp

Now Enter key press works always.
When arrow up text always visible.

Fixed text visibility when arrow up (close #268)

---

src/Compiler/Compiler.cpp
src/ProjNavigator/Test/projectnavigator_commands.cpp
src/ProjNavigator/tcl_command_integration.cpp
src/ProjNavigator/tcl_command_integration.h

Fixed add_design_file command (close #325)

---

src/Compiler/TaskManager.cpp
src/Console/ConsoleInterface.h
src/Console/SearchWidget.cpp
src/Console/TclConsole.cpp
src/Console/TclConsoleWidget.cpp
src/Console/TclWorker.cpp
src/Console/TclWorker.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
third_party/QConsole/include/qconsole.h
third_party/QConsole/src/qconsole.cpp

Fixed Stop button (Close #328)

---

src/Compiler/CompilerOpenFPGA.cpp

Added `-l <DESIGN_NAME>_synth.log` to Yosys command which creates `<DESIGN_NAME>_synth.log` logfile.

Added synthesis logfile for OpenFPGA compiler.

---

src/Console/DummyParser.cpp
src/Console/OutputFormatter.cpp
src/Console/OutputFormatter.h
src/Console/TclConsoleWidget.cpp
src/Console/TclErrorParser.cpp
src/TextEditor/text_editor_form.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fixed open file when click in the console

---

src/Compiler/WorkerThread.cpp
src/Compiler/WorkerThread.h

Improve foedag performance while compile (close #353)

---

src/Compiler/WorkerThread.cpp
src/Compiler/WorkerThread.h

Revert "Improve foedag performance while compile (close #353)"

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/DesignRuns/runs_form.cpp
src/Main/Foedag.cpp
src/Main/main.cpp
src/NewProject/ProjectManager/project_fileset.cpp
src/NewProject/ProjectManager/project_fileset.h
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/ProjNavigator/tcl_command_integration.cpp
src/ProjNavigator/tcl_command_integration.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Compiler gui sync

---

src/Main/Foedag.cpp

Revert "Disable settings temporarily"

---

src/Console/StreamBuffer.cpp
src/Console/StreamBuffer.h
src/Console/TclConsoleWidget.cpp
src/Console/TclWorker.cpp

Improve redirrecting output into tcl console (close #362)

---

src/Compiler/Compiler.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fixed compiler tasks that where unable to run after fail (Close #398)

---

src/NewProject/ProjectManager/project_fileset.cpp
src/NewProject/ProjectManager/project_fileset.h
src/NewProject/ProjectManager/project_manager.cpp

Fixed file order for add_source_file (close #402)

---

src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/newproject.qrc
src/NewProject/templates/verilog_templ.v
src/NewProject/templates/vhdl_templ.vhd

Replace code by some templates.

Add few template files

---

src/Command/CommandStack.cpp
src/Command/CommandStack.h
src/Compiler/Compiler.cpp
src/Console/TclConsoleWidget.cpp

Add console and compiler tasks logging

Add console and compiler tasks logging

---

src/Command/CommandStack.cpp
src/Command/CommandStack.h
src/Command/Logger.cpp
src/Command/Logger.h
src/Console/TclConsoleWidget.cpp
src/Main/Foedag.cpp

For the GUI mode add logging to the file.

Add logging everything to file (only in GUI mode)

---

src/MainWindow/main_window.cpp
src/ProjNavigator/CMakeLists.txt
src/ProjNavigator/PropertyWidget.cpp
src/ProjNavigator/PropertyWidget.h
src/ProjNavigator/add_file_form.cpp
src/ProjNavigator/sources_form.cpp
src/ProjNavigator/sources_form.h
src/ProjNavigator/tcl_command_integration.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Update project navigator, add property window

---

src/Command/CommandStack.cpp
src/Command/CommandStack.h
src/Compiler/CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/Log.cpp
src/Compiler/Log.h
src/Compiler/ProcessUtils.cpp
src/Compiler/ProcessUtils.h
src/Main/Foedag.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Add perf logging (linux only now) - time and utilization

---

src/TextEditor/editor.cpp

Fixed shortcut for serach in the text editor (close #437)

---

src/Compiler/CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerDefines.cpp
src/Compiler/CompilerDefines.h
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/Constraints.h
src/Compiler/Test/compiler_main.cpp
src/NewProject/ProjectManager/project_fileset.cpp
src/NewProject/ProjectManager/project_fileset.h
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/ProjNavigator/add_file_dialog.cpp
src/ProjNavigator/tcl_command_integration.cpp

Fixed file grouping (#440)

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/NewProject/ProjectManager/project_fileset.cpp
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h

Fixed project open:
-- add file grouping to project file
-- fixed compiler steps after project opened (problem with paths)

Fixed project open:

---

src/NewProject/ProjectManager/project_fileset.cpp
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/ProjNavigator/sources_form.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fixed remove file from the project via context menu

---

src/Command/CommandStack.cpp
src/Command/CommandStack.h
src/Compiler/Compiler.cpp
src/Compiler/Log.h
src/Console/StreamBuffer.cpp
src/Console/StreamBuffer.h
src/Console/TclConsole.cpp
src/Console/TclConsoleWidget.cpp
src/Console/TclWorker.cpp
src/Console/TclWorker.h
src/Main/Foedag.cpp
src/Main/Foedag.h
src/Main/registerTclCommands.cpp

Add file logging in batch mode

---

src/Command/CommandStack.cpp
src/Command/CommandStack.h
src/Compiler/Log.h
src/Main/CommandLine.cpp
src/Main/CommandLine.h
src/Main/Foedag.cpp

Add mute command key (close #442)

---

src/Console/TclConsoleWidget.cpp
src/Console/TclConsoleWidget.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fixed shell command like "ls *.log"

---

src/Main/CMakeLists.txt
src/Main/Foedag.cpp
src/Main/FoedagStyle.cpp
src/Main/FoedagStyle.h
src/TextEditor/text_editor_form.cpp

Add foedag style class. This is should be the central place where the whole application style could be changed.

Add foedag style

---

src/Compiler/TaskModel.cpp
src/Compiler/TaskTableView.cpp
src/Compiler/TaskTableView.h

Window: fixed compiler table buttons.

Fixed buttons view on compiler task table

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerDefines.cpp
src/Compiler/CompilerDefines.h
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/Task.h
src/Compiler/TaskManager.cpp
src/Compiler/TaskModel.cpp
src/Compiler/TaskTableView.cpp

Add clean action into compiler task table.
Fixed clean actions here:

Add clean action into compiler task table

---

src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h

Add basic code for project files backward compatibility (close #413 )

Add basic code for project files backward compatibility (close #413)

---

src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/NewProject/create_file_dialog.cpp
src/NewProject/create_file_dialog.h
src/NewProject/source_grid.cpp
src/NewProject/source_grid.h
src/ProjNavigator/add_file_dialog.cpp
src/ProjNavigator/add_file_form.cpp

Issue 396 failed to create file

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/MainWindow/main_window.cpp

Remove FOEDAG::Compiler::m_hardError

---

Makefile
tests/TestGui/foedag_proc.tcl
tests/TestGui/gui_foedag_negetive_test.tcl

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

valgrind fix

---

src/Main/ProjectFile/ProjectFileLoader.h
src/MainWindow/main_window.cpp
src/NewProject/ProjectManager/project.h
src/NewProject/ProjectManager/project_manager.cpp

Fix problem with missing project file.
Here are the steps how to reproduce bug:
* Open FOEDAG
* Press New Project
* Follow all steps and press finish.
Expected result: project file .ospr exists in the project folder.
Actual result: project file is missing

Fixed missed project file

---

src/NewProject/ProjectManager/project_manager.cpp

Fixed path to the files that where created from the GUI.
In order to reproduce it need to do steps from
https://github.com/os-fpga/FOEDAG/tree/main/tests/Testcases/bgm
but create new file for bgm.v
The project won't compile.

Fixed file path for new created files.

---

src/Compiler/CompilerOpenFPGA.cpp
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h

When user modify constraint file it doesn't take effect on project. 
Add read_sdc before synth.

Update constraints before synth

---

src/MainWindow/main_window.cpp

Fixed typo

---

src/NewProject/add_source_form.cpp
src/NewProject/add_source_form.ui
src/NewProject/create_file_dialog.cpp
src/NewProject/device_planner_form.cpp
src/NewProject/location_form.cpp
src/NewProject/location_form.ui
src/NewProject/new_project_dialog.cpp
src/NewProject/new_project_dialog.ui
src/NewProject/newprojectmodel.cpp
src/NewProject/project_type_form.cpp
src/NewProject/project_type_form.ui
src/NewProject/source_grid.cpp
src/NewProject/summary_form.cpp
src/NewProject/summary_form.ui
src/ProjNavigator/add_file_form.cpp

To address an existing issue. If so, please check https://github.com/os-fpga/FOEDAG/issues/467#issue-1273848352
Changes:
Improved the formatting/wording issues.
Capitalize Next Button
Add a space after each comma for the following parts:
"Next,you will specify..."
"Finally,you will specify..."
"You will be able to add sources,create block designs in IP integrator,generate IP, run RTL    analysis,synthesis,implementation,design planning and analysis."

Fixed Typos in Create New Project

---

src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Add progress bar for compilations tasks

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/CompilerOpenFPGA.h

Show clear message to user that target device or architecture file was not specify.
Check target device and architecture files before synth or place.
Show message in case architecture files were specify but unable to find them.

Show error if target device or architecture files not specified.

---

src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fixed issue with arch file path

---

CMakeLists.txt
Makefile
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/PinAssignment/CMakeLists.txt
src/PinAssignment/ConstraintCreator.cpp
src/PinAssignment/ConstraintCreator.h
src/PinAssignment/PackagePinsLoader.cpp
src/PinAssignment/PackagePinsLoader.h
src/PinAssignment/PackagePinsModel.cpp
src/PinAssignment/PackagePinsModel.h
src/PinAssignment/PackagePinsView.cpp
src/PinAssignment/PackagePinsView.h
src/PinAssignment/PinAssignmentCreator.cpp
src/PinAssignment/PinAssignmentCreator.h
src/PinAssignment/PinsBaseModel.cpp
src/PinAssignment/PinsBaseModel.h
src/PinAssignment/PortsLoader.cpp
src/PinAssignment/PortsLoader.h
src/PinAssignment/PortsModel.cpp
src/PinAssignment/PortsModel.h
src/PinAssignment/PortsView.cpp
src/PinAssignment/PortsView.h
src/PinAssignment/SaveDialog.cpp
src/PinAssignment/SaveDialog.h
src/PinAssignment/Test/PinAssignmentCommands.cpp
src/PinAssignment/Test/PinAssignment_main.cpp
tests/TestGui/gui_pinassignment.tcl
tests/TestInstall/CMakeLists.txt

Add Pin Assignment View stab files

Add pin assignment view stab files

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/Main/main.cpp
src/NewProject/CMakeLists.txt
src/NewProject/ProjectManager/compiler_configuration.cpp
src/NewProject/ProjectManager/compiler_configuration.h
src/NewProject/ProjectManager/project.cpp
src/NewProject/ProjectManager/project.h
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
tests/Testcases/aes_decrypt_fpga/aes_decrypt.tcl
tests/Testcases/bgm/bgm.tcl
tests/Testcases/oneff/oneff.tcl
tests/Testcases/trivial/test.tcl

Force users to setup target device or architecture files.
Remove default architecture files.
All scripts should manually defines target device or architecture files.

Remove default architecture files and force user to manually setup target device

---

CMakeLists.txt
src/NewProject/add_constraints_form.cpp
src/NewProject/add_constraints_form.h
src/NewProject/add_constraints_form.ui
src/NewProject/new_project_dialog.cpp
src/ProjNavigator/add_file_dialog.cpp
src/ProjNavigator/add_file_form.cpp
src/ProjNavigator/add_file_form.h
src/ProjNavigator/add_file_form.ui

> - [x] To address an existing issue. RG-17
>- Added pin assignment option in Add_Constraint_form dialog from New Project Window.
>- Added pin assignment option in Add Source dialog from Source tab on GUI. 
>- Selecting Pin Assignment settings from Add_Constraint_form/Add Source dialog will be saved and pass to placement settings after completing new project flow. 
>  This PR improves in the following aspects:  
>- Pin Assignment Method Selection from different dialogs.
> 
> 
> ### Testing Steps:
>- create_design project_1
>- …

Pin Assign Opt in the Add Constraint file form

---

src/Compiler/CompilerOpenFPGA.cpp

Format fix

---

src/NewProject/new_project_dialog.cpp

>- New Project Dialog size is set from one third of window size to default size.

Revert new project window size

---

CMakeLists.txt
etc/templates/Pin_Table.csv
src/MainWindow/main_window.cpp
src/PinAssignment/PackagePinsLoader.cpp
src/PinAssignment/PackagePinsLoader.h
src/PinAssignment/PackagePinsModel.cpp
src/PinAssignment/PackagePinsModel.h
src/PinAssignment/PackagePinsView.cpp
src/PinAssignment/PackagePinsView.h
src/PinAssignment/PinAssignmentCreator.cpp
src/PinAssignment/PinAssignmentCreator.h
src/PinAssignment/Test/PinAssignment_main.cpp

Add loading target device package pin table
Search csv file and show it in the Package Pin table.

Load data for package pin table

---

src/NewProject/source_grid.cpp

> - [x] To address an existing issue  [<Issue ID 558>](https://github.com/os-fpga/FOEDAG/issues/558)
>- "Add Directory..." adds all the source files in "*.ys" file when synthesis runs.
>- Synthesis build successfully when add source files from the "Add Directory..." button.
> Please provide a list of limitations if not specified in any issue
>-  It depends on the openfpga compiler, so it needs to be tested with openfpga compiler in foedag to get "*.ys" file when start the sysntesis.
>Test Steps:
>Run foedag with openfpga compiler by using command: 
>- ./build/bin/foedag --compiler openfpga.
>- Create new project and add source files from "Add …

"Add Directory..." button fixed for "*.ys" file and synthesis test.

---

.github/workflows/main.yml
Makefile
tests/unittest/unittest_main.cpp

Allow create unit tests for different kind of widgets.

Add QApplication for unittests

---

src/Compiler/CompilerOpenFPGA.cpp

Current commit makes sure -L libraries, used in add_design_files command, are also passed to -import.
Example input:
add_design_file -work lib1 -V_2001 ./rtl/timescale.v
add_design_file -work lib2 -V_2001 ./rtl/sasc_brg.v
add_design_file -L lib1 -L lib2 -V_2001 ./rtl/sasc_fifo4.v ./rtl/sasc.v
Output:
verific -work lib1  -vlog2k /home/work/Work/Raptor/tests/Testcases/sasc_testcase/./rtl/timescale.v
verific -work lib2  -vlog2k /home/work/Work/Raptor/tests/Testcases/sasc_testcase/./rtl/sasc_brg.v
verific -L lib1 -L lib2  -vlog2k /home/work/Work/Raptor/tests/Testcases/sasc_testcase/./rtl/sasc_fifo4.v /home/work/Work/Raptor/tests/Testcases/sasc_testcase/./rtl/sasc.v
verific -L lib1 -L lib2 -import sasc

pass relevant libraries to -import command

---

src/Main/ProjectFile/ProjectFileLoader.cpp

> - [x] To address an existing issue: <[#557](https://github.com/os-fpga/FOEDAG/issues/557#issue-1325805860)>
Project path was saved to project file(.ospr) when create a new project. If project folder is moved to another location that leads to invalid path and gui refuse to run the process, because there is incorrect path to the files.
> - Removed the path from the project file (.ospr).
>- Project Path points to actual path wherever it is moved. 
> #### Testing steps
>-  Create new project.
>- Verify .ospr file created in the project folder. 
>- Verify source files and constraint files are also added in (<project_Name>.srcs) folder inside the project …

Fixed project path issue when project folder is moved and load (#557)

---

src/IPGenerate/IPCatalog.h
src/IpConfigurator/IpConfigDlg.cpp

> - [x] To address an existing issue. If so, please provide a link to the issue: GEMINIEDA-333
> This addresses the action items captured in GEMINIEDA-333's comments
>
> 
> - [x] Library: IpConfigurator
> - [ ] Engine
> - Minor visual changes and the Generate IP button now also fires the printed test tcl
> ### Testing
> - These are minor visual changes from feedback, not testing can be done with our current harness …

GEMINIEDA-333: Address Ip Configurator Dlg Feedback

---

src/PinAssignment/PackagePinsLoader.cpp
src/PinAssignment/PinAssignmentCreator.cpp
src/PinAssignment/PinAssignmentCreator.h
src/PinAssignment/PinsBaseModel.cpp
src/PinAssignment/PortsLoader.cpp
src/PinAssignment/PortsLoader.h
tests/unittest/CMakeLists.txt
tests/unittest/PinAssignment/BufferedComboBox_test.cpp
tests/unittest/PinAssignment/PackagePinsLoader_test.cpp
tests/unittest/PinAssignment/PinAssignmentCreator_test.cpp
tests/unittest/PinAssignment/Pin_Table.csv
tests/unittest/PinAssignment/PinsBaseModel_test.cpp
tests/unittest/PinAssignment/PortsLoader_test.cpp
tests/unittest/PinAssignment/ports_test.json
tests/unittest/resources.qrc

Add unit tests for the pin assignment feature. Also some code improvement and code clean up provided as well.

Add unit tests for the pin assignment module

---

src/MainWindow/main_window.cpp

Make task table visible by default.

Move task table below the hiararchy table

---

src/NewProject/source_grid.cpp

The motivation of this PR is GEMINIEDA-351 issue.
New project creation wizard has a handy "Add Directories" feature, but it only looks for the files inside that doesn't go into sub directories. This PR removes that limitation. 
Instead of QDir::entryList, which only checks directory content, I used QDirIterator with QDirIterator::Subdirectories flag.
It recursively visits entire directory hierarchy starting from selected one.
Now the user may select high level folder and the code will make sure all the files, satisfying given filter, from all the sub directories are added to the project under creation.

[GEMINIEDA-351] Look for source files in sub directories

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp

Remove some of the limitations with bitstream force

Enable bitstream

---

CMakeLists.txt
etc/package_pin_info.json
src/PinAssignment/PackagePinsLoader.cpp
src/PinAssignment/PackagePinsLoader.h
src/PinAssignment/PackagePinsModel.cpp
src/PinAssignment/PackagePinsModel.h
src/PinAssignment/PackagePinsView.cpp
src/PinAssignment/PinAssignmentCreator.cpp
src/PinAssignment/PinAssignmentCreator.h
tests/unittest/PinAssignment/PackagePinsLoader_test.cpp
tests/unittest/PinAssignment/package_pin_info.json
tests/unittest/resources.qrc

Add columns explanation to the Package pin table in Pin Assignment feature.
Make loading all data from the json file in order to be more flexible.

Add header tool tips to the Package pin table in Pin assignment

---

src/MainWindow/WelcomePageWidget.cpp
src/MainWindow/WelcomePageWidget.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

Implement recent projects feature
Settings file is created or opened when app start. All recent projects are saved to setting file. 10 projects maximum 
and 5 projects on welcome page

[RG-56] Implement recent projects action

---

src/Main/AboutWidget.cpp

> - [ ] **Modification in adding hyperlink script.**
Condition is added if the hyperlink is avaialble then It will show the hyperlink.
> 
> - [ ] Engine

Hyperlink changes for about Dialog

---

src/NewProject/source_grid.cpp

Fixed Add directory functionality when add new files.

Fixed Add directory issue

---

src/Main/ProjectFile/ProjectFileLoader.cpp
src/Main/ProjectFile/ProjectFileLoader.h
src/Main/ProjectFile/ProjectManagerComponent.cpp

Project file loading has a critical issue related to incorrect loading.
Set target device causes rewrite project file before it is actually loading. Move this to correct place.

[RG-66] Fixed loading project file

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerDefines.cpp
src/Compiler/CompilerDefines.h
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/TaskManager.cpp
src/Compiler/TaskModel.cpp

Add Bitstream clean task into the Task table.

[RG-95] Add bitstream clean command into the task table

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp

Fixed incremental build for analyze. Fixed analyze clean step.

[RG-96] Fixed analyze step

---

src/NewProject/source_grid.cpp

> - [x] Remove unsupported design sources file format.
Unsupported design source file formats are removed from the GUI  add source dialog.
>
> 
> - [x] Library: <Specify the library name>
> - [ ] Engine
> - [x] Break back-compatibility. If so, please list who may be influenced.

[RG-98]-Unsupported Design Source file formats are removed

---

src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/create_file_dialog.cpp
src/NewProject/source_grid.cpp
src/NewProject/source_grid.h
src/ProjNavigator/add_file_dialog.cpp
tests/unittest/CMakeLists.txt
tests/unittest/NewProject/source_grid_test.cpp

Add language selection when user creates project. Blocked by https://github.com/os-fpga/FOEDAG/pull/685
yosis script:

[RG-94] Add language selection for project wizard

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h
src/Main/CMakeLists.txt
src/Main/TclSimpleParser.cpp
src/Main/TclSimpleParser.h
src/MainWindow/Session.cpp
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

Show progress bar in script mode

[RG-97] Add progress bar in script mode

---

src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/NewProject/CMakeLists.txt
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/NewProject/SettingsGuiInterface.h
src/NewProject/add_constraints_form.cpp
src/NewProject/add_constraints_form.h
src/NewProject/add_source_form.cpp
src/NewProject/add_source_form.h
src/NewProject/device_planner_form.cpp
src/NewProject/device_planner_form.h
src/NewProject/new_project_dialog.cpp
src/NewProject/new_project_dialog.h
src/NewProject/source_grid.cpp
src/NewProject/source_grid.h
src/ProjNavigator/sources_form.cpp
src/ProjNavigator/sources_form.h
tests/unittest/NewProject/source_grid_test.cpp

Allow user modify project settings
When project created user can modify project settings:
* via context menu in the project hierarchy
* via menu Project->Project setting
* run any script from testcase folder.
* copy somewhere project file
* Open and close project settings
* Compare latest project file with the one that was copied.
* Create project with all available options
* Open project settings.
* It is expected that project settings are the same as it was created.
* create project with some settings
* Open project settings and close several times.
* Nothing should be changed
* create project with some settings
* Open project settings
* Change something
* Close settings and open again
* All changes should be saved.
* Repeat steps with all possible settings

[RG-93] Project settings

---

src/NewProject/source_grid.cpp

Fix for issue with Move Up/Down buttons for constraint files form

[RG-128] Fixed Move Up/Down buttons for constraint form

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/Main/ProjectFile/ProjectManagerComponent.cpp
src/NewProject/ProjectManager/project_fileset.cpp
src/NewProject/ProjectManager/project_fileset.h
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/NewProject/add_source_form.cpp
src/ProjNavigator/add_file_dialog.cpp
src/ProjNavigator/sources_form.cpp
src/ProjNavigator/tcl_command_integration.cpp

Add full support for compile unit
This actions were done:
* save unit name to file
* Project setting support
* Hide Add Sources...
* Add default unit name for tcl command

[RG-119] Fixed all issues related to compile unit

---

src/IpConfigurator/IpConfigWidget.cpp

> - [x] Addressing in-person ui change requests
> 
> 
> 
> 
> 
>
- Stretch has been moved from above gerenate button to below so it always stays flush with the groupbox above
- Content margins of generate button have been updated to provide some space
> 
> - [x] Library: IpConfigurator
> - [ ] Engine
> - [ ] Continous Integration (CI) …

IpConfigWidget Visual Tweaks

---

src/NewProject/ProjectManager/project_manager.cpp
src/Utils/CMakeLists.txt
src/Utils/sequential_map.h
tests/unittest/CMakeLists.txt
tests/unittest/Utils/sequential_map_test.cpp

Fixed design files compilation order.
**Expected:**
**Actual:**

Fixed compile order for design files

---

src/NewProject/add_source_form.cpp
src/NewProject/add_source_form.h
src/NewProject/add_source_form.ui
src/NewProject/new_project_dialog.cpp

Add directory browsing for include and library path

[GEMINIEDA-473] Add directory browsing for include and library path

---

etc/settings/settings_test.json
src/Compiler/CompilerOpenFPGA.cpp
src/NewProject/add_constraints_form.cpp
src/NewProject/add_constraints_form.h
src/NewProject/add_constraints_form.ui
src/NewProject/new_project_dialog.cpp
src/ProjNavigator/add_file_dialog.cpp
src/ProjNavigator/add_file_form.cpp
src/ProjNavigator/add_file_form.h
src/ProjNavigator/add_file_form.ui

[GEMINIEDA-455] Add "Free" option for placement

---

src/NewProject/device_planner_form.cpp

Fix for wrong data when device is selected by default.

[GEMINIEDA-507] Fixed device selection

---

src/Compiler/CompilerOpenFPGA.cpp

> - [x] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-483]
> top module info isn't printed, but the info can be found in <project_dir>/port_info.json after an analyze step
>
> The analyze step has been updated to read the "topModule" property from port_info.json and print it at the end of the task
> The message will print after a new run: 
> and when the design has already been analyzed:
> 
> - [x] Library: Compiler
> - [ ] Plug-in: …

[GEMINIEDA-483] Adding logic to print topModule after analyze

---

src/MainWindow/main_window.cpp

Save action related to Pin Planner and managed by pin planner. Remove from default GUI.

Remove save action from default GUI

---

src/MainWindow/main_window.cpp

> - [x] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-501]
> The program opens the actual example version of the project which has two issues:
> - Any edits the user makes will be made to the formerly original example
> - If the user invokes from an install copy of foedag/raptor then the example dir is read from /usr/local which the program most likely won't have write access to which can cause errors.
>
> This adds logic to copy the requested example project to the user's home directory. …

[GEMINIEDA-501] Add logic to copy example projs to user home dir

---

.github/workflows/install_centos_dependencies_build.sh
.github/workflows/install_ubuntu_dependencies_build.sh
.github/workflows/main.yml
CMakeLists.txt
DEPENDENCIES.md
docs/source/tutorials/getting_started/dependencies.rst

> - [x] Swig install was intermittently failing in CI actions and we currently don't use swig so it was decided to remove swig
> 
> 
> 
> 
> 
> - Updates CI to remove all swig mentions
> - Updates dependency files to remove swig line
> - Comments out a line in the CMake where swig was originally checked for but seemingly not used for a python build. Line left commented as a reminder that swig is currently removed and will need to be re-added if that section needs it.
> 
> - [ ] Library: …

Remove Swig

---

.github/workflows/main.yml

> - [x] update GitHub CI actions
> - Copies action updates made in raptor PR#368
> - Updates centos github version to avoid an error with the checkout action and submodules
> 
> - [ ] Engine
> - [x] Continous Integration (CI) scripts

Updating GitHub CI actions

---

etc/package_pin_info.json
src/MainWindow/main_window.cpp
src/PinAssignment/PackagePinsLoader.cpp
src/PinAssignment/PackagePinsLoader.h
src/PinAssignment/PackagePinsModel.cpp
src/PinAssignment/PackagePinsModel.h
src/PinAssignment/PackagePinsView.cpp
src/PinAssignment/PackagePinsView.h
src/PinAssignment/PinAssignmentBaseView.cpp
src/PinAssignment/PinAssignmentBaseView.h
src/PinAssignment/PinAssignmentCreator.cpp
src/PinAssignment/PortsModel.cpp
src/PinAssignment/PortsModel.h
src/PinAssignment/PortsView.cpp
src/PinAssignment/PortsView.h
tests/unittest/PinAssignment/PackagePinsLoader_test.cpp
tests/unittest/PinAssignment/PinAssignmentCreator_test.cpp
tests/unittest/PinAssignment/package_pin_info.json

Add mode column for Package pin table in pin planner

[RG-139] Pin planner update, add Mode column

---

src/MainWindow/main_window.cpp
src/PinAssignment/PackagePinsLoader.cpp
src/PinAssignment/PackagePinsLoader.h
src/PinAssignment/PinAssignmentCreator.cpp
src/PinAssignment/PinAssignmentCreator.h
src/PinAssignment/PortsView.cpp
src/PinAssignment/PortsView.h

Allow setup custom package pin table loaders.

[RG-140] Custom device loader

---

src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h

[RG-142] Fixed reset compile steps

---

src/PinAssignment/PackagePinsModel.cpp
src/PinAssignment/PackagePinsModel.h
src/PinAssignment/PackagePinsView.cpp
src/PinAssignment/PackagePinsView.h
src/PinAssignment/PinsBaseModel.cpp
src/PinAssignment/PinsBaseModel.h
src/PinAssignment/PortsModel.cpp
src/PinAssignment/PortsView.cpp
src/PinAssignment/PortsView.h

Add mode column to IO Ports table. Sync with package pin table.

[RG-147] Add mode column into IO ports table.

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

Add correct message when compilation interrupted by user. Remove exclamation marks from compiler messages.
Add question message for canceling compilation.

[RG-153] Add question message on stop compilation. Fixed text when compilation failed

---

src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

Add Simulation menu with different simulations.

[RG-201] Add simulation menu

---

src/Compiler/CompilerDefines.cpp
src/Compiler/CompilerDefines.h
src/Compiler/Task.cpp
src/Compiler/Task.h
src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h
src/Compiler/TaskModel.cpp
src/Compiler/TaskTableView.cpp
src/Main/ProjectFile/ProjectManagerComponent.cpp
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/NewProject/ProjectManager/project_configuration.cpp
src/NewProject/ProjectManager/project_configuration.h
src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/NewProject/add_source_form.cpp
src/NewProject/add_source_form.h
src/NewProject/new_project_dialog.cpp
src/NewProject/project_type_form.cpp
src/NewProject/project_type_form.h
src/NewProject/project_type_form.ui
src/NewProject/source_grid.cpp
src/NewProject/source_grid.h
src/ProjNavigator/tcl_command_integration.cpp
tests/unittest/Compiler/CompilerDefines_test.cpp

Add post synthesis project type

[RG-185] Add support for post synthesis project

---

src/Compiler/Task.cpp
src/Compiler/Task.h
src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h
src/Main/ProjectFile/ProjectFileLoader.cpp

Fixed issue when progress bar shows only after first task done. In case first task is long, it looks like no progress bar.

[RG-190] Fixed progress bar behavior for long-running first task

---

src/Compiler/CMakeLists.txt
src/Compiler/CompilerDefines.h
src/Compiler/TaskGlobal.h
src/Compiler/TaskModel.cpp
src/Compiler/TaskTableView.cpp
src/Compiler/TaskTableView.h

Add Expand All/Collapse All context menu actions for Task table.

Add expand/collapse all actions into Task table

---

src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/NewProject/source_grid.cpp
tests/unittest/NewProject/ProjectManager_test.cpp

Add library and compile unit for simulation files.
This changes related to new project wizard and project setting.

[RG-223] Add library and compile unit for simulation files

---

src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h
src/Main/CMakeLists.txt
src/Main/DialogProvider.cpp
src/Main/DialogProvider.h
src/MainWindow/main_window.cpp

Show message box when user want to clean any task:
class `DialogProvider` is a service class that provide interface for user interaction.

[RG-291] Add message dialog for cleaning task

---

src/Compiler/TaskTableView.cpp

Align status icon to the center:

[RG-231] Status icon align to center

---

src/NewProject/ProjectManager/config.cpp

device.xml file can describe with an optional label the device stats.

Device stats label

---

src/Compiler/CompilerOpenFPGA.cpp

Some bitstream conf files are optional. Support "" empty string in device.xml and bitstream_config_files command

Optional bitstream configuration file

---

etc/settings/settings_test.json
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/CompilerOpenFPGA.h
src/MainWindow/main_window.cpp
src/Utils/StringUtils.cpp
src/Utils/StringUtils.h
tests/unittest/Utils/StringUtils_test.cpp

2 new synthesis settings were added for DSP and BRAM:
Previous settings removed.

[RG-360] Change synthesis settings for bram and dsp

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/WorkerThread.cpp
src/Compiler/WorkerThread.h
src/IPGenerate/IPGenerator.cpp
src/IPGenerate/IPGenerator.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/ProjNavigator/sources_form.cpp
src/ProjNavigator/sources_form.h
src/Utils/FileUtils.cpp
src/Utils/FileUtils.h

New feature allows user to simulate generated IP:
Show message in case IP doesn't support simulation:
New tcl command available:
`simulate_ip  <module name>`

[EDA-1253] Ip simulation

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp

Clarify help for -c argument for chatgpt command:

Update help for chatgpt command

---

src/Compiler/CMakeLists.txt
src/Compiler/Reports/AbstractReportManager.cpp
src/Compiler/Reports/BitstreamReportManager.cpp
src/Compiler/Reports/BitstreamReportManager.h
src/Compiler/Reports/ITaskReportManager.h
src/Compiler/TaskManager.cpp
src/Compiler/TaskModel.cpp
src/MainWindow/ReportsTreeWidget.cpp

Rename third column of task table.
Update with Fmax data.

[EDA-1108] fmax column

---

src/Compiler/Compiler.cpp

Fixed timeout for chatgpt from 3 sec to 3 min

change timeout from 3 sec to 3 min

---

src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/Reports/AbstractReportManager.cpp
src/Compiler/Reports/AbstractReportManager.h
src/Compiler/Reports/BitstreamReportManager.cpp
src/Compiler/Reports/ITaskReportManager.h
src/Compiler/Reports/PackingReportManager.cpp
src/Compiler/Reports/PlacementReportManager.cpp
src/Compiler/Reports/RoutingReportManager.cpp
src/Compiler/Reports/SynthesisReportManager.cpp
src/Compiler/Reports/TimingAnalysisReportManager.cpp
src/Compiler/TaskModel.cpp

* Add I/O table
* Add clock table
* Update indents for logic table  
* Update calculation for DFF and DSP
* Remove GND/VCC

[RG-375] Reports update after feedback

---

src/Simulation/Simulator.cpp

Icarus support

---

etc/settings/settings_test.json
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/Main/Tasks.cpp

Update clb_packing argumets:
```
clb_packing   <directive>  : Performance optimization flags (auto, dense)
auto                   : CLB packing automatically determined (default)
dense                  : Pack logic more densely into CLBs resulting in fewer utilized CLBs however may negatively impact timing
timing_driven          : Pack logic to optimize timing
```
Change default to Auto.

[RG-392] Update clb_packing

---

src/IpConfigurator/IpConfigWidget.cpp
src/Main/WidgetFactory.cpp
src/Main/WidgetFactory.h

[EDA-1553] Fixed recovering of IP dynamic parameters

---

src/Console/TclConsoleWidget.cpp

Fixed issue with console after open project:

[RG-414] Fixed console empty line

---

src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Correct Adder Carry count

---

src/Main/CMakeLists.txt
src/Main/registerTclCommands.cpp
src/MainWindow/CompressProject.cpp
src/MainWindow/CompressProject.h
src/MainWindow/Dialog.cpp
src/MainWindow/Dialog.h
src/MainWindow/LicenseManagerWidget.cpp
src/MainWindow/PathEdit.cpp
src/MainWindow/PathEdit.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

New action allow for user:
New window:
allows user save whole project into a single file by one shot.

[RG-413] Add Compress project... action which allow user to create archive file of the project

---

src/IPGenerate/IPGenerator.cpp

Run IP loading in separate thread to avoid GUI stuck when project loading.

[RG-374] Run add_litex_ip_catalog in seperate thread

---

src/Compiler/Reports/AbstractReportManager.cpp
src/Compiler/Reports/AbstractReportManager.h
src/Compiler/Reports/BitstreamReportManager.cpp
src/Compiler/Reports/BitstreamReportManager.h
src/Compiler/Reports/PackingReportManager.cpp
src/Compiler/Reports/PackingReportManager.h
src/Compiler/Reports/PlacementReportManager.cpp
src/Compiler/Reports/PlacementReportManager.h
src/Compiler/Reports/RoutingReportManager.cpp
src/Compiler/Reports/RoutingReportManager.h
src/Compiler/Reports/SynthesisReportManager.cpp
src/Compiler/Reports/SynthesisReportManager.h
src/Compiler/Reports/TimingAnalysisReportManager.cpp
src/Compiler/Reports/TimingAnalysisReportManager.h
src/Main/JsonReportGenerator.cpp

Fixed fmax after clean command. Remove reports files after clean command.

[RG-425] Fixed fmax column after clean command

---

CMakeLists.txt
Makefile
src/Main/ToolContext.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/ProgrammerGui/CMakeLists.txt
src/ProgrammerGui/ProgrammerMain.cpp
src/ProgrammerGui/ProgrammerMain.h
src/ProgrammerGui/ProgrammerMain.ui
src/ProgrammerGui/Test/ProgrammerGuiCommands.cpp
src/ProgrammerGui/Test/programmer_gui_main.cpp
src/ProgrammerGui/app/main.cpp
src/ProgrammerGui/res.qrc
src/Utils/FileUtils.cpp
tests/TestGui/programmer_gui.tcl

Initial commit for programmer gui module. 
This gui allow users to burn bitstream into device.

[RG-428] Initital programmer gui

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/CompilerOpenFPGA.h

memory bank bitstream cache support

memory bank bitstream support

---

src/Compiler/Compiler.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

default file type for simualtion files

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
tests/TestGui/log_header.tcl

Fixed issue when command `sta opensta` failed because of the top module autodetect.
For now, if user choose top module autodetect we try to read it from port_info.json file

[EDA-1704] Fixed issue with opensta

---

src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/ProjNavigator/CMakeLists.txt
src/ProjNavigator/FileExplorer.cpp
src/ProjNavigator/FileExplorer.h
src/ProjNavigator/sources_form.ui

Add file explorer. Show all files for project path. If no project, show current path.

[RG-443] Add file explorer widget

---

src/Compiler/Reports/AbstractReportManager.h
src/Compiler/Reports/IDataReport.h
src/Compiler/Reports/TableReport.cpp
src/Compiler/Reports/TableReport.h
src/Compiler/Reports/TimingAnalysisReportManager.cpp
src/Compiler/Reports/TimingAnalysisReportManager.h
src/Main/ReportGenerator.cpp

Add new report for timing analysis:

[EDA-1672] Multi clock report

---

src/Compiler/CompilerOpenFPGA.cpp

Remove empty parts from analysis command file

[EDA-1739] Fixed analyze command file, removed empty arguments

---

src/Compiler/CompilerDefines.cpp
src/Compiler/Reports/AbstractReportManager.cpp
src/Compiler/Reports/AbstractReportManager.h
src/Compiler/Reports/BitstreamReportManager.cpp
src/Compiler/Reports/IDataReport.h
src/Compiler/Reports/ITaskReportManager.h
src/Compiler/Reports/PackingReportManager.cpp
src/Compiler/Reports/PlacementReportManager.cpp
src/Compiler/Reports/RoutingReportManager.cpp
src/Compiler/Reports/SynthesisReportManager.cpp
src/Compiler/Reports/TimingAnalysisReportManager.cpp
src/Compiler/Reports/TimingAnalysisReportManager.h
src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h
src/Compiler/TaskModel.cpp
src/Compiler/TaskTableView.cpp
src/Compiler/TaskTableView.h
src/MainWindow/main_window.cpp

Show all clocks frequency in the Fmax column of the task table:

[EDA-1672] Fmax column for multiple clocks projects

---

src/Console/FileNameParser.cpp

Fixed file path detect in the console with `_` character.

[RG-458] Fixed file path with '_' that doesn't handled properly

---

src/Compiler/Reports/AbstractReportManager.cpp
src/Compiler/Reports/ITaskReportManager.h
src/Compiler/Reports/TimingAnalysisReportManager.cpp

Update timing report with unconstrained clocks

[EDA-1705] Unconstrained clock in timing report

---

CMakeLists.txt
src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/device_block.h
src/DeviceModeling/device_modeler.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Adding properties specification for a device modeling block

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/Reports/TimingAnalysisReportManager.cpp
src/Compiler/Reports/TimingAnalysisReportManager.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/ProjNavigator/tcl_command_integration.cpp
src/ProjNavigator/tcl_command_integration.h

Hide all timing reports for opensta

[EDA-1881] Hide timing summary for opensta

---

etc/help.txt
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/ProjNavigator/tcl_command_integration.cpp
src/ProjNavigator/tcl_command_integration.h

Add new flag for `create_design`:

add `clean` flag for create_design command. This flag will cleanup project folder

---

.gitignore
CMakeLists.txt
src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/device_block.h
src/DeviceModeling/device_modeler.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Adding Model names to User names mapping EDA-1865

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/CompilerOpenFPGA.h

Add parameter with defaults values for `BaseVprCommand` to allow turn on/off any of the parameters

[EDA-1863] Avoid generate _post_route files for timing analysis

---

CMakeLists.txt
etc/help.txt
src/Compiler/Compiler.cpp
src/Compiler/TaskManager.cpp
src/Compiler/TaskModel.cpp

[EDA-1886] Enable opensta for production

---

CMakeLists.txt
etc/help.txt
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp

Add support for Surelog and GHDL parsers for full open-source version requested by some users.

Surelog support

---

src/DeviceModeling/device_signal.h
tests/unittest/CMakeLists.txt
tests/unittest/DeviceModeling/device_signal_test.cpp

> - [X ] Adding Gtests for device signals

Adding Gtests to device_signal and resolving weak pointer issue

---

src/Compiler/CompilerOpenFPGA.cpp

remove -defer

---

CMakeLists.txt
tests/unittest/CMakeLists.txt
tests/unittest/DeviceModeling/device_test.cpp

Gtests for DM Device

---

CMakeLists.txt
tests/TestGui/log_header.tcl

> - [X] To address an existing issue. If so, please provide a link to the issue: Fix https://github.com/os-fpga/FOEDAG/pull/1241
> Change the parsing text to use new version format 
> Updates the test case log_header.tcl for changes in https://github.com/os-fpga/FOEDAG/pull/1241
> 
> - [ ] Engine
> - [X] Regression tests
> ### …

Fix log_header.tcl testcase to use new version format in logs

---

src/Compiler/CompilerOpenFPGA.cpp

Automatically switch from Default to GHDL or Surelog when needed

auto parser selection

---

.readthedocs.yml
CMakeLists.txt
docs/requirements.txt

> Remove system packages install since it was removed upstream in read the docs build images.
> https://blog.readthedocs.com/drop-support-system-packages/
> Update read the docs changes.
> - [ ] Engine
> - [X] Continuous Integration (CI) scripts
> ### …

Remove deprecated system packages usage for read the docs build

---

CMakeLists.txt
src/Main/AboutWidget.cpp
src/Main/AboutWidget.h
src/MainWindow/main_window.cpp

[RG-471] Sync About widget with --version output

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp
src/Simulation/Simulator.cpp
src/Utils/FileUtils.cpp
src/Utils/FileUtils.h

Yosys default parser does not handle -y <lib>
Create an approximate library cell list.

Yosys -y handling

---

etc/help.txt
src/IPGenerate/IPGenerator.cpp

Update programmer tcl command help text.
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [x] Documentation
> - [ ] Break back-compatibility. …

Update programmer tcl help text

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/CompilerOpenFPGA.h

analyze command based on Yosys default parser

Yosys default parser-based analyze command

---

src/Compiler/CompilerOpenFPGA.cpp

Most testcases do not have proper package definition grouped in compilation units, the -defer option from Surelog does not re-order properly, so compile everything in a single compilation unit.
See https://github.com/chipsalliance/Surelog/issues/3846

single surelog compilation unit for now

---

CMakeLists.txt

Fixed empty GIT_HASH variable in window msvc which cause build error

Fixed empty GIT_HASH variable

---

.github/workflows/main.yml
CMakeLists.txt

Update main.yml to add if always to upload artifact

---

CMakeLists.txt
src/Main/main.cpp
src/ProgrammerGui/CMakeLists.txt
src/ProgrammerGui/app/main.cpp

Add programmer gui as standalone app

---

CMakeLists.txt
src/Main/main.cpp
src/ProgrammerGui/CMakeLists.txt

Change programmer executable to `programmer_gui`

Change programmer executable name

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

Basic mixed language support. No cross language reference support, nor cross language parameter overloading.

mixed lang support

---

src/Configuration/CFGCompiler/CFGCompiler.cpp
src/ProgrammerGui/ProgrammerMain.cpp
src/ProgrammerGui/ProgrammerMain.ui

Add tcl console support in programmer

Add tcl console to programmer

---

src/MainWindow/main_window.cpp
src/ProjNavigator/HierarchyView.cpp
src/ProjNavigator/HierarchyView.h
src/ProjNavigator/sources_form.cpp
src/ProjNavigator/sources_form.h
tests/unittest/CMakeLists.txt
tests/unittest/ProjNavigator/HierarchyView_test.cpp
tests/unittest/ProjNavigator/hier_info.json
tests/unittest/ProjNavigator/hier_info_1.json
tests/unittest/ProjNavigator/hier_info_corrupted.json
tests/unittest/resources.qrc

Bold the top module Design Sources:

[RG-473] Make file name bold if it's top level module.

---

src/ProjNavigator/HierarchyView.cpp

No matter how incomplete the json is, the hier builder should not crash.

safe hierarchy building

---

CMakeLists.txt
src/IpConfigurator/IpCatalogTree.cpp

Sort ip catalog list alphabetically:

[EDA-1350] Sort ip catalog list alphabetically

---

CMakeLists.txt
src/ProgrammerGui/ProgrammerMain.cpp
src/ProgrammerGui/ProgrammerMain.ui

Remove Help menu. Small code improvement.

Remove Help menu

---

CMakeLists.txt
src/ProgrammerGui/CMakeLists.txt
src/ProgrammerGui/ProgrammerGuiCommon.h
src/ProgrammerGui/ProgrammerMain.cpp
src/ProgrammerGui/ProgrammerMain.h
src/ProgrammerGui/ProgrammerSettingsWidget.cpp
src/ProgrammerGui/ProgrammerSettingsWidget.h
src/ProgrammerGui/ProgrammerSettingsWidget.ui

[RG-449] Programmer settings

---

src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Eblif support

---

src/Compiler/CompilerOpenFPGA.cpp

Revert "Eblif support"

---

src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Netlist support

---

CMakeLists.txt
src/ProgrammerGui/ProgrammerMain.cpp
src/ProgrammerGui/ProgrammerMain.h
src/ProgrammerGui/SummaryProgressBar.cpp
src/ProgrammerGui/SummaryProgressBar.h
tests/unittest/ProgrammerGui/SummaryProgressBar_test.cpp

Allow user select devices they want program:
* Only checked devices will be programmed. 
* Main progress should reflect only selected devices.
* Reset action from context menu should enable device.

[RG-479] Programmer: add checkboxes to tree table.

---

CMakeLists.txt
src/Configuration/CFGCommon/CFGCommon.cpp
src/Configuration/Programmer/Programmer.cpp
src/ProgrammerGui/ProgrammerMain.cpp

Fixed issue with progress and status. 
Make sure progress callback send just a number without any additional info. 
Fixed the way how GUI set the process status.

Fix progress issue and status

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Force eblif

---

etc/help.txt
src/Configuration/CFGCommon/CFGArg.json
src/Configuration/Programmer/Programmer.cpp
src/Configuration/Programmer/ProgrammerGuiInterface.h
src/ProgrammerGui/ProgrammerGuiCommon.h
src/ProgrammerGui/ProgrammerGuiIntegration.cpp
src/ProgrammerGui/ProgrammerGuiIntegration.h
src/ProgrammerGui/ProgrammerMain.cpp
src/ProgrammerGui/ProgrammerMain.h
src/ProgrammerGui/ProgrammerMain.ui
tests/unittest/CFGCommon/CFGArg_test.cpp

Programmer gui updates:
1. Add OPT programming 
2. Status column: show Fail if process failed. Add text colors 
3. Fix for start button: always run all the selected tasks.
4. Disable table context menu when programming is running
5. Checkboxes:
* Make disable by default
* Enable when user select file.
6. Added tool tips

[RG-480] Programmer updates: Added program otp, other gui updates.

---

CMakeLists.txt
src/ProgrammerGui/ProgrammerMain.cpp

Disable Pause button when user press it:

Disable Pause button when user press it

---

CMakeLists.txt
src/IpConfigurator/IPDialogBox.cpp
src/IpConfigurator/IPDialogBox.h
src/IpConfigurator/IPDialogBox.ui

Add scroll area for the parameters list:

[EDA-2121] Add scroll area for parameters list

---

src/Configuration/Programmer/Programmer.cpp
src/Configuration/Programmer/ProgrammerGuiInterface.h
src/ProgrammerGui/ProgrammerGuiIntegration.cpp
src/ProgrammerGui/ProgrammerGuiIntegration.h
src/ProgrammerGui/ProgrammerMain.cpp
src/ProgrammerGui/ProgrammerMain.ui

Implement Stop functionality. 
Change Pause button to Stop.

Allow user to stop programming process

---

etc/help.txt

Add help materials for the design query.

[EDA-1932] Add help for design query

---

CMakeLists.txt
src/Main/ProjectFile/ProjectFileLoader.cpp

Fixed foedag verison in project file

Fixed foedag version in project file

---

src/ProjNavigator/sources_form.cpp
src/ProjNavigator/tcl_command_integration.cpp
src/ProjNavigator/tcl_command_integration.h
src/Simulation/Simulator.cpp

Highlight simulation top module detected by filename
Trigger update source tree when `set_top_testbench` command executed.

[RG-474] Highlight simulation top module detected by filename

---

CMakeLists.txt
src/ProgrammerGui/ProgrammerGuiCommon.h
src/ProgrammerGui/ProgrammerMain.cpp
src/ProgrammerGui/ProgrammerMain.h

Update programmer title and few messages:

[RG-483] Change programmer name, change message.

---

CMakeLists.txt
src/NewProject/ProjectManager/compiler_configuration.cpp
src/NewProject/ProjectManager/ip_configuration.cpp

Fixed properties duplication like this:
Duplication happens if use `CompilerConfiguration::add...` methods

[RG-482] Fixed duplication in compiler and ip configuration properties

---

CMakeLists.txt
src/Compiler/Compiler.cpp
src/MainWindow/main_window.cpp

> - [x] To address an existing issue. If so, please provide a link to the issue: RG-464
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

[RG-464] Fixed run_project and open_project tcl apis

---

CMakeLists.txt
src/NewProject/source_grid.cpp

Allow user select design file with any extension:

[EDA-932] Allow user select design file with any extension

---

src/Compiler/TaskManager.cpp

Fix after https://github.com/os-fpga/FOEDAG/pull/1354

[EDA-2168] Fixed text with &&

---

CMakeLists.txt
src/MainWindow/main_window.cpp

Add Stop action into Run menu

---

CMakeLists.txt
src/IpConfigurator/IPDialogBox.cpp

Fixed IP reconfiguration, when same IP appears in the project but with different names:

[RG-491] Fixed IP reconfiguration

---

CMakeLists.txt
src/Compiler/TaskModel.cpp

Update task view for Fmax (reagarding EDA-2137):
1. Added `---` for empty Fmax
2. Text centered.

Update Fmax column

---

src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp

Fixed wrong netlist file name when try to reuse compilation step.

[RG-490] Fixed netlist filename for compilation

---

CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/Main/Tasks.cpp
src/Main/WidgetFactory.cpp

Fixed reset settings after user execute clean:
* Simulate waveform file
* Synthesis optimization

[RG-489] Fixed settings reset after clean

---

CMakeLists.txt
src/Main/ProjectFile/FileLoaderOldStructure.cpp

Remove unicode character

---

.github/workflows/install_centos_dependencies_build.sh
.github/workflows/main.yml
CMakeLists.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fix centos qt6

---

CMakeLists.txt
Makefile
src/Compiler/Task.cpp
src/Console/OutputFormatter.h
src/IpConfigurator/IpCatalogTree.cpp
src/Main/Foedag.cpp
src/Main/FoedagStyle.h
src/Main/qttclnotifier.cpp
src/MainWindow/MessagesTabWidget.cpp
src/PinAssignment/PackagePinsModel.cpp
src/PinAssignment/PinAssignmentCreator.cpp
src/PinAssignment/PortsModel.cpp
src/ProgrammerGui/ProgrammerMain.cpp
src/ProgrammerGui/SummaryProgressBar.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fixed build issues Qt6 on WIN

---

.github/workflows/main.yml
Makefile
src/Main/qttclnotifier.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Replace hasPendingEvents()

---

CMakeLists.txt
src/NewProject/add_source_form.ui

Fixed tab order for project settings

---

CMakeLists.txt
src/Main/ProjectFile/ProjectFileLoader.cpp

Fixed path for migration message that shows path to backup file.

Fixed path for migration message

---

CMakeLists.txt
src/Compiler/Reports/AbstractReportManager.cpp

Fixed typo for DSP table calculation.

Fixed typo when dsp report calculation

---

CMakeLists.txt
src/Compiler/Reports/AbstractReportManager.cpp

Hide `BRAM packing percentage` from design statistic report since it is not well defined.

Hide `BRAM packing percentage` from report since it is not well defined

---

CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/Main/Tasks.cpp
src/NewProject/add_constraints_form.cpp
src/NewProject/new_project_dialog.cpp
src/ProjNavigator/add_file_dialog.cpp
src/ProjNavigator/add_file_form.cpp

Address review comment from https://github.com/os-fpga/FOEDAG/pull/1378

Update enum PinAssignOpt values according to it's text representation

---

CMakeLists.txt
src/Compiler/Reports/AbstractReportManager.cpp

Fixed Adder Carry number for synthesis in stats report.

[EDA-2253] Fixed stats report for synth

---

CMakeLists.txt
etc/help.txt

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

[EDA-2257] Fixed typo for ip configuration command

---

CMakeLists.txt
src/ProgrammerGui/ProgrammerMain.ui

Change name from Log to Console fir the Programmer GUI

Change name from Log to Console

---

.gitignore
CMakeLists.txt
third_party/gtkwave_cmake/CMakeLists.txt

Revert "Put tk library side to tcl"

---

src/IpConfigurator/IPDialogBox.cpp
src/IpConfigurator/IPDialogBox.h
src/IpConfigurator/IpConfigWidget.cpp
src/IpConfigurator/IpConfigWidget.h
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

Remove copy/paste code from `IpConfigWidget`

[RG-487] Remove copy/paste code from IpConfigWidget

---

.gitignore
CMakeLists.txt
third_party/gtkwave_cmake/CMakeLists.txt

This reverts commit e4d7b898eec7cce6e4ab7e4cf358e7e74d383c4f.

Revert "Revert "Put tk library side to tcl" (#1385)"

---

CMakeLists.txt
src/Compiler/Reports/RoutingReportManager.cpp
src/Utils/sequential_map.h

cherry pick changes from qt6_review branch (old declibed PR https://github.com/os-fpga/FOEDAG/pull/1371)
This PR is a result of qt6 branch review.

Qt6 review2

---

.github/workflows/main.yml
src/NewProject/ProjectManager/project_manager.cpp
src/Utils/sequential_map.h
tests/unittest/Utils/sequential_map_test.cpp

Add new utils class `sequential_multi_map`. This class implement key-value pairs which might be duplicated.

Sequential multi map

---

CMakeLists.txt
src/Main/ProjectFile/ProjectFileLoader.cpp
src/NewProject/ProjectManager/project.cpp
src/NewProject/ProjectManager/project.h

Fixed sig fault related to uninitialized project configs

Fixed segmentation fault in batch mode

---

src/MainWindow/main_window.cpp

Open Programmer GUI for production. 
Add action into Run menu:

[RG-2300] [RG-493] Open Programmer GUI for production build, add to Run menu

---

CMakeLists.txt
src/Compiler/Task.cpp
src/Compiler/Task.h
src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h

fixed macos memory violation

---

CMakeLists.txt
src/DeviceModeling/device_modeler.h

> -  Fix the parent block pointer of an instance in RIC

Fix the Parent Block pointer

---

CMakeLists.txt
src/DeviceModeling/device_instance.h
src/DeviceModeling/device_modeler.h
src/DeviceModeling/rs_parameter.h
tests/unittest/CMakeLists.txt
tests/unittest/DeviceModeling/device_modeler_test.cpp

This PR is to fix various issues + prepare API for bitstream generation (maybe more to come in the future)
1. src/DeviceModeling/device_instance.h 
- Prepare for future use
2. src/DeviceModeling/device_modeler.h
- make sure the defined "width" is parsed and set it in the newly introduced "size_" member variable
- return false in define_param() function if there is unsupported type
- use add_instance() to add instance to the block, instead of just overwrite the mapping. If there is any duplicated …

Fix Various Issue in Device Modeling

---

.github/workflows/labeler.yml
CMakeLists.txt

Fixed CI failure related to labeler: https://github.com/os-fpga/FOEDAG/actions/runs/7152790775

Change labeler version to v5.0.0 because of the bug in main

---

.github/labeler.yml
CMakeLists.txt

Fixing the label syntax issue. Giving label as per version 5

Update labeler.yml to use v5.0.0 syntax

---

CMakeLists.txt
src/Console/CMakeLists.txt
src/IpConfigurator/CMakeLists.txt
src/PinAssignment/CMakeLists.txt
tests/tclutils/CMakeLists.txt

Fixed cmake 3.28.0 issues

---

CMakeLists.txt
src/DeviceModeling/rs_parameter.h
tests/unittest/DeviceModeling/rs_parameter_test.cpp

Use the right access operator. But shouldn't the compilation fail in the first place?!?
> 
> - [x] Engine
> - [ ] Break back-compatibility. If so, please list who may be …

Use correct/consistent access operator

---

etc/help.txt
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/DesignRuns/device_planner_dialog.cpp
src/NewProject/device_planner_form.cpp
src/NewProject/device_planner_form.h
src/NewProject/device_planner_form.ui
src/NewProject/new_project_dialog.cpp
src/NewProject/new_project_dialog.h

Define new tcl command `device_file` which allow user to replace default device.xml file.

[EDA-2225] Add device_file tcl command which can replace default device.xml

---

CMakeLists.txt
third_party/openssl_cmake/openssl_test.cpp

1. Original test just make sure built library is good for calling/linking right after building openssl, since openssl will be used by other subsystem as library. 
2. This change enhance the tets by having stricker checking by comparing golden result
> 
> - [ ] Engine
> - [ ] Continous Integration …

Update openssl test

---

CMakeLists.txt
src/ProjNavigator/tcl_command_integration.cpp

Fixed `set_top_testbench` command that failed in some certain cases.

[RG-499] Fixed set_top_testbench command

---

CMakeLists.txt
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h

Fixed missing progress bar when run script:

[RG-498] Fixed missing progress in a script mode

---

CMakeLists.txt
src/Configuration/CFGCommon/CFGArg.cpp
src/Configuration/CFGCommon/CFGArg.h
src/Configuration/CFGCompiler/CFGCompiler.cpp
src/Configuration/CFGCompiler/CFGCompiler.h
src/Configuration/CMakeLists.txt
src/Configuration/ModelConfig/ModelConfig.cpp
tests/unittest/CFGCommon/CFGArg_test.cpp
tests/unittest/CFGCommon/CFGCommon_test.cpp
tests/unittest/CFGCompiler/CFGCompiler_test.cpp
tests/unittest/CFGProgrammer/CFGProgrammer_test.cpp
tests/unittest/ModelConfig/ModelConfig_test.cpp
tests/unittest/ModelConfig/model_config.json

1. Support Model Config upper level API
> 
> - [ ] Engine

Model Config Version 2

---

src/Simulation/Simulator.cpp
src/Simulation/Simulator.h

Dump simulation commands into files for debug purpose. Same as for all other compilation steps.

Dump to *.cmd file simulation command

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

Finalize exe is called after route so passing file using extension
> 
> - [x ] Library: compiler
> - [ ] Engine

Finalize exe input file by extension

---

CMakeLists.txt
tests/unittest/ProjNavigator/HierarchyView_test.cpp

Since QtTest lib already linked, rework one test with QSignalSpy

Rework one test with QSignalSpy

---

src/NewProject/source_grid.cpp
src/NewProject/source_grid.h

Show warning message about file name duplication:
Show this message when user press Add file..., Add directory.. or Create file... buttons.

[EDA-2363] Show warning message when user try to add files to project with same name

---

CMakeLists.txt
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/Configuration/CFGCompiler/CFGCompiler.cpp
src/Main/main.cpp
src/ProgrammerGui/app/main.cpp

1. Restore the code that had been broken by https://github.com/os-fpga/FOEDAG/pull/1347
2. Generate IO bitstream (Reviewer please aware the limitation)
> - This is done right after fabric bitstream generation (they are done in the same function in fact)
> - Limitation: Currently the code hardcode the model (will improve that once we organize ric database)
> - Limitation: Currently the code only generate (if the model exists) empty IO bitstream (all set to default value by RIC). The final code is pending the readiness of IO design file defined …

Prepare IO bitstream generation

---

src/Compiler/CompilerOpenFPGA.cpp

Report only Route Utilization
> 
> - [x ] Library: Compiler OpenFPGA
> - [ ] Engine

Report routing utilization without finalize exe

---

.github/workflows/install_ubuntu_dependencies_build.sh
CMakeLists.txt
Makefile
src/TextEditor/CMakeLists.txt
src/TextEditor/text_editor_form.h
tests/TestInstall/CMakeLists.txt

Fixed ubuntu install and WIN msvc build. 
Define `FOEDAG_WITH_MONACO_EDITOR` before texteditor include.

qwebengine issues

---

.github/workflows/install_centos_dependencies_build.sh
.github/workflows/install_ubuntu_dependencies_build.sh
.github/workflows/main.yml
CMakeLists.txt
Makefile
src/TextEditor/CMakeLists.txt
src/TextEditor/text_editor_form.h
tests/TestInstall/CMakeLists.txt

Install all the CI dependencies for Qt Web Engine

Qtwebengine CI dependencies for monaco

---

.github/workflows/main.yml
CMakeLists.txt
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/rapidgpt/CMakeLists.txt
src/rapidgpt/RapidGpt.cpp
src/rapidgpt/RapidGpt.h
src/rapidgpt/RapidGptContext.cpp
src/rapidgpt/RapidGptContext.h
src/rapidgpt/RapigGptSettingsWindow.cpp
src/rapidgpt/RapigGptSettingsWindow.h
tests/TestInstall/CMakeLists.txt
tests/unittest/CMakeLists.txt
tests/unittest/rapidgpt/rapidgpt_test.cpp

Add initial support for rapidgpt.
Add rapidgt settings into main window:

[RG-495] Add rapidgpt support

---

src/MainWindow/main_window.cpp
src/NewFile/new_file.cpp

Fixed 2 issues:
1. Open file that was created by user with New action
2. Replace file if it already exists.

Show file in editor when user press Create new file.

---

CMakeLists.txt
Makefile
src/rapidgpt/CMakeLists.txt
src/rapidgpt/RapidGpt.cpp
src/rapidgpt/RapidGpt.h
src/rapidgpt/Test/RapidGptCommands.cpp
src/rapidgpt/Test/RapigGPT_main.cpp
tests/TestGui/rapidgpt.tcl

Improve a way how file context is provided for RapidGPT
Cover RapidGPT with tcl testing

RapidGPT performance improve

---

src/Simulation/Simulator.cpp

Bitstream simulation setup needed an update after directory structure change

Bitstream simulation setup update

---

src/MainWindow/main_window.cpp

Add Exit action into menu of Welcome page

Add Exit action for welcome page

---

src/Compiler/CompilerOpenFPGA.cpp
src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/device_modeler.h
tests/unittest/DeviceModeling/device_modeler_test.cpp

> 1. Support command to undefine device (if it exists)
> 2. Before calling RIC TCL to define a model, always explicitly undefine the model first
> 3. Per discussion with George, all devices will use the same RIC model name for peripheral model
>
> 
> 
> 
> 
> 
> 
> - [x] Engine
> …

Support undefined device

---

tests/unittest/ModelConfig/model_config.golden.ppdb.json
tests/unittest/ModelConfig/model_config_netlist.ppdb.json

Update test to be native of design compilation

---

CMakeLists.txt
src/.foedagenv_lin64.sh
src/foedagenv_lin64.sh
src/to_be_foedag_linx

Add startup script to setup foedag environment.

Add foedag startup script

---

src/MainWindow/main_window.cpp

Add clean console in case:
1. Close project
2. Open new project
3. Create new project with project wizard.

Add clean console for few cases

---

src/rapidgpt/ChatWidget.cpp
src/rapidgpt/ChatWidget.h
src/rapidgpt/ChatWidget.ui
src/rapidgpt/RapidGpt.cpp
src/rapidgpt/RapidGpt.h
tests/unittest/CMakeLists.txt
tests/unittest/rapidgpt/rapidgpt_test.cpp

1. Add Incognito mode indication:
2. Show different message for clear chat history depends on incognito mode. 
3. Fixed Clear chat history, when it was cleared history for the last opened file in incognito mode.

Add Incognoto mode indication. Fixed few bugs ralated to incognito mode

---

src/rapidgpt/RapidGptConnection.cpp
src/rapidgpt/RapidGptConnection.h

Update for RapidGPT error.
Show proper message if file size reach the limit:

RapidGPT: Show error message when file is too big

---

.github/workflows/version.yml
CMakeLists.txt

Updated version.yml to provide sufficient permission to push back to repo

Update version.yml to solve permission problem for increment.yml

---

CMakeLists.txt
src/Simulation/Simulator.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Bitstream simulation fix

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Design edit

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/Simulation/Simulator.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fabric IO edit

---

src/Simulation/Simulator.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Bit sim fix

---

src/Simulation/Simulator.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Bitsim fix

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

Pass config.json file dump by design edit plugin to pin cmd

Pass config.json file dump by design edit plugin to pin cmd

---

src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

pin_c netlist path

---

CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/CompilerDefines.cpp
src/Compiler/CompilerDefines.h
src/Compiler/CompilerOpenFPGA.cpp
src/MainWindow/NewProjectDialog.qml
src/MainWindow/PerfomanceTracker.cpp
src/MainWindow/main_window.cpp
src/MainWindow/mainwindowmodel.h
src/NewProject/ProjectManager/project_manager.h
src/NewProject/newprojectmodel.cpp
src/NewProject/newprojectmodel.h
src/NewProject/project_type_form.cpp
src/NewProject/project_type_form.ui
src/NewProject/source_grid.cpp
src/ProjNavigator/tcl_command_integration.cpp
tests/unittest/MainWindow/PerfomanceTracker_test.cpp

Enable Analysis and Synthesis tasks in Task table for gate-level flow:
Renate Post-Synthesis to Gate-level

Enable Analysis and Synthesis tasks for gate-level flow

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

> - [ X] To address an existing issue. If so, please provide a link to the issue: <issue id>
Sync up with netlist generation process

Bistream netlist gen recipe change

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

Move file reading from c++ to TCL command execution.  
> 
> 
> 
> 
> 
> 
> - [x] Engine
> - [ ] Break back-compatibility. If …

Miscellanous Update for IO support

---

src/Simulation/Simulator.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Post PnR wrapper

---

src/Compiler/CompilerOpenFPGA.cpp
src/Main/registerTclCommands.cpp
src/NewProject/CustomLayout.cpp
src/NewProject/CustomLayout.h
src/NewProject/CustomLayoutBuilder.cpp
src/NewProject/CustomLayoutBuilder.h
src/NewProject/Main/registerNewProjectCommands.cpp
src/NewProject/ProjectManager/config.cpp
src/NewProject/ProjectManager/config.h
src/NewProject/device_planner_form.cpp
src/NewProject/device_planner_form.h
src/NewProject/device_planner_form.ui
src/NewProject/new_project_dialog.cpp
src/NewProject/new_project_dialog.h
tests/TestGui/gui_new_project.tcl
tests/TestGui/userInteraction.tcl

Updates for custom devices:
Main changes: 
* Allow user edit device created previously.
* Allow user remove created device.
* For custom device new field added: `<internal name="MPW1" type="base_device"/>` to identify base device.
Minor updates:
* Fixed issue with devices list header table
* Code refactoring
* tcl tests

[EDA-2517] Custom device improvements

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/CompilerOpenFPGA.h

> - [ ] Breaking new feature. If so, please describe the details in the description part.
When the end user creates a custom device, pass the base device name to verify the license availability.

Pass base device name to license check in case of custum device

---

src/NewProject/CustomLayout.cpp

Fixed max values for custom device width and height properties

Fixed custom device width/height limits

---

src/NewProject/CustomLayout.cpp
src/NewProject/device_planner_form.cpp

Updates: 
* Validate custom device name. Letters, numbers, `-` and `_` are allowed. But it can't start with `-` or `_`
* When modify device, remove old layout only after all other steps are successful.
* Fixed validator for device bram and dsp, 9 digit was missing.

Add device name validation

---

CMakeLists.txt
src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/device_modeler.h

> - [ ] Get Property (Necessary for Mux description and other Modeling)

Necessary infra for Mux predefined types

---

CMakeLists.txt
src/NewProject/CustomLayout.cpp
src/NewProject/CustomLayoutBuilder.cpp
src/NewProject/CustomLayoutBuilder.h
tests/TestGui/gui_new_project.tcl
tests/unittest/CMakeLists.txt
tests/unittest/NewProject/CustomDeviceResources_test.cpp

Updates:
* Add calculation for LUT, FF, BRAM, DSP and Carry Length of custom device.
* Add  verification messages when parameters are not valid.
* Add unit tests and update tcl test

 Custom device, resources calculation

---

CMakeLists.txt
src/Configuration/ModelConfig/ModelConfig.cpp
src/Configuration/ModelConfig/ModelConfig.h
src/Configuration/ModelConfig/ModelConfig_IO.cpp
tests/unittest/ModelConfig/ModelConfig_IO_test.cpp
tests/unittest/ModelConfig/apis/config_attributes.mapping.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json
tests/unittest/ModelConfig/golden/model_config.property.json
tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit
tests/unittest/ModelConfig/model_config_design.json
tests/unittest/ModelConfig/model_config_netlist.ppdb.json

See https://github.com/os-fpga/yosys_verific_rs/pull/603
1. yosys_verific_rs is the one produce the PPDB JSON
2. FOEDAG is the one that consume the PPDB JSON
3. Hence any changes to new format need to be updated here as well
Please note that: this piece of code havent been fully tested, because currently there is synthesis issue in I_BUF_DS and O_BUF_DS use case. See Jira case https://rapidsilicon.atlassian.net/browse/EDA-2652
> …

Prepare to support I_BUF_DS and O_BUF_DS

---

src/rapidgpt/ChatWidget.cpp

Disable rich text for RapidGPT input field to avoid formatting issues like this:

Disable rich text for input RapidGPT editor

---

src/Compiler/Constraints.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Post netlist transform fix for set_pin_loc

---

src/Compiler/NetlistEditData.cpp
src/Compiler/NetlistEditData.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Accurate PIO

---

tests/unittest/ModelConfig/ModelConfig_IO_test.cpp
tests/unittest/ModelConfig/apis/config_attributes.mapping.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json
tests/unittest/ModelConfig/golden/model_config.property.json
tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit
tests/unittest/ModelConfig/model_config_netlist.ppdb.json
tests/unittest/ModelConfig/ric/CLK_BUF.api.json
tests/unittest/ModelConfig/ric/O_BUFT.api.json

Update unit test to include more primitives in the testing
-- I_DELAY, O_DELAY, O_BUFT
> 
> - [ ] Engine
> - [ ] Break back-compatibility. If so, please list who may be …

Include more primitives in unit test

---

src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h
src/Main/TclSimpleParser.cpp
src/Main/TclSimpleParser.h
src/MainWindow/Session.cpp

Update for script mode. Enable all tasks in the task table which run in the script and disable all other. 
For the script like:
```
...
analyze
synth
simulate rtl
```
Task table will looks like:

Enable tasks which run in the tcl script

---

CMakeLists.txt
src/Configuration/ModelConfig/ModelConfig.h
src/Configuration/ModelConfig/ModelConfig_IO.cpp
tests/unittest/ModelConfig/ModelConfig_IO_test.cpp
tests/unittest/ModelConfig/apis/config_attributes.mapping.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json
tests/unittest/ModelConfig/golden/model_config.property.json
tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit
tests/unittest/ModelConfig/model_config_netlist.ppdb.json
tests/unittest/ModelConfig/ric/I_BUF_DS.api.json
tests/unittest/ModelConfig/ric/I_DDR.api.json
tests/unittest/ModelConfig/ric/O_BUFT_DS.api.json
tests/unittest/ModelConfig/ric/O_BUF_DS.api.json
tests/unittest/ModelConfig/ric/O_DDR.api.json
tests/unittest/ModelConfig/ric/PLL.api.json

1. Support allocation of PLL resource
2. Support PLL ICB settings for PLL_REFMUX, PLL and ROOT MUX block. 
3. Support fabric clock assignment
4. Support bit setting for IO BUF DS and IO DDR
> 
> - [ ] Engine
> - [ ] …

Prepare to support PLL ICB

---

CMakeLists.txt
src/Configuration/ModelConfig/ModelConfig_IO.cpp
tests/unittest/ModelConfig/apis/config_attributes.mapping.json

This does not affect functionality of existing feature
1. Just add additional readiness checking from the mapping
- If a particular feature set __ready__ as true, then ModelConfig will go ahead set the bitstream
- if a particular feature set __ready__ as false, then ModelConfig will skip the bitstream setting
- By default it is "ready" if mapping does not specify
2. Rename the variable used in the code
> 
> - [ ] Library: …

Minor update

---

CMakeLists.txt
src/NewProject/CustomLayout.cpp

Update custom device warning hint to be sync with actual calculation.

Update custom device hint

---

src/DeviceModeling/device_instance.h
src/DeviceModeling/device_modeler.h
src/DeviceModeling/device_net.h

> Reduction of the verbosity of RIC device build

Fast tracking integrating the reduction of the verbosity of RIC build

---

src/Simulation/Simulator.cpp

replace file `fabric_<design>_formal_random_top_tb.v` with custom simulation file provided by user.

Replace file fabric_<design>_formal_random_top_tb.v with custom simulation file

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/Constraints.cpp
src/Compiler/Constraints.h
src/DesignQuery/DesignQuery.cpp

Safe parens sdc

---

src/Main/registerTclCommands.cpp
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/NewProject/CustomLayout.cpp
src/NewProject/CustomLayout.h
src/NewProject/CustomLayout.ui
src/NewProject/CustomLayoutBuilder.cpp
src/NewProject/CustomLayoutBuilder.h
src/NewProject/device_planner_form.cpp
src/NewProject/device_planner_form.h
tests/TestGui/gui_new_project.tcl
tests/unittest/NewProject/CustomDeviceResources_test.cpp

Change list:
* Rename Custom device feature into Rapid eFPGA Configurator.
* Update math for custom layout.
* Add new menu, Tools, into main window. Some of the actions where moved to this menu. 
* Add `Rapid eFPGA Configurator` action into Tools menu, so new device can be created from main menu.

New GUI for the custom device feature

---

CMakeLists.txt
src/Simulation/Simulator.cpp

Change list:
* For bitstream simulation:
* append sim top module name at the end of the command instead of `s fabric_<top module>_top_formal_verification_random_tb`
* Icarus only
* In case sim top module is not provided, skip entire part.

Update bitstream simulation

---

src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/device_block.h
src/DeviceModeling/device_modeler.h

> - [ ] implementing:  get_constraint_names, get_constraint_by_name and get_instance_block_type

Dm updates 2

---

src/Main/TclSimpleParser.cpp

Change list:
* Fixed bug with tcl parser. In some specific cases, number of task count can be wrong. Now, tcl script parsed into tokens which makes parsing more accurate.

Fixed parsing of tcl script

---

CMakeLists.txt
etc/device.xml
src/DesignRuns/device_planner_dialog.cpp
src/MainWindow/main_window.cpp
src/NewProject/CustomLayout.cpp
src/NewProject/CustomLayout.h
src/NewProject/CustomLayoutBuilder.cpp
src/NewProject/device_planner_form.cpp
src/NewProject/device_planner_form.h
src/NewProject/new_project_dialog.cpp

Change list:
* Fixed Carry Length calculation
* Filter base devices. Now device which starts with letter 'e' allow for creating custom device.
* Add logging new created or modified device
* Add one more device for testing purposes.

eFPGA updates

---

CMakeLists.txt
src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/device_block.h
src/DeviceModeling/device_modeler.h

> - Implementing get_logic_address, set_logic_address and define_chain

Dm update 04

---

src/Command/Logger.cpp
src/Command/Logger.h
src/MainWindow/CompressProject.cpp
src/MainWindow/CompressProject.h
src/MainWindow/main_window.cpp
tests/unittest/NewProject/CustomDeviceResources_test.cpp

Change list:
* Enable `Save Diagnostics` for production
* Add more entries when save archive with project:
* log files
* user space folder (.foedag)
* Update unit test for eFPGA.

Open Save Diagnostics for production. Add more entries into archive

---

CMakeLists.txt
src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/device_modeler.h

> - Implement add_block_to_chain_type and add Exception Handling

Implement add_block_to_chain_type and add Exception handling EDA-2823

---

src/Configuration/ModelConfig/ModelConfig_IO.cpp
tests/unittest/ModelConfig/apis/config_attributes.mapping.json
tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json
tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit
tests/unittest/ModelConfig/model_config_netlist.negative.ppdb.json
tests/unittest/ModelConfig/model_config_netlist.ppdb.json
tests/unittest/ModelConfig/ric/I_SERDES.api.json
tests/unittest/ModelConfig/ric/O_SERDES.api.json

Changes include:
- Add IO Serdes (map file + API in unit test)
- Correctly configure PLL Ref even though PLL does not need to be routed to FCLK 
> 
> - [ ] Engine
> - [ …

Add IO Serdes support

---

CMakeLists.txt
src/Compiler/Constraints.cpp
src/Compiler/Constraints.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

generate clock support

---

.github/workflows/version.yml
CMakeLists.txt

With the GitHub Actions API update, the check status receives a trigger when we push back from CI but this does not trigger the CI itself. To take care of this, use the key to pretend a real developer is pushing back.
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [ x] Continous Integration (CI) scripts

Update version.yml to use ssh key to push back

---

src/Configuration/ModelConfig/ModelConfig_IO.cpp
tests/unittest/ModelConfig/ModelConfig_IO_test.cpp
tests/unittest/ModelConfig/apis/config_attributes.mapping.json
tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json
tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit
tests/unittest/ModelConfig/golden/model_config_io_bitstream.negative.detail.bit
tests/unittest/ModelConfig/model_config_netlist.negative.ppdb.json
tests/unittest/ModelConfig/ric/I_BUF_DS.api.json

1. Add negative tests
2. Support I_BUF_DS parameter DIFFERENTIAL_TERMINATION
3. Fix unit test flow, which old bitstream need to be cleared before testing new bitstream
Changes include:
- Add IO Serdes support (map file + API in unit test) - no need any C++ code change
- Correctly configure PLL Ref even though PLL does not need to be routed to FCLK
>
> 
> 
> 
> 
> 
> 
> - [ ] Library: …

Add lot of negative tests for clock routing

---

src/DeviceModeling/device_instance.h

Fixing EDA-2840

---

src/Compiler/CompilerOpenFPGA.cpp

Changes:
- Use io_config.json instead of config.json
Testing:
- Not tested
- Downloading latest NS Raptor for batch test
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [ ] Require a change …

Use io_config.json

---

CMakeLists.txt
src/DeviceModeling/device_block.h
src/DeviceModeling/device_instance.h

> - Prohibit the alteration of the structure of a block after usage/instantiation.

Preneting altering the structure of a block after usage/instanciation

---

src/DeviceModeling/device_block.h
src/DeviceModeling/rs_parameter.h

> - Detecting Configuration memory space overlap

Detecting bit overlap for attributes within a block

---

CMakeLists.txt
src/DeviceModeling/device_block.h
src/PinAssignment/PackagePinsView.cpp

Change list:
* Fixed WIN CI issue
* Fixed formatting

Fixed WIN CI failures

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

See https://github.com/os-fpga/yosys_verific_rs/pull/654
This PR is to use design_editor version of SDC in Pin C
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [ ] Require a change on …

PinC use design editor generated SDC

---

CMakeLists.txt
Makefile
src/DeviceModeling/device_block.h
src/DeviceModeling/device_modeler.h
src/DeviceModeling/device_net.h
tests/unittest/DeviceModeling/tcl_tests/unit_test_get_parameters.tcl
tests/unittest/DeviceModeling/tcl_tests/unit_test_get_port_list.tcl
tests/unittest/unit_tests.tcl

> - Adding tcl unit tests to FOEDAG and changing ric logging messages to allow it.

Using ::tcltests built in library for newly added tcl uint tests

---

src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/NetlistEditData.h

Changes list:
* Fixed scrambled path names in reports files
* Fixed NetlistEditData interface to make it more safe.

Replace all reports *.rpt scrambled path names

---

src/Compiler/Compiler.h
src/MainWindow/main_window.cpp

Add basics to allow settings defauls adjustment

Add basics to allow settings defaults adjustment

---

CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/Simulation/Simulator.cpp

Add top module name detected by analyze. In case analyze skipped for some reason, load top module on demand.

Add top module name detected by analyze

---

CMakeLists.txt
src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/device_block.h
src/DeviceModeling/device_instance.h
src/DeviceModeling/device_modeler.h
src/DeviceModeling/device_net.h

> - Adding commands create_instance_chain and append_instance_to_chain. access commands to instance chains and unit tests yet to come.

Adding instance chains infra

---

CMakeLists.txt
src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/device_block.h
src/DeviceModeling/device_modeler.h

> - Continued instance chain support

Continued instance chain support

---

CMakeLists.txt
src/Main/Settings.cpp
src/Main/WidgetFactory.cpp
tests/unittest/Settings/Settings_test.cpp

Change list:
* For checkbox settings, store value in the tcl options for both state, checked and unchecked (it was checked only before). Now every switch will have "true"/"false" value.
* Fixed unit tests

Fixed settings checkbox

---

CMakeLists.txt
src/Configuration/ModelConfig/ModelConfig_IO.cpp
src/Configuration/ModelConfig/ModelConfig_IO.h
src/Configuration/ModelConfig/ModelConfig_IO_resource.cpp
src/Configuration/ModelConfig/ModelConfig_IO_resource.h
tests/unittest/ModelConfig/apis/config_attributes.mapping.json
tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json

Gradually make ModelConfig data driven again:
- Remove resource from c++ (example: https://github.com/os-fpga/FOEDAG/pull/1611/files#diff-e7ef9b87d7819cf46bac0659ac022389662e6bd4785caddb171d942c8a3579f2L243-L290)
- Data driven from config mapping file (example: https://github.com/os-fpga/FOEDAG/pull/1611/files#diff-c2a3e56a6cabfc957dc6918367d5cf6dab8419e8f84a1b68b1416b5f32e49605R361-R380)
Testing done:
- Port this PR to latest NS Raptor
- Run test/batch, test/batch_gen2, …

Make model-config data-driven again

---

CMakeLists.txt
src/DeviceModeling/DeviceModeling.cpp
src/DeviceModeling/DeviceModeling.h
src/DeviceModeling/Model.cpp
src/DeviceModeling/Model.h
src/DeviceModeling/device.h
src/DeviceModeling/device_block.h
src/DeviceModeling/device_instance.h
src/DeviceModeling/device_modeler.h
src/DeviceModeling/device_net.h
src/DeviceModeling/device_pin.h
src/DeviceModeling/device_port.h
src/DeviceModeling/device_signal.h
src/DeviceModeling/logging_utilities.h
src/DeviceModeling/rs_expression.h
src/DeviceModeling/rs_expression_evaluator.h
src/DeviceModeling/rs_parameter.h
src/DeviceModeling/rs_parameter_type.h
src/DeviceModeling/speedlog.h
tests/unittest/DeviceModeling/tcl_tests/unit_test_get_parameters.tcl
tests/unittest/DeviceModeling/tcl_tests/unit_test_get_port_list.tcl

> - A clean cut hold on implementation by a set of unit tests (Unit tests still could be developed)

Dm update 14

---

CMakeLists.txt
tests/unittest/DeviceModeling/tcl_tests/unit_test_constraints.tcl
tests/unittest/DeviceModeling/tcl_tests/unit_test_get_attributes.tcl
tests/unittest/DeviceModeling/tcl_tests/unit_test_get_block_names.tcl
tests/unittest/DeviceModeling/tcl_tests/unit_test_get_instance_names.tcl
tests/unittest/DeviceModeling/tcl_tests/unit_test_get_parameter_types.tcl
tests/unittest/DeviceModeling/tcl_tests/unit_test_io_b_location.tcl
tests/unittest/DeviceModeling/tcl_tests/unit_test_map.tcl

Adding unit tests

---

CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/CompilerOpenFPGA.cpp
src/Simulation/Simulator.cpp
tests/TestBatch/test_compiler_mt.tcl

Change list:
* Show always error message when user try to run some task without project

Show always error message when user try to run some task without project

---

.github/workflows/main.yml
CMakeLists.txt

Use the latest version of the qt setup action to resolve the issue of downloading qt.

Update main.yml to use v4.0.0 of setup qt action

---

CMakeLists.txt
src/MainWindow/main_window.cpp
src/ProjNavigator/FileExplorer.cpp
src/ProjNavigator/FileExplorer.h

Change list:
* Fixed bug, when explorer current path did not change after new project created.
* Add label that shows current path in the explorer.

Updates for the file explorer

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.h
src/Main/main.cpp

Backend now builds 'planning' executable.

renamed stars to planning

---

src/Compiler/CompilerOpenFPGA.cpp
src/Compiler/CompilerOpenFPGA.h

Initial support for routing graph and flat routing.

flat_routing and routing_graph commands

---

CMakeLists.txt
src/Compiler/TaskManager.cpp
src/Compiler/TaskManager.h

Change list:
* Run upstream tasks when user click run any task by clicking on it. Some rules applied in this case:
* If task upstream task disabled, enable it.
* Do not enable simulation tasks
* Enable simulation tasks if user wants to run it

Run upsteam tasks when user run any task

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
Support INI to source the pin SDC that can be used to overwrite mode and internal signals determined by design-editor-extractor. 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine …

Support INI to overwrite pin mode and loc

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
This PR support enhanced version of set_io command (only being used internally)
Testing done:
- Port this PR (+https://github.com/os-fpga/yosys_verific_rs/pull/686) to latest NS Raptor
- Run test/batch, test/batch_gen2 and test/batch_gen3
- Run all GJC - make sure compilation pass but I think there is issue of the project/overall-architecture
>
> 
> 
> 
> 
> 
> 
> - [ ] …

Support enhance version set_io command

---

src/Simulation/Simulator.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Verilator flags

---

CMakeLists.txt
src/Compiler/CompilerOpenFPGA.cpp

> 
> 
> 
> 
> 
Existing flow only support INI to overwrite:
- mode
- internal_pin
This enhancement unify the default flow and INI flow, which extend the overwritten to support 
- set_clock_pin
Also enhance INI path with relative path support. 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> …

Enhance INI support

---

CMakeLists.txt
src/PinAssignment/BufferedComboBox.cpp
src/PinAssignment/CMakeLists.txt
src/PinAssignment/ComboBox.cpp
src/PinAssignment/ComboBox.h
src/PinAssignment/PackagePinsView.cpp
src/PinAssignment/PinAssignmentBaseView.cpp
src/PinAssignment/PinAssignmentBaseView.h
src/PinAssignment/PortsView.cpp

Change list:
* Hide Mode and Internal pin columns for IO Ports table
* Hide Mode and Internal pin columns for Package Pin table
* Create new combo box component for both tables which disables mouse wheel event (No value change on mouse wheel event)

Update Pin planner

---

CMakeLists.txt
src/Compiler/Constraints.cpp

Fixed build issue related to undefined behavior.

Fixed MAC build issue

---

CMakeLists.txt
src/Compiler/Compiler.cpp
src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.cpp
src/IpConfigurator/IPDialogBox.cpp
src/IpConfigurator/IPDialogBox.h
src/IpConfigurator/IpConfigWidget.cpp
src/Main/registerTclCommands.cpp
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/NewProject/ProjectManager/config.cpp
src/NewProject/ProjectManager/config.h
src/NewProject/new_project_dialog.cpp
src/NewProject/new_project_dialog.h

Change list:
* Extend IP Catalog communication protocol with two new fields:
* device - device name
* device_path - path to device file.
* Show warning message when user switch target device

Pass device name and device file path to IP catalog

---

CMakeLists.txt
src/Configuration/ModelConfig/ModelConfig.cpp
src/Configuration/ModelConfig/ModelConfig_IO.cpp
src/Configuration/ModelConfig/ModelConfig_IO.h
tests/unittest/ModelConfig/apis/config_attributes.mapping.json
tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json
tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit
tests/unittest/ModelConfig/golden/model_config_io_bitstream.negative.detail.bit
tests/unittest/ModelConfig/model_config_netlist.negative.ppdb.json
tests/unittest/ModelConfig/model_config_netlist.ppdb.json

> 
> 
> 
> 
> 
Simplify the code and map syntax
- Does not affect the generated bit value
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> …

Simplify ModelConfig

---

CMakeLists.txt
src/MainWindow/main_window.cpp
src/PinAssignment/PackagePinsView.cpp
src/PinAssignment/PinAssignmentBaseView.cpp
src/PinAssignment/PinAssignmentBaseView.h
src/PinAssignment/PortsView.cpp

Change list:
* Fixed crash when close Pin Planner
* Pin Planner combo box management moved to base view class
* Fixed debug output when failed to open file during opening Pin Planner (add check if file exists)

Fixed crash when close Pin Planner

---

CMakeLists.txt
src/MainWindow/main_window.cpp
src/MainWindow/main_window.h
src/ProjNavigator/sources_form.cpp
src/ProjNavigator/sources_form.h

Make access to the design files settings fester.

Add user actions to make more easy access to design files

---

CMakeLists.txt
tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json
tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit
tests/unittest/ModelConfig/golden/model_config_io_bitstream.negative.detail.bit
tests/unittest/ModelConfig/model_config_netlist.negative.ppdb.json
tests/unittest/ModelConfig/model_config_netlist.ppdb.json

> 
> 
> 
> 
> 
Update the unit test with latest netlist compiled from latest Raptor
- No bitstream binary bit change
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [ ] Require a change on …

Update unit test

---

src/rapidgpt/Test/RapidGptCommands.cpp

Make sure rapidgpt tcl test doesn't give false positive results. Instead of searching `server replied` key word we just verify if error string does not empty.

Fixed tcl test command "rapidgpt_send"

---

src/NewProject/ProjectManager/project_manager.cpp
src/NewProject/ProjectManager/project_manager.h
src/NewProject/source_grid.cpp
src/NewProject/source_grid.h
tests/unittest/NewProject/ProjectManager_test.cpp

Provide "overwrite" option when creating file with the same name in Raptor GUI

Allow user to overwrite a file if it already exists

---

src/Compiler/Compiler.cpp
src/Simulation/Simulator.cpp
src/Simulation/Simulator.h

- WIP SDF annotation PNR sim
- Simulation macros streamlining

SDF sim WIP

---

src/Simulation/Simulator.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Fix fallthrough

---

CMakeLists.txt
src/Configuration/ModelConfig/ModelConfig_IO.cpp
tests/unittest/ModelConfig/apis/config_attributes.mapping.json
tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json
tests/unittest/ModelConfig/model_config_netlist.negative.ppdb.json
tests/unittest/ModelConfig/model_config_netlist.ppdb.json

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
1. Enhancement to include flags information in the config JSON output
2. Does not affect bit setting
> 
> - [ ] Engine
> - [ ] Require a change on …

Enhancement to include more info in config JSON file

---

CMakeLists.txt
src/Configuration/ModelConfig/ModelConfig_IO.cpp
src/Configuration/ModelConfig/ModelConfig_IO_resource.cpp
src/Configuration/ModelConfig/ModelConfig_IO_resource.h
tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json

> 
> 
> 
> 
> 
This is to support PLL VCO. 
Will include test case when netlist issue is resolved. 
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [ ] Require a change on Quality of Results …

Support PLL VCO output

---

src/Compiler/Compiler.h
src/Compiler/CompilerOpenFPGA.h
src/Simulation/Simulator.cpp

Icarus does not support vectors in .sdf
We bitblast both the netlist and the sdf file.

bitblast sdf for Icarus

---

src/Compiler/Constraints.cpp
src/Compiler/Constraints.h

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

clock check for timing constraints

---

src/Compiler/NetlistEditData.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

Primary output heuristic

---

src/MainWindow/main_window.cpp

> - [x] To address an existing issue. If so, please provide a link to the issue: EDA-3200
> Pin Planner crashes on any usage, likely due to change in data table access.
> Disables Pin Planner in production mode
> 
> - [ ] Engine

Disable Pin Planner due to crash until resolved.

---

CMakeLists.txt
src/Simulation/Simulator.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

DSP RAM Timed sim wip

---

CMakeLists.txt
tests/unittest/ModelConfig/apis/config_attributes.mapping.json
tests/unittest/ModelConfig/golden/model_config.ppdb.json
tests/unittest/ModelConfig/golden/model_config_io_bitstream.backdoor.txt
tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit
tests/unittest/ModelConfig/golden/model_config_io_bitstream.negative.detail.bit
tests/unittest/ModelConfig/ric/gbox_top.tcl

> 
> 
> 
> 
> 
Update config mapping file to set PEER_IS_ON for peer gearbox
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [ ] Break …

Set PEER_IS_ON for peer gearbox

---

src/Compiler/Constraints.cpp

more accurate support for -clock <clock name> in constraints

-clock better support

---

src/Simulation/Simulator.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

bitblast exe path fix

---

src/Compiler/NetlistEditData.cpp

> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine

generated clock fix
