src/Console/DummyParser.cpp, src/Console/TclConsole.cpp, src/Console/TclConsoleWidget.cpp, src/Console/TclConsoleWidget.h, src/Console/TclWorker.cpp, src/Console/TclWorker.h, src/Console/Test/ConsoleTestUtils.cpp, src/Console/Test/console_main.cpp, src/Console/Test/console_standalone.cpp, src/Console/Test/console_test.cpp, tests/TestGui/gui_console_proc.tcl, third_party/QConsole/include/qconsole.h, third_party/QConsole/src/qconsole.cpp
Close #174 
Make console single threaded and fixed crash when run in replay mode.
The **puts** command won't work in this case. So, for the tests I have replaces it with **debug** command for the redirection into the console widget.
=> Make console single threaded and fix crash in replay mode (close #174)

.github/workflows/main.yml, .gitmodules, CMakeLists.txt, cmake/cmake_tcl.txt
We are now using Tcl8.6.12 which is supported by SWIG. Tcl9.0 is not supported by SWIG.
=> Remove Tcl9.0 submodule

src/Main/CMakeLists.txt, src/Main/Foedag.cpp, src/Main/Foedag.h, src/Main/Settings.cpp, src/Main/Settings.h, src/Main/Tasks.cpp, src/Main/Tasks.h, src/Main/main.cpp, src/Main/registerTclCommands.cpp, src/MainWindow/Session.h, src/NewFile/Test/newfile_main.cpp, src/NewProject/Main/newproject_main.cpp, src/ProjNavigator/Test/projnavigator_main.cpp, src/TextEditor/Test/texteditor_main.cpp
Per a conversation regarding singleton use in the previous settings PR (https://github.com/os-fpga/FOEDAG/pull/319#discussion_r861167792), I've refactored the settings object to remove singleton and static elements and instead tried to copy the way data is passed around in the Session class.
@alain-rs & @volodymyrkochyn does this look like a better approach to you?
I had to touch a lot more files with this approach which makes me feel like it's a bit more tightly coupled, but wanted to get your opinion.
I also had to re-arrange the order of the last parameters on FOEDAG::Foedag() instantiation as ToolContext is passed w/ a default arg and not provided in a number of our instantiations.
Leaving this as a draft PR for now to make sure this is a desired change.
=> Possible Settings Refactor

src/Console/TclWorker.cpp
Remove input channel from TCL to avoid default prompt when custom console is created.
=> Remove TCL default prompt from console

src/Compiler/Compiler.cpp, src/Console/TclConsoleWidget.cpp
Main issue was word wrap in the console.
The problem still exists when process produces output more than 10k lines at the same time.
=> Fixed gui freeze when log output is very big (#362)

src/ProjNavigator/sources_form.cpp, src/ProjNavigator/sources_form.h
Files from the project folder are shown with folder tree.
Files outside the project are shown with full path (close #342)
=> Rework project navigator.

etc/settings/settings_test.json, src/Compiler/CompilerDefines.cpp, src/Compiler/CompilerDefines.h, src/Compiler/Task.cpp, src/Compiler/Task.h, src/Compiler/TaskManager.cpp, src/Compiler/TaskModel.cpp, src/Compiler/TaskTableView.cpp, src/Compiler/TaskTableView.h, src/Main/Foedag.cpp, src/Main/Settings.cpp, src/Main/Settings.h, src/Main/Tasks.cpp, src/Main/Tasks.h, src/Main/WidgetFactory.cpp, src/Main/WidgetFactory.h, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
Task tree "Edit Settings" entries now render as buttons and will dynamically load a settings dialog for the parent Task.
Current settings are still test values and aren't integrated with the respective tasks.
If no project is loaded, editing task settings will persist for the session only(currently).
If a project has been loaded, settings will be saved in the project folder under [projectName].settings/ as json files.
When a project is loaded or created, current settings are cleared, system defaults are reloaded and project settings are loaded (see below).
When a project is loaded, all .json files found in the project folder [projectName].settings/ anr loaded and merged into the current settings json.
=> Adding persistence to task settings dialog system

etc/settings/settings_test.json, src/Main/Tasks.cpp, src/Main/WidgetFactory.cpp, src/Main/registerTclCommands.cpp
> - This adds tcl arg support to the settings/widget factory system for the remaining widgets (previously only comboboxes and checkboxes were supported)
> - The temporary console command DemoWidgets has been updated to show all the widget types using a tcl arg
> - Check the code for "TclExample" to see a basic example of how to add tcl arg support to a settings dialog.
=> Adding tcl arg support for remaining widget types

src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h, src/ProjNavigator/tcl_command_integration.cpp
Provide user more clear and full information which file is not exists for the command add_design_file. Close #515 
Return from the function list of all files that are not exists.
Error before:
Error after:
=> Improve error message when file is not exists (close #515)

src/Main/AboutWidget.cpp, src/Main/AboutWidget.h, src/Main/main.cpp
Allow to show/hide LICENSE at about window.
Added into the FOEDAG::ProjectInfo showLicense flag which indicates whether need to show license or not.
=> Allow show/hide LICENSE at About window

src/Compiler/CompilerDefines.cpp, src/Compiler/CompilerDefines.h, src/Compiler/CompilerOpenFPGA.cpp, src/Main/ProjectFile/ProjectManagerComponent.cpp, src/NewProject/ProjectManager/project_manager.cpp
Read constraint file before add it to the project.
We expect that after project build file <filename>_openfpga.sdc should appear in the project folder. It should be non empty.
How to test.
1. Create new project with all files via project wizard and build.
2. Create project and add files from the context menu and build.
3. Open project file and build.
=> Read constraint file before it added to the project

src/TextEditor/text_editor_form.cpp
This commit extends file tabs with a tooltip, containing full file path (#537):
=> Show full file path in a tab tooltip

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
Improve file loading. Current implementation load file on every reopen main window. It doesn't make sense to do it every time. 
I reworked it in a way that load file only when user choose Open Project.
Move open file from reopen main window.
We load file only when user open project.
Core
The P&R View button. This button need to update after file is loaded.
=> Improve file loading

src/Compiler/TaskManager.cpp, src/MainWindow/main_window.cpp, src/NewProject/source_grid.cpp, src/ProjNavigator/sources_form.cpp
> - [ ] [To follow a UI Standard. Changes are made for this issue: <issue id>](https://github.com/os-fpga/FOEDAG/issues/465)
> - [ ] While menu commands are used for immediate actions, more information might be needed to perform the action. Indicate a command that needs additional information (including a confirmation) by adding an ellipses "..." at the end of the label.
> - [ ]  UI standards call for all menu picks that require additional user input to have ... at the end of their text.
> 
> 
> 
> 
> 
>
> 
> 
> 
> - [ ] Changed the menu picks from "New" , "Open File ", "New Project", Open Project" to "New...", "Open File...", "New Project...", "Open Project..." and vice …
=> Added ... ellipses in Menu Picks texts that invoke dialog 

src/NewProject/location_form.cpp, src/NewProject/location_form.h
> - [ ] To address an existing issue, Open --> https://github.com/os-fpga/FOEDAG/issues/466
> - [ ] The New Project wizard defaults to project_1 and project name check action was set on Next Button. Now logic is updated to automatically set the project name which doesn't exist in the directory without pressing Next Button. 
> - When New Project Menu option is clicked, project name automatically sets to new name which doesn't exist in the directory. Each time creating a new project it increments "x" in  project_x as project name. By default it sets to project_1.
>  https://github.com/os-fpga/FOEDAG/issues/466 
>- Project Name updated until a unique path …
=> Default ProjectName Logic Improved

Makefile, src/MainWindow/main_window.cpp, tests/TestBatch/test_compiler_stop.tcl
Fixed issue with Stop button. It become disable event when process still in progress
Steps to reproduce:
* Open some project with openfpga compiler
* Press Start button
*Actual results:* Stop button become disable after second task has started.
*Expected results:* Stop button enabled until all tasks done.
Call Compiler::finish only after all tasks done.
Need to test Stop button when run some script.
=> Fixed Stop button, when it become disable event operation is still running

src/Compiler/CompilerDefines.cpp, src/Compiler/CompilerDefines.h, src/Main/ProjectFile/ProjectManagerComponent.cpp, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h, src/ProjNavigator/tcl_command_integration.cpp
This is a fix of a bug that related to new project creation. When user wants create new project, the selection of the device doesn't taking into account.
When user select device and press Ok in the wizard, target_device tcl command is running with corresponding device name. Also, the same happened when file is loading.
=> Fixed device selection when new project started

src/MainWindow/main_window.cpp
Given PR makes sure that GUI takes the full-screen size after startup. 
After switching to 'Normal' mode GUI takes 2/3 part of the screen, horizontally aligned.
Calculations are based on more recent QScreen instead of QDesktopWidget. It's also recommended by Qt:
https://doc.qt.io/qt-5/qdesktopwidget-obsolete.html
=> show main window maximized; restore as 2/3 of primary screen

src/NewProject/new_project_dialog.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-25
> The standard OK button was used when dialog was switched to QDialogButtonBox
>
> This renames the QDialogButtonBox OK button to "Finish"
> - [x] None
> ### Testing
> - Testing via CI smoke tests as well as manual integration testing w/ Raptor
> - This change is in text only and …
=> [RG-25] Renaming New Project Wizard Ok button to Finish

src/IpConfigurator/CMakeLists.txt, src/IpConfigurator/IpConfigurator.cpp, src/IpConfigurator/IpConfiguratorCreator.cpp, src/IpConfigurator/IpConfiguratorCreator.h, src/IpConfigurator/Test/ipconfigurator_main.cpp, src/Main/registerTclCommands.cpp, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-32
> The IpConfigurator's submodule creation wasn't correct and could lead to a segfault under testing
>
> This updates the IpConfigurator such that it copies the approach of other submodules
> 
> - [ ] Engine
> - [x] None
> - ipconfigurator_show & ipconfigurator_hide are …
=> RG-32: Refactoring IpConfigurator

src/Compiler/TaskModel.cpp, src/Compiler/TaskModel.h
Issue: task table will not expand row when new rows arrived.
There is wrong conversion between task id and row index.
=> Fixed task table, expanding rows issue

etc/templates/ports_test.json, src/MainWindow/main_window.cpp, src/PinAssignment/BufferedComboBox.cpp, src/PinAssignment/BufferedComboBox.h, src/PinAssignment/CMakeLists.txt, src/PinAssignment/PackagePinsLoader.cpp, src/PinAssignment/PackagePinsModel.cpp, src/PinAssignment/PackagePinsModel.h, src/PinAssignment/PackagePinsView.cpp, src/PinAssignment/PackagePinsView.h, src/PinAssignment/PinAssignmentBaseView.cpp, src/PinAssignment/PinAssignmentBaseView.h, src/PinAssignment/PinAssignmentCreator.cpp, src/PinAssignment/PinsBaseModel.cpp, src/PinAssignment/PinsBaseModel.h, src/PinAssignment/PortsLoader.cpp, src/PinAssignment/PortsLoader.h, src/PinAssignment/PortsModel.cpp, src/PinAssignment/PortsModel.h, src/PinAssignment/PortsView.cpp
Add Ports table for the pin assignment feature. Synchronize selections between ports and package pins
Load ports data from json file and show it in the ports table. Selection in Ports table and Package Pin table are synchronized.
=> Add IO ports table and sync with package pin table

src/Compiler/Compiler.cpp, src/Compiler/CompilerOpenFPGA.cpp, src/Main/ProjectFile/ProjectManagerComponent.cpp, src/NewProject/ProjectManager/project_fileset.cpp, src/NewProject/ProjectManager/project_fileset.h, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h, src/ProjNavigator/tcl_command_integration.cpp, src/ProjNavigator/tcl_command_integration.h
Given PR extends 'add_Design_files ' TCL command with '-work' and '-L' arguments.
It also makes sure they are passed to Yosys script. So far only Verific parser is supported, as default Yosys one puts all the files from the script into one pile.
UI is also not included here.
By default, empty strings will be used and previous behavior kept.
To make its behavior more clear, here is the example: Input (test.tcl)
...
add_design_file -work lib1 test.v -SV_2012
add_design_file -L lib1 -L lib2 bottom.v -SV_2012
...
Output (test.ys):
...
verific -work lib1  -sv2012 /home/work/Work/FOEDAG-Taras/tests/Testcases/trivial/test.v
verific -L lib1 -L lib2  -sv2012 /home/work/Work/FOEDAG-Taras/tests/Testcases/trivial/bottom.v
...
Tested on FOEDAG application with following cmdline commands:
--verific …
=> extend add_Design_files command with -work and -l arguments.

CMakeLists.txt, Makefile, src/Console/TclConsoleWidget.cpp, src/Console/TclConsoleWidget.h, src/IPGenerate/IPCatalogBuilder.cpp, src/IPGenerate/IPGenerator.cpp, src/IpConfigurator/IpCatalogTree.cpp, src/IpConfigurator/IpCatalogTree.h, src/MainWindow/main_window.cpp, tests/Testcases/IPGenerate/IP_Catalog/nested/folder/dummy_1_gen.py, tests/Testcases/IPGenerate/IP_Catalog/nested/folder/further/nested/dummy_2_gen.py, tests/Testcases/IPGenerate/test_recursive_load.tcl
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-27
> 
> 
> 
> 
> 
> buildLiteXCatalog only searches the single directory passed to it
> 
> 
> 
> 
> 
> - Updates buildLiteXCatalog to use `std::filesystem::recursive_directory_iterator` instead of `std::filesystem::directory_iterator`
> - Updates CMakelists.txt to install IP_Catalog at share/foedag/IP_Catalog and include a nested dummy ips
> - Updates call to display the Available Ips dock widget so that the console prompt works as expected …
=> RG-27: Supporting recursive search for IP Gen Python script

src/Compiler/Compiler.cpp
> This speeds up any test that runs the Sythensize or Global Placement tasks in the Foedag dummy compiler
> Currently the dummy compiler prints a percentage increase every second to simulate a task running.
>
> The delay between updates has been reduced to 100ms to speed up test runs
> 
> - [ ] Engine
> - [x] Regression tests
> Dummy compiler tasks will finish faster
=> Reducing dummy compiler delay from 1s to 100ms

Makefile, src/IPGenerate/IPCatalog.cpp, src/IPGenerate/IPCatalog.h, src/IPGenerate/IPCatalogBuilder.cpp, src/IpConfigurator/IpCatalogTree.cpp, src/IpConfigurator/IpConfigDlg.cpp, src/IpConfigurator/IpConfigDlg.h, src/IpConfigurator/IpConfigurator.cpp, src/IpConfigurator/IpConfiguratorCreator.cpp, src/Main/WidgetFactory.cpp, src/Main/WidgetFactory.h, src/Main/registerTclCommands.cpp, src/Utils/StringUtils.cpp, src/Utils/StringUtils.h, tests/TestGui/gui_ipconfigurator.tcl, tests/Testcases/IPGenerate/IP_Catalog/dummy_generators/RapidSilicon/IP/axis_converter/V1_0/axis_converter_gen.py, tests/Testcases/IPGenerate/IP_Catalog/dummy_generators/RapidSilicon/IP/axis_converter/V1_1/axis_converter_gen.py, tests/Testcases/IPGenerate/IP_Catalog/nested/folder/dummy_1_gen.py, tests/Testcases/IPGenerate/IP_Catalog/nested/folder/further/nested/dummy_2_gen.py
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-14
> IP Configurator dialog was empty
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> Ip Configurator dialog now looks up and displays an IP's VLNV meta data, parameters, and the generated output path.
> 
> - [x] Library: IPGenerate, IpConfigurator
> - [ ] Engine
> - [x] Regression tests
> ### Impact …
=> RG-14: Populating IP Configurator UI

src/MainWindow/WelcomePageWidget.cpp, src/MainWindow/main_window.cpp
Motivate of the pull request:
- #RG-49
- #RG-51
As a result of logo pixelation improvement, it changes from upper to lower:
The second change makes sure shortcuts of welcome page actions aren't overlapped:
=> fix logo pixelitation issue; update welcome page actions shortcuts

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/NewProject/new_project_dialog.cpp
When create new project - window title doesn't reflect the project name (see screenshot)
When get text for window title - it is wrong calculation of existing folder.
Show/hide new project title was updated according to the documentation.
=> Fixed wrong window title after new project has started

src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h
When start new project - no target device in the project manager.
After new project is created - project manager doesn't provide target device. E.g. 
qDebug() << projectManager->targetDevice(); will show empty string.
=> Fixed empty target device

src/MainWindow/main_window.cpp
There is crash when welcome page started and user try to create new project.
Before welcome page started we need to initialize everything which is done by ReShowWindow method. Not calling it leads to many problems.
=> Fixed crash when welcome page is open

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
The motivation of this PR is RG-52 issue, which is caused by some actions not making sense on a welcome page.
As a quick solution we'll just hide entire menu bar. In the future we might want to implement more intelligent mechanism on managing views on a menu bar.
As long the code hiding toolbars for the welcome page already exists, I extended it with hiding the menu bar as well.
>
Menu bar will no longer be visible when welcome page is on.
=> hide menu bar on welcome page

src/IpConfigurator/IpCatalogTree.cpp, src/IpConfigurator/IpCatalogTree.h
> Discovered an oversight in original Available IP Logic that could result in Raptor displaying an empty IP tree even after a semi successful load of IPs.
> It was assumed that return value of IPCatalogBuilder::buildLiteXCatalog (which loads all IPs at once) would return true if any of the IPs succeeded to load (assuming the return result was OR'd with loop results), but its logic works out such that it returns false if any of the IPs failed to load. My code was overprotectively skipping displaying of any IPs when the return value was false.
>
> The return value is no longer checked and instead the system is …
=> Fix potential empty Available IP tree scenario in Raptor

src/NewProject/ProjectManager/config.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: GEMINIEDA-338
> A device table is filled based off a key compare in a QMap. The existing code gave the same key to sibling devices with the same device/series/family. This resulted in the table only ever showing 1 device because whichever device was read in last overwrote the previous entry with the same key.
>
> The devices names is added to the key to provide a unique entry in the QMap
> 
> - …
=> GEMINIEDA-338: Fix new project dialog not showing multiple devices

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
The motivation of this change is RG-52 issue, logged on “Show Welcome Page” flag value not stored between runs.
This leads to welcome page appearance after each GUI restart, which might be annoying.
The idea is rather simple: we store an empty file in a working directory. During startup initialization we check whether it's there and don't show the welcome page, if it's not. The file is created when we uncheck "Show Welcome Page" checkbox.
The only way to see the welcome page again is to delete the file from working directory.
=> make “Show Welcome Page” checkbox persistent between runs

src/Compiler/TaskTableView.cpp, src/Compiler/TaskTableView.h
This PR aims to solve rg-58 issue: enable scrollbars while compilations is is progress.
I couldn't activate only the scrollbar and leave all the rest as is. It is part of the view which was disabled automatically.
Still, there is an API to retrieve the widget holding only the data part: viewport().
Disabling only that one leaves scrollbars working - exactly what we want.
By doing so other things got enabled either:
- Selection;
- parent tasks collapse/expand;
- column resize.
Those only affect visual representation and, I hope, are acceptible:
Note: mouse press events got activated as well, so I had to manually catch them while compilation is in progress. Not the best approach, but it avoids extra complexity and …
=> Only disable tasks table viewport and leave scrollbars working

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
The goal of this PR is to fix RG-64 issue: welcome page immediately disappears after unchecking "Show WelcomePage" checkbox. The user should still be able to execute one of proposed actions.
Not hiding the page immediately opens another opportunity for the user: he may change his mind and check the flag again.
In this case the file has to be removed. Still, all this will have to be reworked after we get QSettings working and decide on configuration panel for this.
=> Continue showing welcome page after user unchecked "Show WelcomePage" checkbox

src/MainWindow/WelcomePageWidget.cpp
The goal of this PR is to fix RG-63 issue: labels alignment on the welcome page.
Left margin of description and application name was set to 0, which is similar to actions and recent projects margin.
Show Welcome Page checkbox was moved to the center, as suggested in RG-63.
=> Align welcome page controls

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
Current PR reverts changes of following PR:
https://github.com/os-fpga/FOEDAG/pull/657
Change is caused by updated requirements.
Now welcome page will immediately disappear after unchecking "Show welcome page" flag.
=> Revert changes keeping welcome page open after unchecking show flag

src/IpConfigurator/IpConfigDlg.cpp, src/IpConfigurator/IpConfigDlg.h, src/ProjNavigator/sources_form.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-71
> Currently the source tree lists IP instances by IPName_Version which limits the user to only 1 unique instance of each IP version
> - This PR updates the Ip Instances listing in the source tree to show the user specified Module Name instead of IPName_Version  
> ![image](https://user-images.githubusercontent.com/103447061/191280953-2d14dc76-14f9-4e65-8b09-2b3082a93bba.png)
> - Configure dialog has been updated to handle both configure and re-configure operations as expected …
=> [RG-71] - Use Module Name instead of IP Name for IP Instances in Source Tree

src/Compiler/Compiler.cpp, src/Utils/StringUtils.cpp, src/Utils/StringUtils.h, tests/unittest/Utils/StringUtils_test.cpp
This PR fixes first part of RG-83 issue: make sure *.VHD and *.SV files, passed to add_design_files TCL function, are recognized in case insensitive manner.
There are two ways of detecting which language to use: 
- explicitly indicate it as a parameter of add_design_files():
add_design_file aes_decrypt128.sv aes_decrypt256.sv  -SV_2012
- Or the application automatically deduces the language. Currently only two formats are handled explicitly:
VHDL_2008 (*.vhd)
SYSTEMVERILOG_2017 (*.sv)
Automatic language detection was case sensitive: if the file had *.VHD type, it wasn't recognized as VHDL_2008.
This PR makes sure type is recognized in case insensitive …
=> [RG-83] Recognize *.VHD and *.SV files in case insensitive manner

Makefile, ip_load/axis_converter_V1_0_axis_converter.json, ip_load/axis_converter_V1_0_axis_converter2.json, src/Compiler/Compiler.cpp, src/Compiler/Compiler.h, src/IPGenerate/IPCatalogBuilder.cpp, src/IPGenerate/IPGenerator.cpp, src/IpConfigurator/IpCatalogTree.cpp, src/Main/Foedag.cpp, tests/TestBatch/test_ip_configure_load.tcl, tests/Testcases/IPGenerate/IP_Catalog/dummy_generators/RapidSilicon/IP/axis_converter/V1_0/axis_converter_gen.py, tests/Testcases/IPGenerate/IP_Catalog/dummy_generators/RapidSilicon/IP/axis_converter/V1_1/axis_converter_gen.py
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-70
> Currently the IP_Catalog needs to be manually loaded by calling add_litex_ip_catalog
> add_litex_ip_catalog is now called when ip_catalog and configure_ip are fired and the IP Catalog is empty.
> 
> - [x] Library: IPGenerate, Compiler
> - [ ] Engine
> - [ ] …
=> [RG-70] Auto load IP Catalog

src/NewProject/add_constraints_form.cpp, src/NewProject/add_source_form.cpp, src/ProjNavigator/add_file_form.cpp
> - [x] **Copy files to project option in design creation wizard doesn't actually copy anything**
"Copy sources into project" checkbox was checked by default. Now default option is changed to unchecked.
Screenshot: 
**Test Steps:**
-     Create a new project
-     move next to add source window
-     Verify "Copy sources into project" option is unchecked by default. 
-     Now checked “copy file sources into project”  checkbox 
-     finished the project
-     Open the project folder project_x/project_x.srcs/sources_1 
-     Source file “.v” is copied there. C
>
> 
> 
> 
> 
> 
> ### Which part of the code base …
=> [RG-81] Copy files project checkbox option is set unchecked by default (PART1 & PART 2)

src/IpConfigurator/IpConfigDlg.cpp, src/Main/WidgetFactory.cpp, src/Main/WidgetFactory.h
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-74
> QWidgetFactory currently places widgets and labels in 1 QHBoxLayout per entry. This can result in labels that don't line up.
>
> WidgetFactory and the IP Configuration dialog have been updated to use [QFormLayout](https://doc.qt.io/qt-5/qformlayout.html) which provides better field alignment when labels are involved.
> Per the concerns in the Jira description, extra care was taken to ensure as little of the underlying widget structure was changed as these are GUI related changes and we don't have a GUI test suite to ensure …
=> [RG-74] Improve WidgetFactory field alignment

src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h, src/NewProject/add_source_form.cpp, src/NewProject/add_source_form.h, src/NewProject/add_source_form.ui, src/NewProject/new_project_dialog.cpp, src/ProjNavigator/sources_form.cpp, src/ProjNavigator/sources_form.h, src/ProjNavigator/tcl_command_integration.cpp
Add possibility for users to setup top level module in project wizard. And remove relation to the filename. 
Update Hierarchy view:
* Remove top level item
* Remove action from context menu
=> [GEMINIEDA-371] Add new fields into project wizard - top level module and library for top level

etc/settings/settings_test.json
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-88
> Foedag's settings file has settings specific to Raptor
>
> Effort, FSM Encoding, Carry, and Fast Synthesis options have been removed from the Synthesis settings
> 
> - [x] Library: Main
> - [ ] Engine
> - [ ] Break back-compatibility. If so, please list who …
=> [RG-88] Remove Raptor specific synthesis settings

src/ProjNavigator/sources_form.cpp
Fixed hierarchy view when file name is the same as top module and it is become hidden.
Caused after #670 
* Create project
* Add design file
* set top module same as file name.
Result: No file in the hierarchy.
=> Fixed hierarchy view

src/IPGenerate/IPCatalog.cpp, src/IPGenerate/IPCatalog.h, src/IPGenerate/IPCatalogBuilder.cpp, src/IPGenerate/IPGenerator.cpp, src/Utils/FileUtils.cpp, src/Utils/FileUtils.h
> - [x] To address an existing issue. If so, please provide a link to the issue: [RG-99]
> [FileUtils::LocateExecFile](https://github.com/os-fpga/FOEDAG/blob/f937d2954f15071d256b1f05019d1751864a3f17/src/Utils/FileUtils.cpp#L127) is used to search for a system copy of python3. LocateExecFile currently only works for unix. Additionally, this method of looking for a system copy of python3 will most likely fail to find the correct version of python where we've installed litex modules.
>
> A new function, …
=> [RG-99] Adding logic to find litex enabled python interpreter for IP Catalog

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
> - [x] To address an existing issue. If so, please provide a link to the issue: [RG-109]
> Currently when the users presses the close button, a warning message box is shown asking if the user wants to close the project. 
>
> - There is now a close project message box and an exit program message box
> - Both use a Question message box instead of a Warning message box
> - Logic has been added to show the close project message when a user selects File > Close Project
> - Logic has been added to show the exit program message when …
=> [RG-109] Updating close project and exit program messages

src/NewProject/summary_form.ui
This is a final remark of RG-111 issue: alignment fix of summary tab.
=> [RG-111]Fix alignment of summary tab

src/IpConfigurator/IpConfigWidget.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: GEMINIEDA-418
> Only the base project path is provided to the configure_ip name
>
> The passed output path now matches what configure_ip expects
> 
> - [x] Library: IpConfigurator
> - [ ] Engine
> - [ ] Require a change on Quality of …
=> [GEMINIEDA-418] Fix ip configure output path

src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/source_grid.cpp, src/NewProject/source_grid.h
NOTE this is currently a draft pr to get feedback from devs more familiar with the project system
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-108
> All files in the New Project Wizard are added sequentially which removes the concept of grouping multiples files in one add_design_files call
>
> - This change adds a compile units field to the Add Design Files tab:
> <img width="463" alt="image" src="https://user-images.githubusercontent.com/103447061/193952182-ef7bc419-9eac-488b-bdfc-09bf080 …
=> [RG-108]: Add compile units field to Add Design Files tab in New Project Wizard

src/IPGenerate/IPGenerator.cpp, src/IPGenerate/IPGenerator.h, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/ProjNavigator/sources_form.cpp, src/ProjNavigator/sources_form.h
> - [x] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-417]
> No option is provide to remove or delete an IP
>![image](https://user-images.githubusercontent.com/103447061/193956457-54077ed6-59c4-4823-a1a1-290d76829606.png)
> - 2 new options are provided
> - "Remove IP from project" will remove the IP instance from the current set of ip instances but leaves IP build files.
> - "Delete IP" deletes the build files associated with this IP as well as removes its instance
> ### Which part of the …
=> [GEMINIEDA-417] Add Remove and Delete IP options to source tree ip instances

src/IpConfigurator/IpConfigWidget.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: existing issue, altho don't think it was captured in a jira
> Currently the IpConfigWidget displays it's dynamically generated parameters in a basic widget which can't shrink any smaller. As a result, an ip w/ many parameters can force the widget to take up too much space.
> 
>
> The fields of the IpConfigWidget have been added to a QScrollArea which allows the parent dock window to scale down the QScrollarea while still rendering the windows at …
=> Make IpConfigWidget Scrollable

src/Compiler/TaskManager.cpp
> - [x] **Bitstream Clean does not clean the green status**
- Timing Analysis
- Power
- Bit Stream
Clean buttons of following above do not clean the green status. Now they are fixed and they clean green status.
Testing Step
- Create new project in foedag
- Press Start button and wait untill all design compilation is completed.
- Press clean button of the mentioned options above. 
- Check that green status of that option  cleans.
Added the functionality of clean button of the above mentioned options.
> 
> - [x] Library: <Specify the library name>
> - [ ] …
=> [RG-125] Clean button fixed for bitsream,power and timing Anaylsis

src/NewProject/project_type_form.cpp
Hide Post Synth flow from project type since it is not ready jet.
=> [RG-126] Hide post synth flow since it is not ready yet

src/IpConfigurator/IpConfigWidget.cpp, src/IpConfigurator/IpConfigWidget.h, src/Main/ProjectFile/ProjectManagerComponent.cpp, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/NewProject/CMakeLists.txt, src/NewProject/ProjectManager/ip_configuration.cpp, src/NewProject/ProjectManager/ip_configuration.h, src/NewProject/ProjectManager/project.cpp, src/NewProject/ProjectManager/project.h, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h
> - [x] To address an existing issue. If so, please provide a link to the issue: [RG-127]
> IP instances listed in the source tree would persist after a project change because the instances are still tracked by the IpGenerator class after a project change.
>
> - Added logic to reset the ip instances on project close/change
> - This also makes initial changes to the project system to allow for tracking of IP information. This will be used in later feature updates.
> 
> - [x] …
=> [RG-127] IP project settings changes, reset ip instances tree on project change

src/Main/ProjectFile/ProjectManagerComponent.cpp
These changes are needed to be able to fix RG-114 and store design files with relative paths in project file.
Hardcoded string '$OSRCDIR' is recognized in the code as the path to the project folder : (.../Raptor/examples/sasc_testcase/)
It wasn't considered when desirializing design files though: file paths were passed to the project manager as they are. Now we replace '$OSRCDIR' with the project path. The code is backward compatible as won't replace anything if there is no such string used.
>
Now design files can be stored with relative paths in the project file.
On a screenshot below all "File Path" lines were already supported. Current change extends it for "Group ..." …
=> [RG-114] Handle local relative paths for design files

src/IPGenerate/IPCatalogBuilder.cpp, tests/TestBatch/test_ip_generate.tcl
> - [x] To address an existing issue. If so, please provide a link to the issue: [RG-124]
> A dummy IP called MOCK_IP was always added to the catalog when loading the IP system
>
> The code to create MOCK_IP has been removed from build catalog code
> 
> - [x] Library: IPGenerate
> - [ ] Engine
> - [ ] Require a …
=> [RG-124] Remove MOCK_IP from IP Catalog builder

src/IPGenerate/IPCatalogBuilder.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-459]
> Original ip builder code had print statements reported when IPs were found/loaded and added
>
> - "IP Catalog, Adding IP: ..." messages have been removed
> - "IP Catalog, found IP Compiler: ..." messages have been removed
> - 1 summary message, "IP Catalog, found X IPs", has been added
> 
> - [ ] Library: IPGenerate
> - [ ] Engine
> - [ …
=> [GEMINIEDA-459] Removing IP builder "Adding" and "Found" messages

src/Compiler/CompilerOpenFPGA.cpp
Fix for bitstream generation caused by wrong path to generated files.
=> [GEMINIEDA-463] Fixed bitstream generation

src/MainWindow/main_window.cpp
Given PR aims to fix RG-135 issue, which occurs at times while evaluating the project,
According to previous implementation, Stop action was only enabled when both, the console and the task manager, are in progress. Due to multiple status changes within the project compilation, sometimes console was no longer running while task manager still had in progress status. 
>
Stop button will be enabled whenever one of them is in progress. It makes sense anyway, as there is something we can stop.
=> [RG-135] Enable Stop button when either task manager or console is in progress

src/MainWindow/main_window.cpp
> - [ ] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-472]
> Checkmark is only managed when user interacts with the ip configurator action in the view menu
>
> Logic has been added to update the checkmark during project transitions
> 
> - [x] Library: MainWindow
> - [ ] Engine
> ### Testing
> - Manually …
=> [GEMINIEDA-472] Update view checkmark logic for Ip Configurator

src/NewProject/device_planner_form.cpp, src/NewProject/device_planner_form.h
Make device selection always visible.
User must see what actual device will be selected. So, there is always be selection of one of the device.
=> [GEMINIEDA-464] Make device selection always visible

src/Compiler/Compiler.cpp, src/Compiler/CompilerDefines.cpp, src/Compiler/CompilerOpenFPGA.cpp, src/Compiler/Task.cpp, src/Compiler/Task.h, src/Compiler/TaskManager.cpp, src/Compiler/TaskTableView.cpp, src/Compiler/TaskTableView.h, src/Main/Tasks.cpp, src/Main/Tasks.h
> - [x] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-461]
> - logs were output to the project dir w/ no ui interface besides Open File
> - Synthesis log was saved as <project_name>_synth.log
> - Packing, Placement, Routing, Timing Anaylsis, & Power Analysis task all logged into vpr_stdout.log
>
> ### What does this pull request change?
> - Task view context menu now has a "View <task> Log" option in the context menu
> - Logic has been added to disable the view log option if a log file doesn't exist
> - In Foedag
>   - all tasks …
=> [GEMINIEDA-461] Adding View Log option to task view context menu

src/NewProject/new_project_dialog.cpp, src/NewProject/new_project_dialog.h
> - [x] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-471]
> Error conditions were intentionally ignored
>
> We now check Compile Unit groups to ensure that each file has the same language type and alert the user with a message box if not:
> 
> - [x] Library: NewProject
> - [ ] Engine
> ### Testing
> - …
=> [GEMINIEDA-471] Add language mismatch check for compile units in new project / project settings

src/IPGenerate/IPGenerator.cpp, src/IpConfigurator/IpCatalogTree.h, src/IpConfigurator/IpConfigWidget.cpp, src/IpConfigurator/IpConfigWidget.h, src/IpConfigurator/IpConfigurator.cpp, src/IpConfigurator/IpConfigurator.h, src/Main/ProjectFile/ProjectManagerComponent.cpp, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/NewProject/ProjectManager/ip_configuration.cpp, src/NewProject/ProjectManager/ip_configuration.h, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h
> - [x] To address an existing issue. If so, please provide a link to the issue: [GEMINIEDA-480]
> Saving IP Instances was planned for december release and hadn't been written
>
> IP Instance config commands are now stored in the project so they can be re-configured at load time
> 
> - [x] Library: IpConfigurator, Main, MainWindow, NewProject
> - [ ] Engine
> - [ ] Continous Integration …
=> [GEMINIEDA-480] Save IP Instance info to project file

src/Compiler/CompilerOpenFPGA.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: [RG-100]
> - Per comments in [GEMINIEDA-392], "--gen_post_synthesis_netlist on" was originally on by default, but got removed at some point
>
> - "--gen_post_synthesis_netlist on" has been added to CompilerOpenFPGA::Route()'s VPR command
> 
> - [x] Library: Compiler
> - [ ] Engine
> - [ ] Continous …
=> [RG-100] Add "--gen_post_synthesis_netlist on" to Route VPR command

.github/workflows/main.yml
> - [x] macos-gcc target started failing after mac latest updated
>   - Mac 12 removed gcc9
> - Updates macos-gcc target to use gcc-11
> - Downgrades mac CLT to 13.4.1 to avoid a known linker assertion https://github.com/actions/runner-images/issues/6350
> 
> - [ ] Engine
> - [x] Continous Integration (CI) scripts
=> update macos-gcc to gcc-11

.github/workflows/main.yml, src/IpConfigurator/IpConfigurator.cpp, src/MainWindow/main_window.cpp
> - [x] Fix regression in gui caused by https://github.com/os-fpga/FOEDAG/pull/745
> showPrompt() was called on the console after a project load to fix the console if any errors printed when executing tcl w/ GlobalSession->TclInterp()->evalCmd(), but if there were no errors, the the console printed two prompts indicators:
>
> Switched to GlobalSession->CmdStack()->push_and_exec() which doesn't break the console on error and removed the …
=> Fix extra # in console prompt when opening a project

Makefile, src/Compiler/Compiler.cpp, src/Compiler/CompilerOpenFPGA.cpp, src/Main/CommandLine.cpp, src/Main/CommandLine.h, src/MainWindow/Session.cpp, src/MainWindow/TopLevelInterface.h, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, tests/TestGui/open_project_test/open_project.tcl, tests/TestGui/open_project_test/test.ospr, tests/TestGui/open_project_test/test.srcs/sources_1/bottom.v, tests/TestGui/open_project_test/test.srcs/sources_1/test.v
This PR fulfills RG-138 and introduces new '--project' cmdline option.
Command line arguments parsing has been extended with '--project' option. In case it's used together with '--script', an error is given and startup fails.
>
'--project' allows setting a project file (*.ospr) in the cmdline and corresponding gets opened after startup. As if the application was started without any cmdline options and Open Project action for indicated project was executed.
Tested on FOEDAG and Raptor:
> 
> - [ ] Engine
> - [+] Documentation
> - [ ] …
=> [RG-138] Introduce --project cmdline option to open a project directly at startup

src/PinAssignment/PinAssignmentCreator.cpp
* Fixed problem with SDC file parsing when there are additional spaces.
* Fixed order issue. First need parse location and then mode.
=> [EDA-213] Fixed loading sdc to pin planner when sdc has some useless spaces

src/IPGenerate/IPGenerator.cpp, src/IPGenerate/IPGenerator.h
> - [x] Fixing an oversite in previous implementation
> - When deleting an ip from the UI w/ r-click > Delete IP, the ip build files were removed, but the cached .json file wasn't which would result in a failure to generate the actual ip files the next time someone tried to generate that IP again.
>
> - Abstracted the logic for determining the cached json path
> - Added logic to delete the cached json file when an IP is requested to be …
=> Add logic to delete cached json when deleting ip

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/PinAssignment/PinAssignmentCreator.cpp, src/PinAssignment/PinAssignmentCreator.h
Improve usability. Show better indication for pin planner modification.
=> [RG-158] Add star to the tab name of pin planner views when modified by user.

src/TextEditor/editor.cpp, src/TextEditor/editor.h, src/TextEditor/text_editor_form.cpp, src/TextEditor/text_editor_form.h
Update files opened in editor, when they changed on disk. If file is in modified state - ask user if need to reload.
=> [RG-154] Add file tracking for files opened in editor

src/MainWindow/main_window.cpp, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h, src/NewProject/create_file_dialog.cpp, src/NewProject/new_project_dialog.cpp, src/NewProject/new_project_dialog.h, src/NewProject/source_grid.cpp, src/NewProject/source_grid.h, src/PinAssignment/PinAssignmentCreator.cpp, src/PinAssignment/PinAssignmentCreator.h, src/PinAssignment/Test/PinAssignment_main.cpp, src/ProjNavigator/tcl_command_integration.cpp, tests/unittest/PinAssignment/PinAssignmentCreator_test.cpp
Add support for constraint *.pin file. Pin planner now works only with this file.
Only one *.pin file supported
=> [RG-156] Add support *.pin constraint file for pin planner

src/Compiler/CompilerDefines.cpp, src/Utils/QtUtils.cpp, src/Utils/QtUtils.h, tests/unittest/CMakeLists.txt, tests/unittest/Compiler/CompilerDefines_test.cpp, tests/unittest/Utils/QtUtils_test.cpp
When user add files we detect wrong file type in case file extension is in upper case.
=> Fixed wrong file type when file extension is in upper case

src/Main/Tasks.cpp, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/PinAssignment/PackagePinsView.cpp, src/PinAssignment/PackagePinsView.h, src/PinAssignment/PinAssignmentCreator.cpp, src/PinAssignment/PinAssignmentCreator.h, src/PinAssignment/PortsView.cpp, src/PinAssignment/PortsView.h, src/PinAssignment/Test/PinAssignment_main.cpp, src/TextEditor/text_editor.cpp, src/TextEditor/text_editor.h, src/TextEditor/text_editor_form.cpp, src/TextEditor/text_editor_form.h, src/Utils/QtUtils.h, tests/unittest/Utils/QtUtils_test.cpp
Allow user refresh pin planner in case *.pin constraint file was changed on disk or by user or some other app.
=> [RG-159] Allow refresh pin planner tables after *.pin file was changed on the disk

src/Compiler/Compiler.cpp, src/Compiler/Compiler.h, src/Compiler/CompilerOpenFPGA.cpp, src/ProjNavigator/tcl_command_integration.cpp, src/ProjNavigator/tcl_command_integration.h
Allow user create different design flows with tcl command
create_design tcl command accept one more argument: -type: rtl, post-synth
=> [RG-187] Add project type for create_design tcl command

src/Compiler/CompilerDefines.h, src/Compiler/TaskManager.cpp, src/Compiler/TaskModel.cpp, src/Compiler/TaskTableView.cpp
Move simulation buttons on top of the Task table.
=> [RG-208] Move simulation button on top of the task table

src/Compiler/TaskManager.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-222
> - Bitstream task didn't have an abbreviation set
>
> - Bitstream task now has it's abbreviation set to "BIT"
> 
> - [x] Library: Compiler
=> [RG-222] Set bitstream abbreviation

src/Main/ProjectFile/ProjectManagerComponent.cpp, src/Main/ProjectFile/TaskManagerComponent.cpp, src/NewProject/ProjectManager/project.cpp, src/NewProject/ProjectManager/project.h, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h, src/NewProject/add_source_form.cpp, src/NewProject/add_source_form.h, src/NewProject/new_project_dialog.cpp, src/NewProject/new_project_dialog.h, src/NewProject/source_grid.cpp, src/NewProject/source_grid.h, src/ProjNavigator/tcl_command_integration.cpp, src/Simulation/Simulator.cpp, src/Simulation/Simulator.h
Add top module name for simulation and all other option as Design source page have.
Simulation top module was moved from Simulation (`Simulator::SetSimulationTop`) to Project manager (`ProjectManager::setTopModuleSim`)
This change required because now simulation top module could be set from tcl command and GUI.
=> [RG-227] Add simulation options to Project settings

tests/TestGui/gtkwave_invoke.tcl, third_party/gtkwave_cmake/CMakeLists.txt
> - This will simplify other clients accessing gtkwave
> - The GTKWave archive was downloaded to a path that had a different name in windows
>
> - Both windows and unix archives are now downloaded to the same location so that other client CMake files don't have to determine where the file will be found based on platform.
> 
> - [x] Library: GTKWave
> - [ ] Engine
=> GTKWave: Set download location to a fixed location

third_party/gtkwave_cmake/CMakeLists.txt
This fixes a typo in https://github.com/os-fpga/FOEDAG/pull/873 which accidentally saves the file under gtkwave**Tcl**.tar.gz instead of gtkwave**TCL**.tar.gz which is what other clients are looking for.
=> GTKWave:: Fix typo in archive name

src/Compiler/CompilerDefines.cpp, src/Compiler/CompilerDefines.h, src/Compiler/TaskModel.h, src/Compiler/TaskTableView.cpp, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
Make Enable/Disable option available for simulation tasks only.
For post synth project hide all tasks above Simulate Gate.
RTL project:
Post synth project:
=> [RG-239] Update task table: Enable/Disable for simulation tasks only, hide some tasks for post synth project

Makefile, src/Compiler/Compiler.cpp, src/Compiler/CompilerOpenFPGA.cpp, src/Simulation/Simulator.cpp, src/Simulation/Simulator.h, tests/TestGui/simulation_flow.tcl
Add one more argument for simulation_options tcl command - level: 
`simulation_options <simulator> <task> ?<level>? <options>`
level values could be rtl, gate, pnr.
level is optional. If level not specify, options will be applied to all levels.
Also `bool Compiler::RegisterCommands(TclInterpreter* interp, bool batchMode)` function changed. Now it will register simulation commands without any conditions.
=> RG-234: Add one more optional parameter to simulation_options - level.

src/Main/CMakeLists.txt, src/MainWindow/PathEdit.cpp, src/MainWindow/PathEdit.h, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/NewProject/location_form.cpp, src/NewProject/location_form.h, src/NewProject/new_project_dialog.cpp, src/NewProject/new_project_dialog.h
Menu File->Preferences extended with Default project path:
Dialog allow to select path. This path then will be used when create new project:
This setting is persistent.
`PathEdit` new class that encapsulate QTextEdit with button and QFileDialog.
=> [RG-203] Allow user to change default project folder

src/Compiler/Compiler.cpp, src/Compiler/Compiler.h
New mehod `HasInternalError` verify if pointer `m_tclCmdIntegration` not null. Normally it should never happened. 
Fail tcl command with message "Internal: tcl command integration does not initialized".
=> [RG-164] Cleanup code for compiler class

src/Compiler/CompilerDefines.cpp, src/Compiler/CompilerDefines.h, src/NewProject/source_grid.cpp, tests/unittest/Compiler/CompilerDefines_test.cpp
For post synth project type we detect file *.v as **netlist** verilog. But not verilog.
The root cause of issue we have detected wrong file language:
=> [RG-256] Add auto detect of netlist verilog by file extention for post synth project type

etc/settings/settings_test.json, src/Compiler/Compiler.cpp, src/Main/Tasks.cpp, src/Main/Tasks.h, src/Main/WidgetFactory.cpp, src/Simulation/Simulator.cpp, src/Simulation/Simulator.h, tests/unittest/CMakeLists.txt, tests/unittest/Simulation/Simulation_test.cpp, tests/unittest/Utils/StringUtils_test.cpp
New settings added for simulation rtl/gate/pnr/bitstream:
Settings json file extended with new settings for all simulation types.
Added few conversion functions (like `ToSimulatorType` or `ToString`) to avoid code duplication.
Added integration task settings into `simulate` command. 
Changes in `src/Main/Tasks.cpp` are need for save/load data to/from settings widget.
[RG-234]: https://rapidsilicon.atlassian.net/browse/RG-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [RG-234] Simulation settings: simulator, options

Makefile, src/Compiler/Compiler.cpp, src/Compiler/CompilerOpenFPGA.cpp, src/ProjNavigator/tcl_command_integration.cpp, src/ProjNavigator/tcl_command_integration.h, tests/Testcases/simulation_trivial/sim_main.cpp, tests/Testcases/simulation_trivial/test.tcl, tests/Testcases/simulation_trivial/test.v
New Tcl command has been added: clear_simulation_files. 
This command remove all files that was added as simulation. When GUI mode is used, hierarchy view is updated after files removed.
Tcl test has been added.
=> [RG-258] Add tcl command: clear_simulation_files

src/Compiler/Compiler.cpp, src/Compiler/Compiler.h, src/Console/TclErrorParser.cpp, src/TextEditor/editor.cpp
We analyze log file after every compilation step. In case some error (here is the regexp: `"Error [0-9].*:"`) we put a link into the console. This link is open log file and show exact line with error.
Text editor was fixed. Now method `Editor::markLine` ensures that marked line is visible.
For the `TclErrorParser::handleLine` fixed clazy warning.
=> [RG-262] Add hyperlink to last known error message from a task pointing to a rpt file

src/Main/Settings.cpp, src/Main/Tasks.cpp, src/Main/WidgetFactory.cpp, src/Main/WidgetFactory.h
If the settings value contains some characters like space or dash e.g:
This setting lost when project loads.
=> [RG-253] Fixed issue with loading settings, when arg value has special chars like space or dash

src/MainWindow/MessagesTabWidget.cpp, src/MainWindow/main_window.cpp
Generate messages after each compiler task done.
Update for  `MessagesTabWidget` fixes issue with generating messages event when no log file.
=> [RG-290] Show messages after each task while using the play button.

src/NewProject/new_project_dialog.cpp
`ui->m_tabWidget->clear();` doesn't free memory for the widgets so it is user responsibility. 
`m_locationForm` and `m_proTypeForm` become nullptr in case Project settings so need to provide check if this objects are valid.
=> [RG-110] Fixed memory leaks in newProjectDialog

src/Compiler/Compiler.cpp, src/Compiler/Compiler.h, src/Compiler/CompilerOpenFPGA.cpp, src/Compiler/CompilerOpenFPGA.h, src/MainWindow/main_window.cpp, src/PinAssignment/PinAssignmentCreator.cpp, src/PinAssignment/PinAssignmentCreator.h, src/PinAssignment/Test/PinAssignment_main.cpp
Search pin table data in device.xml file.
`m_OpenFpgaPinMapCSV` was renamed and moved to Compiler since this is related to common data but not only openfpga
[EDA-1155]: https://rapidsilicon.atlassian.net/browse/EDA-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [EDA-1155] Change search path for *.csv file pin planner. Now it searches in device.xml

src/Compiler/CompilerOpenFPGA.cpp
Repack command (set_clock_pin) needs to be available prior to the pin table being correct.
Reworked the flow logic.
Also made the set_clock_pin create a change of constraint for the incremental flow.
=> repack xml available even if pin table not ready

src/IPGenerate/IPCatalog.h, src/IPGenerate/IPGenerator.cpp, src/ProjNavigator/sources_form.cpp
New flag `m_generated` for ip instance set to true when user generates the IP. Show only generated IPs in the hierarchy view.
=> [RG-358] avoid generation of multiple IPs

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
New option allow to skip message about exit program:
No this message when unchecked:
=> [RG-365] Add one more option to preferences: Show message on exit program

src/Main/CMakeLists.txt, src/MainWindow/EditorSettings.cpp, src/MainWindow/EditorSettings.h, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/ProjNavigator/Test/projnavigator_main.cpp, src/ProjNavigator/sources_form.cpp, src/ProjNavigator/sources_form.h, src/Utils/FileUtils.cpp, src/Utils/FileUtils.h
Allow user select few 3rd party editors:
Than open project files:
=> [RG-380] Added 3rd party editors support for project file edit

Makefile, src/Simulation/Simulator.cpp, tests/TestBatch/test_simulation_options.tcl
Added more informative message when `simulation_options` command got failed.
Covered by tcl test.
=> [EDA-1567] simulation options wrong arg

src/Compiler/Compiler.cpp
Fixed `simulate` command. Use default waveform file name when user didn't specify it.
=> [EDA-1607] Fixed simulate args issue with waveform file name

src/Compiler/Compiler.cpp, src/Compiler/Compiler.h, src/Compiler/Task.cpp, src/Compiler/Task.h, src/Compiler/TaskManager.cpp, src/Compiler/TaskManager.h, src/Main/CMakeLists.txt, src/MainWindow/PerfomanceTracker.cpp, src/MainWindow/PerfomanceTracker.h, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/Simulation/Simulator.cpp, tests/unittest/CMakeLists.txt, tests/unittest/MainWindow/PerfomanceTracker_test.cpp
Add new feature - Compute Usage:
Result is available only after task successfully done.
Result is N/A in case:
* Task was cleaned
* Task was skipped because of no design change.
* Project was opened.
For simulation task:
* Duration is a sum of three (elaboration, compile and simulate)
* Utilization is maximum of three  (elaboration, compile and simulate)
=> [EDA-957] Initial implementation of Compute Usage  table which shows task duration and memory utilization

src/MainWindow/main_window.cpp
Fixed failed analyze when user stop compile:
=> [RG-456] Fixed analyze command failed when user stop compilation

src/MainWindow/main_window.cpp
Reverts os-fpga/FOEDAG#1210 due to a new bug discovery while testing.
=> Revert "[RG-461] Fixed crash when exit while compilation is in progress"

src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
Fixed two issue when exit from foedag while compilation in progress:
* Crash
* running process after close for script mode
Implementation makes sure that compilation process has finished and only after that close the application.
=> [RG-461] [RG-463] Fixed crash when exit while compilation is in progress

CMakeLists.txt, src/MainWindow/main_window.cpp, src/PinAssignment/PinAssignmentCreator.cpp, src/PinAssignment/PinAssignmentCreator.h
Fixed wrong path to ports file. Additionally, add warning message if ports loading fails.
=> [EDA-1876] Fixed missing ports in pin planner

CMakeLists.txt, src/Main/ProjectFile/ProjectFileComponent.cpp, src/Main/ProjectFile/ProjectFileComponent.h, tests/unittest/MainWindow/ProjectFileComponent_test.cpp
Fixed logical mistake in `operator<` for Version class. 
All cases covered by unit tests.
=> Fixed version comparison

CMakeLists.txt, src/Command/CommandStack.cpp, src/Command/CommandStack.h, src/Main/Foedag.cpp
When `--mute` option is used, logs will write to the log file. Standard output still remains muted.
=> [EDA-1938] Enable write logs to file when --mute option set

CMakeLists.txt, src/DeviceModeling/device_net.h, src/DeviceModeling/rs_parameter.h, src/DeviceModeling/rs_parameter_type.h, tests/unittest/CMakeLists.txt, tests/unittest/DeviceModeling/device_net_test.cpp, tests/unittest/DeviceModeling/rs_parameter_test.cpp
> - [x ] To add new Gtests to Device Modeling, testing and fixing rs type names generation
> 
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
=> Add Gtests for nets and parameters and fix rs type name generation (across platforms)

CMakeLists.txt, src/Compiler/Compiler.cpp, src/Compiler/Compiler.h, src/Configuration/CFGCommon/CFGCommon.cpp, src/Configuration/CFGCommon/CFGCommon.h, src/Configuration/CFGCompiler/CFGCompiler.cpp, tests/unittest/CFGCommon/CFGArg_test.cpp, tests/unittest/CFGCommon/CFGCommon_test.cpp, tests/unittest/CFGCompiler/CFGCompiler_test.cpp
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
>> Cosmetic changes
>> Prepare few paths that needed by OCLA Parser
> 
> - [x] Engine
> - [ ] …
=> Preparation for OCLA Parser

src/Compiler/TaskManager.cpp, src/Compiler/TaskManager.h, tests/unittest/CMakeLists.txt, tests/unittest/Compiler/TaskManager_test.cpp
In case user execute Clean for simulation, remove files for simulation only but not the downstream steps.
=> [EDA-1199] When user run 'Clean' simulation action, perform clean step for simulation only.

CMakeLists.txt, src/Compiler/TaskManager.cpp, src/Compiler/TaskManager.h, src/Compiler/TaskTableView.cpp, src/Compiler/TaskTableView.h
Update message for clean simulation task:
Disable `View waveform` action when waveform file doesn't available.
=> [RG-469] Clean for simulation needs a separate message and disabling of some context items

CMakeLists.txt, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
When user press `Reconfigure IP` action from context menu open ip configuration dialog.
=> Open IP configuration when user select IP Reconfiguration action from context menu

.clang-tidy
Turn off -readability-identifier-length check since to many warnings in every file and some of them comes from Qt and some is expected like `i` in for loop, `ok` as bool flag, `ec` for error code and many other.
=> Turn off -readability-identifier-length check

CMakeLists.txt, src/Configuration/CFGCommon/CFGArg.json, tests/unittest/CFGCommon/CFGArg_test.cpp
- Added -v flag to indicate verbose output for `list_cable` and `list_device` tcl commands
- -v flag is optional. Default value false.
The implementation of the programmer tcl commands `list_cable` and `list_device` output is coming on next PR if this proposal works for everyone.
Example of list_cable output 
```
% programmer list_cable -v
INFO: Cable           
INFO: -----------------
INFO: (1) RsFtdi_1_1
INFO: (2) RsFtdi_1_2
RsFtdi_1_1 RsFtdi_1_2
% programmer list_cableRs
Ftdi_1_1 RsFtdi_1_2      <------------ these are space separated tcl …
```
=> Add verbose flag for list_cable and list_device

CMakeLists.txt, src/Simulation/Simulator.cpp
> - [X] To address an existing issue. If so, please provide a link to the issue: EDA-2030
> Update supported languages for GHDL without verific parser.
> VHDL_2019 language is illegal in GHDL simulation type
> 
> - [X] Library: simulation
> - [ ] Engine
> - [ ] Continuous Integration (CI) scripts
> - [ ] …
=> [EDA-2030] VHDL_2019 is not supported for GHDL simulation without Verific parser

CMakeLists.txt, src/MainWindow/main_window.cpp
Fixed generate IP after compilation was canceled:
This is fixed:
=> [RG-468] Fixed generating IP after stop compilation press.

CMakeLists.txt, src/Utils/StringUtils.h, tests/unittest/Utils/StringUtils_test.cpp
This function provides an easy way to concatenate strings. For example:
```
std::string formatstr{"hello %"};
formatstr = StringUtils::format(formatstr, "world");
EXPECT_EQ(formatstr, std::string{"hello world"});
```
This function can be replaced with similar function from the C++20
=> Add 'format' function that gives a nice way to concatenate strings

CMakeLists.txt, src/Compiler/CompilerOpenFPGA.cpp
This allows pin_c and bitstream generation to work when Raptor uses VHDL input
=> raptor: use eblif for vhdl flow

CMakeLists.txt, src/Compiler/Compiler.cpp, src/Compiler/Compiler.h, src/Compiler/CompilerDefines.cpp, src/Compiler/CompilerDefines.h, src/Compiler/CompilerOpenFPGA.cpp, src/Simulation/Simulator.cpp
> - [x] To address an existing issue. If so, please provide a link to the issue: EDA-2024, EDA-2007
> Initially, we looked at using try catch to capture the exceptions raised, https://github.com/os-fpga/FOEDAG/tree/handle-errors
> Upon discussion with wider team, we decided to add a new error state for the compiler which stores that last known error (user friendly)
> Adds error state to compiler which stores both the error number and corresponding error message.
> 
> - [x] …
=> [EDA-2024] [EDA-2007] Compiler error handling last error

CMakeLists.txt, src/IpConfigurator/IPDialogBox.cpp, src/IpConfigurator/IPDialogBox.h, src/IpConfigurator/IPDialogBox.ui
Fixed layout for IPs:
Fixed default button, when user press Enter. Now, no action for Enter.
=> [EDA-2121] Fixed IP window layout

CMakeLists.txt, src/Configuration/CFGCommon/CFGCommon.h, src/Configuration/CFGCompiler/CFGCompiler.cpp, src/Configuration/Programmer/Programmer.cpp
Added tcl status returned to programmer fpga_config, flash and otp command execution. It returns TCL_ERROR whenever the programming failed.
Whenever TCL_ERROR return from fpga_config, flash or otp command, the Programmer GUI will stop the subsequent programming task
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [x] Library: Programmer
> - [ ] Engine
> …
=> Programmer fpga_config, flash and OTP tcl return

CMakeLists.txt, src/NewProject/source_grid.cpp
Added missing VHDL 2019 and EDIF languages for the drop down selection.
=> Added VHDL 2019 and EDIF languages in the drop box menu of Project settings

CMakeLists.txt, src/ProjNavigator/sources_form.cpp
`Target` marker has been removed from constraint file in the gui. FOEDAG does not support multiple constraints so it doesn't make any sense and can confuse uses.
=> Remove Target marker for constraint file since foedag deosn't support multiple constraint files

CMakeLists.txt, src/Configuration/CFGCommon/CFGCommon.cpp, src/Configuration/CFGCommon/CFGCommon.h
This PR enhance the cfg assert msg printing format and also added a common function CFG_sleep_ms() for Configuration applications.
Below:
After:
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [X] Library: CFGCommon
> - [ ] Engine
> …
=> Enhance cfg assert msg printing format

CMakeLists.txt, etc/help.txt, etc/settings/settings_test.json, src/Compiler/Compiler.h, src/Compiler/CompilerOpenFPGA.cpp
> - [X] To address an existing issue. If so, please provide a link to the issue: EDA-2103
> Added EBLIF as lang for PnR netlist in both synthesis and packing UI task settings
> Help updated.
> Adds new PnR netlist lang, EBLIF
> Default netlist lang will still be verilog unless specified.
> 
> - [X] Library: Compiler, CompilerOpenFPGA
> - [ ] Plug-in:
> - [ ] Engine
> - [X] Documentation
> - [ ] Continuous Integration (CI) scripts
> ### Impact of the …
=> [EDA-2103] Add EBLIF to PnR netlist language setting for synthesis and placement task

CMakeLists.txt, src/Compiler/CompilerOpenFPGA.cpp
Only files with matching modules or primitives names are parsed with -y
=> filter -y files

CMakeLists.txt, src/MainWindow/Session.cpp
We do not run project when `--project` switch is used.
=> [RG-486] When --project switch is used, open specified project but do not start compilation

CMakeLists.txt, src/IPGenerate/IPGenerator.cpp, src/IpConfigurator/IPDialogBox.cpp
* Fixed Simulate IP when module name changed
* Validate module name with regex `^[a-zA-Z0-9_]*$`
=> [RG-488] Fixed Simulate IP when module name changed and add module name validation

CMakeLists.txt, src/Main/TclSimpleParser.cpp
Fixed command count for tcl script. 
This count reflect here:
=> Fixed tcl simple parser to calculate commands correct

CMakeLists.txt, src/Configuration/Programmer/CMakeLists.txt, src/Configuration/Programmer/Programmer.cpp, tests/TestInstall/CMakeLists.txt, tests/unittest/CMakeLists.txt
> - [x] To address an existing issue. If so, please provide a link to the issue: EDA-2021
The programmer tool depends on libusb library dynamically. The solution is to copy the libusb.dll to be side by side with the binary
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> ### Impact of the pull …
=> [EDA-2021] Fix MSVC build for Programmer tool 

CMakeLists.txt, etc/help.txt, etc/settings/settings_test.json, src/Compiler/Compiler.cpp, src/Main/Tasks.cpp, src/NewProject/add_constraints_form.ui, src/ProjNavigator/add_file_form.ui
Update Pin Location Assign Method:
=> Update Pin Location Assign Method, replace `free` with `pin_constraint_disabled`

CMakeLists.txt, src/Compiler/TaskTableView.cpp
Fixed context menu issue on CentOS, when user was not able to click on three dots.
=> Fixed three dot area context menu for Task table

CMakeLists.txt, src/IpConfigurator/IPDialogBox.cpp, src/IpConfigurator/IPDialogBox.h
Fixed issue with Generate IP button. Now when any error occurred, Configure IP window remains until user cancel it or fix wrong parameter.
=> Fixed Generate IP behavior when some error occured

CMakeLists.txt, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h, src/ProjNavigator/add_file_dialog.cpp, src/ProjNavigator/tcl_command_integration.cpp, src/ProjNavigator/tcl_command_integration.h, tests/unittest/NewProject/ProjectManager_test.cpp
Refactoring code to avoid copy/pase from: 
* ProjectManager::setSimulationFiles
* ProjectManager::setDesignFiles
=> [RG-305] Remove copy/paste code from ProjectManager::setSimulationFiles, ProjectManager::setDesignFiles

CMakeLists.txt, src/Configuration/CMakeLists.txt
Explicitly use add_dependencies() to make sure cfgcommon is compiled first within configuration subsystem
target_link_libraries() is used before this, and I have impression that with target_link_libraries, CMAKE should figure the dependency since if you need to link to a library, that library (or target) should have been compiled first. 
>
> 
makefile change
> 
> - [ ] Library: <Specify …
=> Explicitly use add_dependencies() for dependency

CMakeLists.txt, src/Command/Command.h, src/Command/CommandStack.h, src/Command/Logger.h, src/Compiler/Compiler.cpp, src/Compiler/CompilerDefines.cpp, src/Compiler/CompilerOpenFPGA.h, src/Compiler/Task.h, src/Compiler/TaskGlobal.h, src/Compiler/TaskManager.cpp, src/Compiler/TaskTableView.cpp, src/Compiler/TaskTableView.h, src/Main/CommandLine.h, src/MainWindow/main_window.cpp, src/NewProject/Main/registerNewProjectCommands.h, src/Tcl/TclInterpreter.h, tests/unittest/Compiler/TaskManager_test.cpp
Fixed MACOS build issue.
This PR fixes few different build issues:
* `#include <QtWidgets>` causes build fail
* Override virtual slot TaskTableView::dataChanged. This causes link error. 
This issue also present on Linux but for some reason does not cause link error. Command for detect problem:
```
find dbuild/ -name mocs_compilation.cpp.o | xargs -n 1 -I % sh -c 'objdump -x % | grep registerConverterFunction'
```
Error output:
````
0000000000000000         *UND*	0000000000000000 _ZN9QMetaType27unregisterConverterFunctionES_S_
0000000000000000         *UND*	0000000000000000 _ZN9QMetaType25registerConverterFunctionERKSt8functionIFbPKvPvEES_S_
0000000000000023 R_X86_64_PLT32    _ZN9QMetaType27unregisterConverterFunctionES_S_-0x0000000000000004
0000000000000045 R_X86_64_PLT32 …
```
=> Macos qt6 issue

CMakeLists.txt, src/Main/Foedag.cpp, src/Main/Settings.cpp, src/Main/Settings.h, src/Main/Tasks.cpp, src/Main/Tasks.h, src/Main/WidgetFactory.cpp, src/Main/WidgetFactory.h, src/MainWindow/Session.cpp, src/Utils/ArgumentsMap.cpp, src/Utils/ArgumentsMap.h, src/Utils/CMakeLists.txt, src/Utils/sequential_map.h, tests/unittest/CMakeLists.txt, tests/unittest/Settings/CompilerSettings_test.cpp, tests/unittest/Settings/Settings_test.cpp, tests/unittest/Settings/settings_test.json, tests/unittest/Utils/ArgumentsMap_test.cpp, tests/unittest/Utils/sequential_map_test.cpp, tests/unittest/resources.qrc
Key changes is class `ArgumentsMap`. It replaces std::string and used for parsing arguments for gui settings. 
Every `TclArgs_get/get<setting>Options` doesn't have to parse argument string. It happens on other level.
=> [RG-249] settings improvement

src/Compiler/Compiler.cpp, src/Compiler/Compiler.h, src/Compiler/CompilerDefines.h, src/Compiler/CompilerOpenFPGA.cpp, src/Compiler/TaskManager.cpp
Implement new tcl command `compile2bits`. This command performs this actions in one shot:
* packing
* placement
* routing
* timing
* bitstream
Also new action available in Bitstream context menu:
=> [EDA-2345] Add compile2bits tcl command

CMakeLists.txt, src/Compiler/Compiler.cpp, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h, src/ProjNavigator/add_file_dialog.cpp, src/ProjNavigator/tcl_command_integration.cpp, src/ProjNavigator/tcl_command_integration.h, src/Utils/QtUtils.cpp, src/Utils/QtUtils.h, tests/unittest/NewProject/ProjectManager_test.cpp
1. Use string list instead of conversion string to string list for design and simulation files. Before the change, files list was compiled into the string with space separator. Inside ProjectManager this string splits into list of strings. After changes, there is no string for files but only string list. 
2. Encapsulate conversion between `std::string` and `QString` inside `TclCommandIntegration` class. Provide interface with `std::string` only for compiler.
=> [RG-306] Code improvement to avoid conversion from string to string list for project mananger

CMakeLists.txt, src/Compiler/CompilerOpenFPGA.cpp
update for loading `device.xml`. Use relative path for `file` attribute.
=> [RG-497] Use relative path in device.xml

.github/workflows/install_centos_dependencies_build.sh, .github/workflows/main.yml, CMakeLists.txt
> - [ x] To address an existing issue. 
Adding Qt with OpenSSL enabled in CentOS 7 CI
> 
> - [ ] Engine
> - [ x] Continous Integration (CI) scripts
=> Update CentOS CI to use Qt with OpenSSL enabled

src/Simulation/Simulator.cpp
Change default compilation options for verilator simulator to `--main --timing --exe`. 
This change affects batch mode only.
=> [EDA-2005] Add default parameters for verilator simulation, batch mode

.github/workflows/main.yml
temporary disable macos test_install target
=> Temporary disable test_install target for macos due to build issue

.github/workflows/labeler.yml, CMakeLists.txt, third_party/monaco-editor/CMakeLists.txt
Move the Monaco Editor-related stuff to Monaco CMake and remove it from the main CMake. Use a more precise CMake variable to perform the copy and install action
=> Clean up cmake for monaco editor

.github/workflows/version.yml, third_party/monaco-editor/CMakeLists.txt
Remove the install section from Monaco Editor Cmake as it is no longer needed.
Move Monaco unzip content to an etc folder so that they get copied like others.
=> Monaco editor cmake clean up

src/MainWindow/MessagesTabWidget.cpp, src/TextEditor/editor.cpp, src/TextEditor/text_editor_form.cpp
Fixed selection line number for monaco editor.
In the `Messages` tab user can press on warnings or errors and they are opened in the editor.
=> Fixed line selection number in monaco editor

src/rapidgpt/RapigGptSettingsWindow.cpp, src/rapidgpt/RapigGptSettingsWindow.ui
Hide Remote server URL setting of RapidGPT
=> [EDA-2432] Hide Remote URL setting for rapiggpt

third_party/monaco-editor/monaco-editor.html
Fix Line Highlight Issues when opening file from console in monaco editor
The fileLoaded() call from JS occurs before the file is actually ready and rendered, and causes a miss of the highlight line (marker) signal emitted from Qt the first time.
Makes the monaco editor wait until the file is actually loaded using the OnDidChangeModel event from monaco, and switch to main JS context using setTimeout to call the fileLoaded() to Qt to inform that the editor is now ready and rendered.
Now, the signals …
=> Fix Line Highlight Issues

third_party/openssl_cmake/CMakeLists.txt
> - [x ] To address an existing issue. 
RapidGPT is facing a core dump and one possible cause is not providing the correct OpenSSL lib so copying the OpenSSL to the build/lib folder along with using a bash script as an invoker to set LD_LIBRARY_PATH to this library.
The bash script is in [PR # 1466](https://github.com/os-fpga/FOEDAG/pull/1466)
=> Copy lib ssl and crypto to build/lib folder to provide same lib across all system

Makefile, src/TextEditor/text_editor_form.cpp
https://bugreports.qt.io/browse/QTBUG-25789
This happens because TextEditorForm defined as  
Q_GLOBAL_STATIC(TextEditorForm, texteditor)
And when application is exit it try to destroy static member. But since TextEditorForm is a part of GUI, it’s already destroyed. Normally, this case should handled by Qt but in this case, it somehow related to QWebEngineView.
=> Fixed crash ralated to editor after application close

src/Compiler/Constraints.cpp
1. Full compilation test (tested at Raptor level) was broken due to https://github.com/os-fpga/FOEDAG/pull/1461. Specifically I remove the original code and completely rewrite set_property command, thinking it was not exercised by any code. https://github.com/os-fpga/FOEDAG/pull/1461/files#diff-3008f9added136f0dc9ac2353b1282c7ef81e626257d205932ff44545aa184e4L571-L583
2. Restoring back the original code
>
> 
> 
> 
> 
> 
> ### Which part …
=> Restore set_property original code

src/.foedagenv_lin64.sh, third_party/openssl_cmake/CMakeLists.txt
Place the OpenSSL libs in the build/lib/openssl folder so that at install time we can handle symbolic links easily.
=> Copy openssl libs in folder to handle symbolic links

src/Main/CommandLine.cpp
Fixed crash when `--device` argument is missing for command line
=> Fixed crash when no device specified

src/Compiler/Reports/AbstractReportManager.cpp, src/Compiler/Reports/AbstractReportManager.h, src/Compiler/Reports/SynthesisReportManager.cpp, src/Compiler/Reports/SynthesisReportManager.h
Update reports for BRAM and DSP:
* Change keywords for synthesis
* Hide DSP block 9x10 for non synthesis compilation steps.
* Show BRAM 18k for synthesis only
=> Update reports for BRAM and DSP

CMakeLists.txt, src/Compiler/Compiler.cpp, src/Compiler/CompilerOpenFPGA.cpp
Restore the Netlist compilation flow.
The new Netlist compilation flow looks like the following in a raptor.tcl project:
```
create_design AES_DECRYPT_GATE -type gate-level
target_device 1VG28
read_netlist aes_decrypt.v
add_constraint_file aes_decrypt_gate.sdc
analyze 
synthesize
packing
place
route
sta
power
bitstream
```
=> Restore the Netlist flow

src/Compiler/Compiler.h, src/Compiler/CompilerOpenFPGA.cpp, src/Compiler/CompilerOpenFPGA.h, src/Compiler/Constraints.cpp, src/Compiler/Constraints.h, src/DesignQuery/DesignQuery.cpp
Netlist editing requires that the timing constraints get name translation
=> SDC name translation

CMakeLists.txt, src/Simulation/Simulator.cpp
Now Verilator supports the relocation of binaries so no longer a need to set the VERILATOR_ROOT environment variable before invoking the verilator.
=> Commented the section of setting verilator root

etc/devices/custom_layout_template.xml, src/Compiler/CompilerOpenFPGA.cpp, src/Compiler/CompilerOpenFPGA.h, src/Main/Foedag.cpp, src/MainWindow/main_window.cpp, src/NewProject/CMakeLists.txt, src/NewProject/CustomLayout.cpp, src/NewProject/CustomLayout.h, src/NewProject/CustomLayout.ui, src/NewProject/CustomLayoutBuilder.cpp, src/NewProject/CustomLayoutBuilder.h, src/NewProject/ProjectManager/config.cpp, src/NewProject/ProjectManager/config.h, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/device_planner_form.cpp, src/NewProject/device_planner_form.h, src/NewProject/device_planner_form.ui
- Allow user create new device for existed:
- The custom_device.xml stores the new devices and is saved under the home directory (~/.raptor or ~/.foedag). 
- The template added is based of https://github.com/neulink-semi/Raptor/blob/a17ca1fd79c8b675b1bd4b85422ec57a4f5cd634/etc/devices/gemini_compact_62x44/gemini_vpr.xml#L2819
- It is stored under the implementation subfolder of the project and VPR will pick it up automatically if the corresponding device is selected.
- We will have to create templates for each device separately in future.
- Currently, we don't support deletion of devices from the GUI although it's possible to delete it manually from the file mentioned above.
=> Allow user to create custom device based off the existing ones

CMakeLists.txt, src/NewProject/CustomLayout.cpp, src/NewProject/CustomLayout.h, src/NewProject/CustomLayoutBuilder.cpp, src/NewProject/CustomLayoutBuilder.h, src/NewProject/device_planner_form.cpp, src/NewProject/device_planner_form.h
Updates:
* Fixed issue with wrong base device when user Edit device
* Fixed window title for Edit device
* Fixed issue when filters reset to default after custom device created/edited/removed
*  Improvement. When user press Create device, selected device in the table will be used as base
* Improve message readability when remove device
=> Fixed few issues related to custom device

CMakeLists.txt, src/Configuration/CFGCommon/CFGCommon.cpp, src/Configuration/CFGCommon/CFGCommon.h, src/Configuration/ModelConfig/ModelConfig.h, src/Configuration/ModelConfig/ModelConfig_IO.cpp, tests/unittest/CFGCommon/CFGCommon_test.cpp, tests/unittest/ModelConfig/apis/config_attributes.mapping.json, tests/unittest/ModelConfig/golden/model_config.ppdb.json, tests/unittest/ModelConfig/model_config_netlist.ppdb.json
Add infrastructure to validate pin location.
- For example in I_BUF_DS and O_BUF_DS case, the respective pad pin must be assigned as a pair
- The unit test netlist PPDB is hand-crafted, but generated by yosys. 
- This is because of issue https://rapidsilicon.atlassian.net/browse/EDA-2652. Once it is fixed, will retest
> 
> - [x] Engine
> - [ ] Continous …
=> Add pin validation infra: prepare for IO_BUF_DS

src/NewProject/CustomLayout.cpp, src/NewProject/CustomLayout.h, src/NewProject/CustomLayout.ui, src/NewProject/CustomLayoutBuilder.cpp, tests/TestGui/gui_new_project.tcl
Updates:
* Add custom device resources shown during creation/modification
* Indicate error in case some of the parameters is not valid.
=> For the custom device window, show device resources when user change any of fields

src/NewProject/CustomLayoutBuilder.cpp
The vpr layout has additional rox/columns for IOs.
This abstract that away.
Row,Column numbers are real fabric numbers now. Resource count is corrected.
Offsets for DSP/BRAM are also adjusted.
=> Account for io row/column

.github/workflows/build_centos_image.yml.yml, .github/workflows/install_centos_dependencies_build.sh, CMakeLists.txt
To build FOEDAG with CPython, install bzip2-devel libffi-devel on CentOS
=> Install bzip2-devel libffi-devel on centos 7 for Python

CMakeLists.txt, src/DeviceModeling/device_instance.h
…ssian.net/browse/EDA-2699
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [ ] Break back-compatibility. If so, please …
=> Revoking work in progress for instance nets at elaboration time (EDA-2699)

.github/workflows/Dockerfile, .github/workflows/install_centos_dependencies_build.sh, .github/workflows/main.yml, CMakeLists.txt
Install Python 3.8 on all OS so that other system can use it.
=> Install python3.8 on All OS

CMakeLists.txt, src/Configuration/ModelConfig/ModelConfig_IO.cpp
1. This is to reenable full flow IO bitstream generation. It was disabled previous via https://github.com/os-fpga/FOEDAG/pull/1531
2. In our current Python build,
- All CI platform are using Python 3.8 or above, except CENTOS, it is using Python 3.6
- When embeded Python into C code, CENTOS C code will be compiled based on 3.6 library (.so or .a)
- However in Raptor, we ship precompiled python which is in version 3.8
- This version mismatch (what we have in CI CENTOS vs what we …
=> Reenable bitstream generation

.github/workflows/Dockerfile, .github/workflows/main.yml, CMakeLists.txt
The latest GitHub runners are using MacOS 14 now and this MacOS version does not support Python 3.8 while we still want to support Python 3.8 due to CentOS 7 so making sure CI runs on MacOS 12
=> Update main.yml to stick to macos 12 to support py3.8

CMakeLists.txt, src/Configuration/ModelConfig/ModelConfig.h, src/Configuration/ModelConfig/ModelConfig_IO.cpp, tests/unittest/ModelConfig/apis/config_attributes.mapping.json, tests/unittest/ModelConfig/golden/model_config.ppdb.json, tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit, tests/unittest/ModelConfig/model_config_netlist.ppdb.json, tests/unittest/ModelConfig/ric/CLK_BUF.api.json, tests/unittest/ModelConfig/ric/PLL.api.json, tests/unittest/ModelConfig/ric/gbox_top.tcl, tests/unittest/ModelConfig/ric/virgotc_bank.tcl
Changes include:
a. Provide API to validate parameter(s) before using it. (Use case: for example PLL need to validate the multiply and division params)
b. Prepare to support clock routing to gearbox. In the progress understanding RTL what to set in bits to support. 
Testing:
a. ported code (together with https://github.com/os-fpga/yosys_verific_rs/pull/626) to latest NS Raptor manually
b. run batch, batch_gen2 and batch_gen3 test.
>
> …
=> IO bitstream generation

CMakeLists.txt, src/Compiler/CompilerOpenFPGA.cpp
1. Allow device level config map if it exists.
2. If it does not exists, we will use family series config map. 
3. This allow further customization for a particular device if neccessary
Testing:
- ported code (together with https://github.com/os-fpga/Raptor/pull/1684) to latest NS Raptor manually
- run batch, batch_gen2 and batch_gen3 test. (Note: and2_bitstream had been failing locally)
Code coverage failed:
- no unit test in Compiler to execute a project
- hence it is expected …
=> Allow device level of config map if it exists

CMakeLists.txt, src/Compiler/CompilerOpenFPGA.cpp
VPR SDC parser requires we surround complex name like FOO[0].bar with {} 
Result: {FOO[0].bar}
=> sdc fix for VPR parser

CMakeLists.txt, src/Configuration/ModelConfig/ModelConfig.cpp, src/Configuration/ModelConfig/ModelConfig_IO.cpp, tests/unittest/ModelConfig/ModelConfig_IO_test.cpp, tests/unittest/ModelConfig/apis/config_attributes.mapping.json, tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json, tests/unittest/ModelConfig/golden/model_config.ppdb.json, tests/unittest/ModelConfig/golden/model_config.property.json, tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit, tests/unittest/ModelConfig/model_config_netlist.negative.ppdb.json, tests/unittest/ModelConfig/model_config_netlist.ppdb.json, tests/unittest/ModelConfig/ric/virgotc_bank.tcl
1. This is to revert back the relax code, which was done because there is possible at previous critical time: C++, RIC model, RIC API and Config Mapping file might not consumed by NS Raptor at the same time (in case out-of-sync update). 
- now that everything is in place, undo one of the relax code
3. Update all unit test to use latest CC pin since NS Raptor is already being updated with latest PT. 
Testing:
- ported code to latest NS Raptor manually
- run batch, batch_gen2 and …
=> Stricten the relax code. Update unittest

CMakeLists.txt, src/DeviceModeling/DeviceModeling.cpp, src/DeviceModeling/DeviceModeling.h, src/DeviceModeling/device_instance.h, src/DeviceModeling/device_modeler.h
> - implementing 
set_io_bank
set_logic_location
set_phy_address
get_io_bank
get_phy_address
get_logic_location
=> Dm updates 3

src/Compiler/CompilerOpenFPGA.h, src/Main/main.cpp
Change exec name 'pin_c' to 'stars' in FOEDAG.
Currently 'stars' have all the source code of pin_c, plus more.
'stars' can function as pin_c for a couple of month now, I tested it many times.
'stars' detects "pin_c mode" is one of 3 ways:
1. if the absolute exec path (argv[0]) ends in "pin_c"
2. if the "--function pin_c" command line option is specified
3. if there is a typical set of pin_c options, i.e. "--csv" and "--assign_unconstrained_pins"
With this FOEDAG  checkin, the 3rd way will be used, temporarily.
This is the 1st step of multi-stage process of combining 'pin_c' and 'stars' functionality in component named 'planner'.
The executable name will be 'pln', because there is already an app with exec called 'planner' (GNOME planner).
Further stages will be:
- change exec name 'pin_c' …
=> merge pin_c with stars (1st step) pin_c -> stars in FOEDAG

CMakeLists.txt, src/Compiler/Compiler.cpp, src/Simulation/Simulator.cpp
Change list:
* Add an error message for TCL commands `add_design_file` and `add_simulation_file` when the file name is missing
* Add an error message for all types of simulations when simulation file(s) are missing from the project.
=> Add error message when simulation files are missing

src/DeviceModeling/device_block.h, src/DeviceModeling/device_modeler.h
> -FOR EDA-2854 Introduce new boolean to indicate if this is configurable block when defining block using "define_block" command
=> Dm update 10

CMakeLists.txt, src/Configuration/ModelConfig/ModelConfig.cpp
Referring to https://rapidsilicon.atlassian.net/browse/EDA-2854, which Manadher propose to use "property" feature to identify config or none-config block
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> ### Impact of the …
=> Skip block if property has no_configuration set

CMakeLists.txt, src/DeviceModeling/device_block.h, src/DeviceModeling/device_modeler.h
> - Revoking redundant method to mark any module for "no_configuration"
=> Revoking the block alteration to indicate "not for config"

CMakeLists.txt, src/Compiler/CompilerOpenFPGA.cpp, src/Compiler/Constraints.cpp, src/Compiler/Constraints.h, src/Configuration/ModelConfig/ModelConfig.cpp, src/Configuration/ModelConfig/ModelConfig_IO.cpp, src/Configuration/ModelConfig/ModelConfig_IO.h, tests/unittest/ModelConfig/ModelConfig_IO_test.cpp, tests/unittest/ModelConfig/apis/config_attributes.mapping.json, tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json, tests/unittest/ModelConfig/golden/model_config.ppdb.json, tests/unittest/ModelConfig/golden/model_config.simplified.property.json, tests/unittest/ModelConfig/golden/model_config_detail.txt, tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit, tests/unittest/ModelConfig/golden/model_config_io_bitstream.negative.detail.bit, tests/unittest/ModelConfig/model_config_netlist.negative.ppdb.json, tests/unittest/ModelConfig/model_config_netlist.ppdb.json, tests/unittest/ModelConfig/ric/O_SERDES_CLK.api.json
Improvement:
- Allow overwrite any of IO bitfield via TCL using set_attr command
- Take into consideration of error from extractor (new feature added via https://github.com/os-fpga/yosys_verific_rs/pull/652)
- Allow parameter validation to ignore failure if parameter(s) are not defined, since we support default setting if parameter is not defined.
- Add O_SERDES_CLK support in unit test
- Add more parameter validation in unit test (config mapping file)
Testing:
- ported code to …
=> Improvement and add O_SERDES_CLK test case

CMakeLists.txt, src/Compiler/Reports/AbstractReportManager.cpp, src/Compiler/Reports/AbstractReportManager.h, src/Compiler/Reports/BitstreamReportManager.cpp, src/Compiler/Reports/BitstreamReportManager.h, src/Compiler/Reports/ITaskReportManager.h, src/Compiler/Reports/PackingReportManager.cpp, src/Compiler/Reports/PackingReportManager.h, src/Compiler/Reports/PlacementReportManager.cpp, src/Compiler/Reports/PlacementReportManager.h, src/Compiler/Reports/RoutingReportManager.cpp, src/Compiler/Reports/RoutingReportManager.h, src/Compiler/Reports/SynthesisReportManager.cpp, src/Compiler/Reports/SynthesisReportManager.h, src/Compiler/Reports/TimingAnalysisReportManager.cpp, src/Compiler/Reports/TimingAnalysisReportManager.h, src/Main/Tasks.cpp
Fixed issue with Timing Analysis report. When generate json report, wrong data were taken for Timing Analysis because of the wrong report ID. Now report id can be taken from it's integer id and converted to string if needed.
=> Fixed report generation for Timing Analysis

CMakeLists.txt, src/Simulation/Simulator.cpp
Change list:
* When user perform clean files for simulation (Clean all or one task clean), do not show error message that simulation files missing.
=> Remove error message about Simulation files missing when clean step performs

CMakeLists.txt, src/Compiler/CompilerOpenFPGA.cpp, src/Compiler/Constraints.cpp, src/Configuration/ModelConfig/ModelConfig.cpp, src/Configuration/ModelConfig/ModelConfig_IO.cpp, src/Configuration/ModelConfig/ModelConfig_IO.h, tests/unittest/ModelConfig/ModelConfig_IO_test.cpp, tests/unittest/ModelConfig/ModelConfig_test.cpp, tests/unittest/ModelConfig/apis/config_attributes.mapping.json, tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json, tests/unittest/ModelConfig/golden/model_config.ppdb.json, tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit, tests/unittest/ModelConfig/golden/model_config_io_bitstream.negative.detail.bit
> - [x] To address an existing issue - https://rapidsilicon.atlassian.net/browse/CASTORIP-156
There is existing PLL architectural flaw, which we need to configure the ICB data twice:
- first time with pll_PLLEN set to 0
- second time with pll_PLLEN set to 1 (if the PLL is used)
This PR generates two ICB data:
- io_bitstream.bit (first time)
- io_bitstream.post.bit (second time)
- this only happen if the device series is Gemini or Virgo
Testing done:
- Port this PR to latest NS Raptor
- Run test/batch, test/batch_gen2. test/batch_gen3
>
> #### What does this pull …
=> Workaround for PLL architectural flaw

CMakeLists.txt, src/IPGenerate/IPGenerator.cpp
Fixed issue with IP configurator, when user wasn't able to generate same IP but with different version.
=> Fixed issue when user can't add same IP with different versions

CMakeLists.txt, src/Main/Settings.cpp, src/Main/Tasks.cpp, src/MainWindow/main_window.cpp, tests/unittest/IPGenerator/IPGenerator_test.cpp
Change list:
* Fixed creating run_1 folder when no project
* Fixed static path to settings files, this cause save files to wrong path.
* Fixed unit tests
=> Fixed creating run_1 folder when no project specified

CMakeLists.txt, src/Main/ProjectFile/CompilerComponent.cpp, src/Main/ProjectFile/CompilerComponent.h
Load data from config.json after project file loaded. This will fix clock names in the reports
=> Load data from config.json after project file loaded. This will fix clock names in the reports

CMakeLists.txt, src/Compiler/Compiler.cpp, src/Compiler/Compiler.h
Change list:
* Update `create_design` tcl command. If project already exists, it will be closed automatically before new project created. No need to use close_project command. Now this command guaranty that new project will be created.
=> Improve create_design tcl command. Close prev design automaticaly before create new one

CMakeLists.txt, src/Main/CommandLine.cpp, src/Main/CommandLine.h, src/MainWindow/Session.cpp, src/MainWindow/Session.h, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h
Run TCL script, new feature that allow user to execute tcl script from the GUI. User action can be found under File->Run TCL script..
The flow is:
1. Ask user if close previous project
2. Allow user select tcl script
3. Run selected script
=> Add Run TCL script action to allow run script from the UI

CMakeLists.txt, src/ProjNavigator/FileExplorer.cpp, src/ProjNavigator/FileExplorer.h
Change list:
* Remove label in file explorer with current path
* Add tool tip for ".." top level folder that shows full path
=> Remove label with curren path and add tool tip instead

CMakeLists.txt, etc/help.txt, src/Compiler/Compiler.cpp, src/Compiler/Compiler.h, src/IPGenerate/IPGenerator.cpp, src/IPGenerate/IPGenerator.h, src/MainWindow/main_window.cpp, src/MainWindow/main_window.h, src/NewProject/ProjectManager/DesignFileWatcher.cpp, src/NewProject/ProjectManager/project_manager.cpp, src/NewProject/ProjectManager/project_manager.h, src/ProjNavigator/sources_form.cpp, src/ProjNavigator/sources_form.h, src/ProjNavigator/tcl_command_integration.cpp, src/ProjNavigator/tcl_command_integration.h, src/Utils/StringUtils.cpp, src/Utils/StringUtils.h, tests/Testcases/IPGenerate/test_ipgenerate_modules.tcl
Change list:
* Add context menu for ip instance: Add IP to Design. This menu is disabled in the Gate-level project type
* Add new tcl command: ip_add_to_design
* New command covered by tcl test
* Help updated
=> Add context menu for IP that allow to add IP files to design

CMakeLists.txt, src/Compiler/TaskManager.cpp
Fixed launching of the P&R View from Routing task.
=> Fixed issue when launching PnR view from routing tasks re-runs the previous tasks again

src/MainWindow/main_window.cpp, src/PinAssignment/PinAssignmentCreator.cpp
Change list:
* Open Pin Planner for production build
* Fixed parsing of *.pin file when pin name appears in `{}` brackets.
=> Task/eda 3015/pin planner fixed busses

src/Compiler/Reports/IDataReport.h, src/Compiler/Reports/TableReport.cpp, src/Compiler/Reports/TableReport.h, src/Compiler/Reports/TimingAnalysisReportManager.cpp, src/Main/ReportGenerator.cpp, src/Main/ReportGenerator.h, src/Main/Tasks.cpp
Change list:
* Add new feature to reports creation that allow open files instead of generating some report.
* Change list of the timing analysis reports
=> Add few more reports to timing analysis which open log files

CMakeLists.txt, src/IpConfigurator/IPDialogBox.cpp, src/Utils/CMakeLists.txt, src/Utils/JsonWriter.cpp, src/Utils/JsonWriter.h, tests/TestInstall/CMakeLists.txt
Replace `json` with `JsonStreamWriter`. 
`json` writes everything as string while `JsonStreamWriter` writes directly string to file. So if string contains number, the number type will be written into the file.
=> Fixed wrong json types for IP Catalog communication

CMakeLists.txt, src/NewProject/add_source_form.cpp
Remove top module auto-detect indication for simulation. No other changes regarding auto-detect feature.
Simulation:
Design:
=> Remove top module auto-detect indication for simulation

CMakeLists.txt, src/MainWindow/main_window.cpp, src/ProjNavigator/sources_form.cpp, src/ProjNavigator/sources_form.h
Update list of actions which are disabled during compilation:
* Project Settings
* Add Design files.../Add Constraint files../Add Simulation files...
* Remove File
* Close Project
* Simulate IP
* Add IP to design
* Reconfigure IP
* Remove IP from Project
* Delete IP
=> Disable actions from cotext menu of the Project table when compilation is running

src/Compiler/CompilerOpenFPGA.cpp
> #### FOEDAG Limitation
> - [ ] We don't specify top module for VHDL design during elaboration which leads to ghdl error "no top module found"
> #### Solution
> - [ ] This feature will specify the top-module for pure vhdl design.
> #### PR Limitations
> - Top module is not specified for mixed language designs (Conflicting top module name for VHDL and Verilog/SystemVerilog designs).
=> Specify Top Module for Pure VHDL Design Exclusively During Design Elaboration

CMakeLists.txt, tests/TestGui/compiler_flow/raptor_run.sh
Xvfb could not run in the CGA environment due to conflicting dependencies with Verdi. Removed Verdi to let Xvfb run.
Fix the parser path.
=> Fix Xvfb error for GUI Testcase in CGA

CMakeLists.txt, src/Configuration/ModelConfig/ModelConfig.cpp, src/Configuration/ModelConfig/ModelConfig_IO.cpp, src/Configuration/ModelConfig/ModelConfig_IO.h, src/Configuration/ModelConfig/ModelConfig_IO_resource.cpp, src/Configuration/ModelConfig/ModelConfig_IO_resource.h, tests/unittest/ModelConfig/apis/config_attributes.mapping.json, tests/unittest/ModelConfig/design_edit.sdc, tests/unittest/ModelConfig/golden/bitstream_setting.xml, tests/unittest/ModelConfig/golden/config.py, tests/unittest/ModelConfig/golden/model_config.negative.ppdb.json, tests/unittest/ModelConfig/golden/model_config.ppdb.json, tests/unittest/ModelConfig/golden/model_config_io_bitstream.backdoor.txt, tests/unittest/ModelConfig/golden/model_config_io_bitstream.detail.bit, tests/unittest/ModelConfig/golden/model_config_io_bitstream.negative.detail.bit, tests/unittest/ModelConfig/model_config_netlist.negative.ppdb.json, tests/unittest/ModelConfig/model_config_netlist.ppdb.json, tests/unittest/ModelConfig/ric/I_BUF.api.json, tests/unittest/ModelConfig/ric/I_BUF_DS.api.json, tests/unittest/ModelConfig/ric/O_BUF.api.json, tests/unittest/ModelConfig/ric/O_BUFT.api.json, tests/unittest/ModelConfig/ric/O_BUFT_DS.api.json, tests/unittest/ModelConfig/ric/O_BUF_DS.api.json, tests/unittest/ModelConfig/ric/PLL.api.json, tests/unittest/ModelConfig/ric/gbox_mode.api.json, tests/unittest/ModelConfig/ric/pll_refmux.tcl
<Put hold on while waiting RIC API be updated - see https://rapidsilicon.atlassian.net/browse/VIRGO-384>
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
Together with https://github.com/os-fpga/yosys_verific_rs/pull/760 and https://github.com/os-fpga/Raptor/pull/1923, this changes auto-determine the needed core-clock. All the clock input is treated as fast clock
Also initial support of bidirectional pin
Testing done:
- Port all these 4 changes (3 …
=> Support new core clock flow

.github/workflows/main.yml, CMakeLists.txt
[macOS] GCC 11 will be removed from all macOS images on August 12](https://github.com/actions/runner-images/issues/10213)
> - [ x] To address an existing issue.
GitHub MacOS 12 has no longer GCC-11 so bumping the GCC version to 12.
=> Update main.yml to use GCC 12 as GCC 11 is no longer available on macos image

CMakeLists.txt, src/Compiler/CompilerOpenFPGA.cpp
> - [ X] To address an existing issue. If so, please provide a link to the issue: <EDA-3138>
=> flat_routing option in OpenFPGA script EDA-3138

CMakeLists.txt, src/Simulation/Simulator.cpp, src/Utils/FileUtils.cpp, src/Utils/FileUtils.h
Icarus ignores the timescale present in the SDF file, so we need 
to scale the content from ps to ns to match the simulation timescale.
=> SDF timescale conversion for Icarus

src/Compiler/Compiler.cpp, src/Simulation/Simulator.cpp, src/Simulation/Simulator.h
Adding new internal getter API, move TB generation code to Raptor Tcl code
=> path getter, messages api, move tb generation to Tcl

.gitmodules, CMakeLists.txt
OpenOCD a submodule, contains git2cl as submodule. Git2Cl is hosted on `git.savannah.nongnu.org`. Sometimes this website faces issues entertaining the cloning request especially if the request originates from GitHub Actions servers. Since our code base compilation does not directly depend upon OpenOCD so, we can remove it to avoid the failure of GH Actions due to this issue.
=> Remove openOCD submodule

CMakeLists.txt, src/MainWindow/main_window.cpp, src/PinAssignment/PinAssignmentBaseView.cpp
Bug: qobject_cast<QComboBox*> returns 0 now the type is ComboBox
Use brute force cast for now.
=> Fix Pin Planner crash

CMakeLists.txt, src/Compiler/CompilerOpenFPGA.cpp
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
=> Use extractor generated CLK pin XML if possible

.github/workflows/main.yml, CMakeLists.txt
> - [ x] To address an existing issue. If so, please provide a link to the issue: 
GitHub Actions runners are now using Ubuntu 24.04 and we don't support it so using Ubuntu 22.04
> 
> 
> 
> 
> 
>
> 
> 
> 
> 
> 
> 
> - [ ] Engine
> - [ x] Continous Integration (CI) scripts
> - [ ] Require a change on Quality of …
=> Use github runner os 22.04
